- som_infoenergia/__init__.py
- som_infoenergia/giscedata_polissa.py
- som_infoenergia/giscedata_polissa_view.xml
- som_infoenergia/pdf_tools/topdf.py
- som_infoenergia/report/infoenergia_header.mako
- som_infoenergia/som_infoenergia_enviament.py
- som_infoenergia/som_infoenergia_lot.py
- som_infoenergia/som_infoenergia_view.xml
- som_infoenergia/tests/test_lot_enviament.py
- som_infoenergia/tests/test_wizard_send_reports.py
- Split infoenergia.py in two (enviament & lot) and fix tests. 
- Add field autoconsum & tarifa. 
- Minor fixes.
> Split infoenergia models in two (enviament & lot)

- som_webforms_helpers/giscedata_polissa_tarifa.py
With changes introduced with Nous Peatges, GKWH product will have more than 2 energy periods.
> Update get_tariff_prices function to allow GKWH to have more than 2 energy periods

- scripts/cron_informe_cnmc_canvi_comer.py
- scripts/cron_switchingreport.sh
- scripts/somenergia.css
Script to use GISCE wizard to generete "CNMC cambio comercializador" report
> Script to generate informe CNMC canvi comer

- som_account_invoice_pending/som_account_invoice_pending_data.xml
Enviament SMS Recordatori factura pendent (CAT)
SOM ENERGIA. Hola, et recordem que tens 1 FACTURA PENDENT DE PAGAMENT. Import pendent: X € (import de la factura). Contracte: XXXX (nº de contracte). Per contactar: 900103605
Enviament SMS Recordatori factura pendent (CAST)
SOM ENERGIA. Hola, te recordamos que tienes 1 FACTURA PENDIENTE DE PAGO. Importe pendiente: X € (import de la factura). Contrato: XXXX (nº de contracte). Para contratar: 900103605
> ADD plantilla SMS factura pendent

- som_informe/report/components/A301/A301.py
- som_informe/report/components/B101/B101.py
- som_informe/report/components/B103/B103.py
- som_informe/report/components/C101/C101.py
- som_informe/report/components/C201/C201.py
- som_informe/report/components/D102/D102.py
- som_informe/report/components/E101/E101.py
- som_informe/report/components/E108/E108.py
- som_informe/report/components/M101/M101.py
- som_informe/report/components/M105/M105.py
- som_informe/report/components/ProcesA3/ProcesA3.py
- som_informe/report/components/ProcesATR/ProcesATR.py
- som_informe/report/components/ProcesATR/__init__.py
- som_informe/report/components/ProcesB1/ProcesB1.py
- som_informe/report/components/ProcesB2/ProcesB2.py
- som_informe/report/components/ProcesC1/ProcesC1.py
- som_informe/report/components/ProcesC2/ProcesC2.py
- som_informe/report/components/ProcesD1/ProcesD1.py
- som_informe/report/components/ProcesE1/ProcesE1.py
- som_informe/report/components/ProcesM1/ProcesM1.py
- som_informe/report/components/ProcesR1/ProcesR1.py
- som_informe/report/components/R105/R105.py
- som_informe/report/components/header/header.mako
- som_informe/wizard/wizard_create_technical_report.py
Objectives
Attempt to create a first release for the som_informe module
Solve problems form the multiples ,meges from previus PR's
Apply translations
> fix issues from multiple merges and translations

- som_informe/i18n/es_ES.po
- som_informe/report/components/D101/D101.py
- som_informe/report/components/ProcesC1/ProcesC1.py
Objectives
Attempt to create a first release for the som_informe module
Solve problems
Apply translations
> Fix some issues and add translation file

- som_informe/requirements.txt
Modify requirements of som addons module
> Modify requirements

- scripts/cron_informe_cnmc_canvi_comer.py
- scripts/cron_switchingreport.sh
L'script s'executa cada 15 de mes, creant l'informe de canvi de comercialitzadora per a la CNMC, del mes anterior. 
Les modificacions faciliten executar l'script per mesos anteriors
> Suport per la execució de informes antics

- som_switching/__terp__.py
- som_switching/giscedata_polissa.py
- som_switching/giscedata_polissa_view.xml
Add data_alta_autoconsum field in polissa form and tree views.
Add data_ultima_lectura_f1 field in tree view.
> Add data_alta_autoconsum in polissa

- som_infoenergia/__init__.py
- som_infoenergia/__terp__.py
- som_infoenergia/giscedata_cups.py
- som_infoenergia/giscedata_polissa.py
- som_infoenergia/som_enviament_massiu.py
- som_infoenergia/som_infoenergia_view.xml
Add a new function to compute consum anual
> Add consum anual lectures

- som_switching/__terp__.py
- som_switching/giscedata_switching_data.xml
- som_switching/giscedata_switching_notification_data.xml
Noves plantilles rebuig B1:
Motiu C7
Motiu C1
Motiu 39
> ADD new b1 templates

- powersms/wizard/wizard_send_sms.py
Add a new specific function for "to" field to obtain the telefon numbers when multiple lines were selected by the user.
> Fix to value when multiple sms

- powersms/wizard/wizard_send_sms.py
This case was not taking into account as part of the fix of multiple sms
> Add empty to value when create_empty_number is true

- som_webforms_helpers/__terp__.py
- som_webforms_helpers/giscedata_polissa_tarifa.py
- som_webforms_helpers/tests/__init__.py
- som_webforms_helpers/tests/tarifes_demo.xml
- som_webforms_helpers/tests/test_tarifes.py
Add a date paramter to the function get_tariff_prices to obtain prices in the given date.
If not date is set remains the current behavior of the function.
> Select tariffs in a date if it is given

- som_switching/giscedata_switching_notification_data.xml
- som_webforms_helpers/tests/tarifes_demo.xml
Hem de deixar la condició com estava fins que arreglem la d'autoconsum
> Fix rebuig notification until autoconsum is fixed

- som_switching/tests/tests_wizard_comment_to_F1.py
- som_switching/wizard/wizard_comment_to_F1.py
- som_switching/wizard/wizard_comment_to_F1_view.xml
- afegir text al text existent
- Substituir text existent
- eliminar el text existent
> Add new functionalities wizard comment f1

- som_informe/__terp__.py
- som_informe/i18n/es_ES.po
- som_informe/i18n/som_informe.pot
- som_informe/report/components/InvoiceF1C/InvoiceF1C.mako
- som_informe/report/components/InvoiceF1C/InvoiceF1C.py
- som_informe/report/components/InvoiceF1C/__init__.py
- som_informe/report/components/InvoiceF1NG/InvoiceF1NG.mako
- som_informe/report/components/InvoiceF1NG/InvoiceF1NG.py
- som_informe/report/components/InvoiceF1NG/__init__.py
- som_informe/report/components/InvoiceF1RA/InvoiceF1RA.mako
- som_informe/report/components/InvoiceF1RA/InvoiceF1RA.py
- som_informe/report/components/InvoiceF1RA/__init__.py
- som_informe/report/components/InvoiceF1Unsupported/InvoiceF1Unsupported.mako
- som_informe/report/components/InvoiceF1Unsupported/InvoiceF1Unsupported.py
- som_informe/report/components/InvoiceF1Unsupported/__init__.py
- som_informe/report/components/InvoiceFE/InvoiceFE.mako
- som_informe/report/components/InvoiceFE/InvoiceFE.py
- som_informe/report/components/InvoiceFE/__init__.py
- som_informe/report/components/__init__.py
- som_informe/report/components/component_utils.py
- som_informe/requirements.txt
- som_informe/tests/__init__.py
- som_informe/tests/som_informe_demo.xml
- som_informe/tests/test_wizard_create_technical_report.py
- som_informe/wizard/wizard_create_technical_report.py
> WIP: invoice components

- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
- giscedata_facturacio_comer_som/report/components/invoice_details_td_excess_power_quarterhours/invoice_details_td_excess_power_quarterhours.mako
Modificar el text treien els dies de càlcul del kpx degut a un boe
https://secure.helpscout.net/conversation/1752876030/10901274?folderId=3510978
Es mostraven els dies
No es mostren els dies
[x] Reiniciar serveis
[] Actualitzar mòdul
> canvi de texts a la factura en pdf amb excés de potència quartihoraria per BOE

- giscedata_facturacio_comer_som/report/components/emergency_complaints/emergency_complaints.mako
Canviar el link  de la Junta arbitral
El link antic ja no existeix
Apareix el link correcte
[] Reiniciar serveis
[] Actualitzar mòdul
> Canviar el link  de la Junta arbitral

- giscedata_facturacio_comer_som/report/components/emergency_complaints_td/emergency_complaints_td.mako
Canviar el link de la Junta arbitral
El link antic ja no existeix
Apareix el link correcte
[] Reiniciar serveis
[] Actualitzar mòdul
> Canviar el link de la Junta arbitral pel component TD

- som_factures_paper/__init__.py
- som_factures_paper/__terp__.py
- som_factures_paper/giscedata_polissa.py
- som_factures_paper/giscedata_polissa_view.xml
- som_factures_paper/wizard/wizard_paper_invoice_som.py
Implementar les millores demanades al assistent de factures en paper:
https://trello.com/c/Y5vDBFAu/4714-0-8-p7-add-p10-externalitzar-la-facturaci%C3%B3-en-paper
S'adaptava al treball manual
S'adapta als nous requeriments
- som_factures_paper
> Millores per l'assistent de factures en paper

- som_switching/__init__.py
- som_switching/wizard/__init__.py
- som_switching/wizard/giscedata_switching_mod_con_wizard.py
- Quan hi ha canvi de titular setejar enviament a email per defecte
https://trello.com/c/Y5vDBFAu/4714-0-8-p7-add-p10-externalitzar-la-facturaci%C3%B3-en-paper
Mantenia el camp enviament de la nova pòlissa exactament igual que a l'antiga
Seteja el camp enviament a 'email' a la nova polissa
[x] Reiniciar serveis
[] Actualitzar mòdul
> quan hi ha canvi de titular setejar enviament a email per defecte

- account_account_som/__init__.py
- account_account_som/__terp__.py
- account_account_som/security/ir.model.access.csv
- account_account_som/tests/tests_wizard_account_balance.py
- account_account_som/wizard/__init__.py
- account_account_som/wizard/wizard_account_balance_report.py
- account_account_som/wizard/wizard_account_balance_report_view.xml
El balanç comptable triga molt i volem poder fer-lo de manera asíncrona i rebre'l per correu electrònic quan estigui fet (tant en PDF com en Excel)
> Poder fer el balanç contable asincron

- som_factures_paper/__init__.py
- som_factures_paper/__terp__.py
- som_factures_paper/giscedata_polissa.py
- som_factures_paper/giscedata_polissa_view.xml
- som_factures_paper/wizard/wizard_paper_invoice_som.py
Reverts Som-Energia/openerp_som_addons#97
> Revert "Revert "Millores per l'assistent de factures en paper""

- scripts/send_invoice_emails.py
- scripts/send_invoice_emails.sh
Els scripts d'enviar factures estaven al GIST https://gist.github.com/tinogis/c6b7476812e8b670ccb50ba98075c240
Bugbuster
El script estava en un gist
Esta en un repositori
> Moure scripts de enviar factures

- giscedata_facturacio_comer_som/giscedata_facturacio_comer_data.xml
- giscedata_facturacio_comer_som/report/giscedata_facturacio_comer_som.py
Permetre generar pdf's signats digitalment des de l'erp
https://trello.com/c/44T6fWyh/4773-0-6-p6-ep247-an%C3%A0lisi-i-automatitzaci%C3%B3-de-la-facturaci%C3%B3-amb-signatura-digital-des-de-lerp
No signava o signava tots els documents
Signa els documents depenent d'una condició encara per detallar a la targeta.
> Permetre generar pd's de factura signats digitalment

- som_facturacio_calculada/__terp__.py
- som_facturacio_calculada/som_facturacio_calculada_data.xml
Afegir un nou mòdul per a la implementació de la facturació calculada a partir de corbes
No existia el mòdul
- Instal·lar i actualitzar el mòdul   `som_facturacio_calculada`
> Nou mòdul per a la facturació calculada a partir de corbes

- .circleci/config.yml
> Corregir el circleci config per afegir el nou repositori poweremail-modules

- giscedata_facturacio_comer_som/report/giscedata_facturacio_comer_som.py
Arreglar el bug introduit en https://github.com/Som-Energia/openerp_som_addons/pull/101 que feia que deixés de funcionar la impressió varies factures en un sol PDF
https://secure.helpscout.net/conversation/1814881967/11421976/
Només s'imprimia la primera
S'imprimeixen totes. Només que calgui firmar-ne una digitalment, es firmarà tot el PDF
> FIX: No es podien imprimir més d'una factura generant un sol PDF

- giscedata_facturacio_som/__terp__.py
- giscedata_facturacio_som/wizard/__init__.py
- giscedata_facturacio_som/wizard/wizard_model_list_from_file.py
- giscedata_facturacio_som/wizard/wizard_model_list_from_file_data.xml
Afegir el model d'extra lines al `wizard_model_list_from_file`
No es podia llistar aquest model
Es pot llistar les extralines a partir de l'Id d'aquestes 
-  `giscedata_facturacio_som`
> Afegir el model d'extra lines al `wizard_model_list_from_file`

- Manteniment.md
Simplificar les comandes necessàries per aplicar els canvis a la branca rolling del servidor de testing
Hi havia més comandes
Amb menys comandes s'aconsegueix el mateix resultat
> Simplificar el fitxer de manteniment

- som_infoenergia/__terp__.py
- som_infoenergia/security/ir.model.access.csv
- som_infoenergia/tests/test_wizards.py
- som_infoenergia/wizard/__init__.py
- som_infoenergia/wizard/wizard_create_enviaments_from_partner.py
- som_infoenergia/wizard/wizard_create_enviaments_from_partner_view.xml
https://trello.com/c/scSVUPL6/4888-0-0-p9-assistent-de-lot-denviament-massiu-per-afegir-partners-massivament
Es poden afegir partners als lots d'enviament
> added partner to assistent lot d'enviament massiu

- som_facturacio_calculada/giscedata_polissa.py
- som_facturacio_calculada/som_facturacio_calculada_data.xml
- som_facturacio_calculada/tests/test_polissa_lectures_calculades.py
- som_facturacio_calculada/wizard/wizard_crear_lectures_calculades.py
- som_facturacio_calculada/wizard/wizard_crear_lectures_calculades_view.xml
Millorar la creació de lectures calculades
https://trello.com/c/TtIeLzka/4981-0-8-p2-prova-pilot-facturaci%C3%B3-setmanal
S'incorporen noves comprovacions
> Millorar la creació de lectures: tenir en compte els casos ATR i intentar fer el màx entre (21,14,7) dies

- som_facturacio_comer/__init__.py
- som_facturacio_comer/__terp__.py
- som_facturacio_comer/giscedata_facturacio.py
- som_facturacio_comer/giscedata_facturacio_contracte_lot.py
- som_facturacio_comer/giscedata_facturacio_contracte_lot_view.xml
- som_facturacio_comer/giscedata_facturacio_data.xml
- som_facturacio_comer/giscedata_facturacio_factura_view.xml
- som_facturacio_comer/giscedata_facturacio_validation.py
- som_facturacio_comer/giscedata_facturacio_validation_data.xml
- som_facturacio_comer/giscedata_polissa.py
- som_facturacio_comer/giscedata_polissa_view.xml
- som_facturacio_comer/security/ir.model.access.csv
- som_facturacio_comer/tests/__init__.py
- som_facturacio_comer/tests/tests_facturacio_warnings.py
- som_facturacio_comer/tests/tests_wizard_open_factures_send_mail.py
- som_facturacio_comer/tests/tests_wizard_revert_incident_fact_contracte_lot.py
- som_facturacio_comer/wizard/__init__.py
- som_facturacio_comer/wizard/wizard_move_contracts_to_prev_lot.py
- som_facturacio_comer/wizard/wizard_open_factures_send_mail.py
- som_facturacio_comer/wizard/wizard_open_factures_send_mail_view.xml
- som_facturacio_comer/wizard/wizard_revert_incident_fact_contracte_lot.py
- som_facturacio_comer/wizard/wizard_revert_incident_fact_contracte_lot_view.xml
Afegir el mòdul  `som_facturacio_comer`
> Afegir el mòdul `som_facturacio_comer`

- som_infoenergia/report/components/tail_text/tail_text.py
Calcular la data de renovació a partir de la data d'alta
https://trello.com/c/ScBdYZ11/4974-ep215p1modificar-datafinal-de-les-plantilles-30-61-indexada
Es calculava a partir de la data final de la modificació contractual activa
Es calcula a partir de la data d'alta
> Calcular la data de renovació a partir de la data d'alta

- som_account_invoice_pending/wizard/wizard_tugesto_invoices_export.py
> Fix PR 118

- som_autofactura/__init__.py
- som_autofactura/__terp__.py
- som_autofactura/security/ir.model.access.csv
- som_autofactura/som_autofactura_data.xml
- som_autofactura/som_autofactura_task.py
- som_autofactura/som_autofactura_task_view.xml
- som_autofactura/wizard/__init__.py
- som_autofactura/wizard/wizard_autofactura.py
- som_autofactura/wizard/wizard_autofactura.xml
Fer el procés de facturació de manera automàtica
https://trello.com/c/t30p8a4P/4926-0-0-p9-ep247-opci%C3%B3-facturaci%C3%B3-per-proc%C3%A9s-autom%C3%A0tica
S'han d'anar fent els procesos un a un.
Hi ha un assistent, que prèvia configuració, farà els processo que estigui marcats com actius, un darrere l'altre.
> Nou mòdul som_autofactura

- uiqmako_helpers/__init__.py
- uiqmako_helpers/__terp__.py
- uiqmako_helpers/security/ir.model.access.csv
- uiqmako_helpers/tests/__init__.py
- uiqmako_helpers/tests/test_uiqmako_helper.py
- uiqmako_helpers/uiqmako_helper.py
Add module to implement UI-QMako helper functions.
> Add render_mako_text function for uiqmako tool

- som_switching/__terp__.py
- som_switching/giscedata_atc.py
- som_switching/giscedata_atc_data.xml
- som_switching/giscedata_atc_view.xml
- som_switching/giscedata_polissa_view.xml
- som_switching/security/ir.model.access.csv
- som_switching/wizard/__init__.py
- som_switching/wizard/wizard_create_atc_from_polissa.py
- som_switching/wizard/wizard_create_atc_from_polissa.xml
https://trello.com/c/e6Ka1ry0/5082-0-6-p31-ep247-crear-nou-camp-i-model-per-etiquetatge-de-cacs
> Add tags to ATC

- som_facturacio_comer/giscedata_facturacio_contracte_lot.py
Arreglar la vista de pòlissa lot columna numero d'incidències
Incidència https://secure.helpscout.net/conversation/1906256330/12268061
No s'actualitza
Si actualitza
* som_facturacio_comer
> changing the store function base member

- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
Arreglar falta de p3 al descompte
https://secure.helpscout.net/conversation/1905932473/12267540
el pdf falla
el pdf no falla
> better contidion

- som_facturacio_comer/tests/__init__.py
- som_facturacio_comer/tests/tests_wizard_refund_rectify_from_origin.py
Afegir tests pel wizar_refund_recitify_from_origin
> WIP; Afegir tests pel wizar_refund_recitify_from_origin

- som_informe/wizard/wizard_create_technical_report.py
Arreglar el comportament del wizard del som_informe
https://secure.helpscout.net/conversation/1898481819/12244111?folderId=5804115
Petava
no petarà ¿?
> Fix reference before assignment

- som_switching/giscedata_switching.py
Sobreescriu mètode d'activació de casos ATR per tenir comportament anterior
> Sobreescriu mètode d'activació de casos ATR per tenir comportament anterior

- giscedata_facturacio_comer_som/giscedata_facturacio_comer_som_demo.xml
- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
- giscedata_facturacio_comer_som/i18n/es_ES.po
- giscedata_facturacio_comer_som/i18n/giscedata_facturacio_comer_som.pot
- giscedata_facturacio_comer_som/report/components/hourly_curve/hourly_curve.css
- giscedata_facturacio_comer_som/report/components/hourly_curve/hourly_curve.mako
- giscedata_facturacio_comer_som/report/components/invoice_details_td_energy/invoice_details_td_energy.mako
- giscedata_facturacio_comer_som/report/components/invoice_details_td_energy_generationkwh/invoice_details_td_energy_generationkwh.mako
- giscedata_facturacio_comer_som/report/components/invoice_details_td_excess_power_maximeter/invoice_details_td_excess_power_maximeter.mako
- giscedata_facturacio_comer_som/report/components/invoice_details_td_excess_power_quarterhours/invoice_details_td_excess_power_quarterhours.mako
- giscedata_facturacio_comer_som/report/components/invoice_details_td_generation/invoice_details_td_generation.mako
- giscedata_facturacio_comer_som/report/components/invoice_details_td_other_concepts/invoice_details_td_other_concepts.mako
- giscedata_facturacio_comer_som/report/components/invoice_details_td_power/invoice_details_td_power.mako
- giscedata_facturacio_comer_som/report/report_giscedata_facturacio_factura_comer.mako
- giscedata_facturacio_comer_som/tests/tests_FacturacioFacturaReport_some.py
Afegir dates de les línies d'energia, potència i GkWh al PDF de la factura
> WIP: Afegir dates de les línies d'energia, potència i GkWh al PDF de la factura

- scripts/clean_mailboxes.py
Moure en un lloc segur aquest script que estava en una carpeta temporal
https://secure.helpscout.net/conversation/1926667165/12585044?folderId=3063377
> Afegim script del servirdor al repositori

- som_infoenergia/i18n/es_ES.po
- som_infoenergia/i18n/som_infoenergia.pot
- som_infoenergia/report/components/antecedents/antecedents.mako
- som_infoenergia/report/components/energy_prices/energy_prices.mako
- som_infoenergia/report/components/energy_prices/energy_prices.py
- som_infoenergia/report/components/power_prices/power_prices.mako
- som_infoenergia/report/components/power_prices/power_prices.py
- som_infoenergia/report/components/tail_text/tail_text.mako
- som_infoenergia/report/components/tail_text/tail_text.py
- som_infoenergia/report/report_indexed_offer.css
- Modificar adjunts 
- Fer que les potències de la taula del PDF adjunt s'actualitzin automàticament i no haguem de fer incidència cada cop que canviem preus.
https://trello.com/c/m8Vk8aBf/5128-0-4-p6-modificar-plantilles-mails-no-renovaci%C3%B3
Es mostraven textos ara no requerits
Les tarifes de pòtència estaven fixades
S'han canviat els textos requerits 
S'utiltza la funció get_atr_price per obtenir els preus automàticament
- som_infoenergia
> Modifica adjunts tarifa indexada

- www_som/__terp__.py
- www_som/giscedata_facturacio.py
- www_som/tests/tests_factura.py
- www_som/www_som_data.xml
- Actualitzar la lògica de `www_som`
- https://trello.com/c/Sz4M3lGx/5102-0-0-p24-ep255-tpv-limitar-factures-que-es-poden-pagar
> Actualitzar la lògica de `www_som`

- som_autofactura/__terp__.py
- som_autofactura/som_autofactura_task.py
- som_autofactura/som_autofactura_task_view.xml
- som_autofactura/wizard/wizard_autofactura.py
Detectar els passos intermedis desactivats en el procés de facturació automàtic.
https://secure.helpscout.net/conversation/1937046182/12664060?folderId=3063374
Si un pas intermedi estava desactivat, continuava amb el següent.
Si un pas intermedi estava desactivat s'atura el procés
> FIX autofactura: Quan un pas intermig està desactivat, detectar-ho

- som_infoenergia/som_infoenergia_data.xml
Afegir email template per correu rebaixa iva 5%
https://trello.com/c/Zx5IvB4Q/5197-0-0-p12-actualitzaci%C3%B3-de-tarifes-1-07-2022-rebaixa-iva-5
No existia el template
Template afegit
> Add email template for rebaixa iva 5%

- som_switching/giscedata_atc_data.xml
Fer que les tags de CACs no es sobreescriguin amb l'update
https://secure.helpscout.net/conversation/1942179604/12697202?folderId=3063374
- `som_switching`
> Fer que les tags de CACs no es sobreescriguin amb l'update

- som_account_invoice_pending/wizard/wizard_tugesto_invoices_export.py
- Canvi en els requeriments, l'identificador només pot ser numèric.
> VAT number only indentifier

- .github/workflows/integration_config.yml
- som_facturacio_switching/__init__.py
- som_facturacio_switching/__terp__.py
- som_facturacio_switching/facturacio_extra.py
- som_facturacio_switching/facturacio_extra_view.xml
- som_facturacio_switching/giscedata_facturacio.py
- som_facturacio_switching/giscedata_facturacio_importacio_linia.py
- som_facturacio_switching/giscedata_facturacio_importacio_linia_view.xml
- som_facturacio_switching/giscedata_facturacio_switching.py
- som_facturacio_switching/giscedata_facturacio_switching_cron.xml
- som_facturacio_switching/giscedata_facturacio_switching_error.py
- som_facturacio_switching/giscedata_facturacio_switching_error_data.xml
- som_facturacio_switching/giscedata_polissa.py
- som_facturacio_switching/pricelist_demo_data.xml
- som_facturacio_switching/res_municipi.py
- som_facturacio_switching/security/ir.model.access.csv
- som_facturacio_switching/tests/__init__.py
- som_facturacio_switching/tests/test_giscedata_facturacio_importacio_linia.py
- som_facturacio_switching/tests/test_import_f1.py
- som_facturacio_switching/tests/test_polissa.py
- som_facturacio_switching/tests/test_wizard_delete_reimport_2001_f1.py
- som_facturacio_switching/tests/test_wizard_gestio_text_to_polissa.py
- som_facturacio_switching/wizard/__init__.py
- som_facturacio_switching/wizard/wizard_delete_reimport_2001_f1.py
- som_facturacio_switching/wizard/wizard_delete_reimport_2001_f1_view.xml
- som_facturacio_switching/wizard/wizard_gestio_text_to_polissa.py
- som_facturacio_switching/wizard/wizard_gestio_text_to_polissa_view.xml
- som_facturacio_switching/wizard/wizard_model_list_from_file.py
- som_facturacio_switching/wizard/wizard_model_list_from_file_data.xml
Moure mòdul som_facturacio_switching
> Moure mòdul som_facturacio_switching

- .github/workflows/integration_config.yml
> Desfer canvis per proves

- som_switching/demo/som_switching_demo_data.xml
- som_switching/giscedata_atc_data.xml
- som_switching/security/som_switching.xml
- som_switching/tests/tests_unlink_atc.py
Borrar un pudb i moure data a demo data
https://secure.helpscout.net/conversation/1974245209/13001412/
Hi havia un pudb i es creava un demo data on no tocava
No hi és i es crea el demo data on toca
> Remove pudb from test

- scripts/change_partner_in_invoice.py
Canviar el partner en una factura
Per exemple https://secure.helpscout.net/conversation/1873043849/12046187?folderId=3510978
> Change partner in invoice

- som_switching/__terp__.py
Treure del terp un fitxer inexistent
> Removed security

- som_crawlers/models/som_crawlers_config.py
- som_crawlers/models/som_crawlers_result.py
- som_crawlers/models/som_crawlers_task.py
- som_crawlers/models/som_crawlers_task_step.py
- som_crawlers/views/som_crawlers_config_view.xml
- som_crawlers/views/som_crawlers_result_view.xml
- som_crawlers/views/som_crawlers_task_view.xml
- Fitxer adjunt al resultat, no tasca. 
- Nou camp bool resultat. 
- Tasques i resultats failed en vermell. 
- Segons al timestamp. 
- Camp distribuidora. 
- Cerca tasques per últim resultat
- Descripció curta de la darrera execució
https://trello.com/c/veSn4jg9/5319-0-4-p26-ep259-revisar-m%C3%B2dul-massiveimporter-i-posar-ho-a-productiu
> Modificacions vàries al som_crawlers

- .github/workflows/integration_config.yml
- som_crawlers/data/som_crawlers_data.xml
- som_crawlers/models/som_crawlers_task_step.py
- som_crawlers/scripts/script_run_crawler.py
- som_crawlers/tests/wizard_executar_tasca_tests.py
Update the som crawlers module to support crawlers with inheritance such as iberdrola.
https://trello.com/c/veSn4jg9/5319-0-4-p26-ep259-revisar-m%C3%B2dul-massiveimporter-i-posar-ho-a-productiu
No es podia
Es pot
- [x ] Reiniciar serveis
- [x ] Actualitzar mòdul
> Support inherited files

- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
- giscedata_facturacio_comer_som/i18n/es_ES.po
- giscedata_facturacio_comer_som/i18n/giscedata_facturacio_comer_som.pot
- giscedata_facturacio_comer_som/report/components/invoice_details_td_energy/invoice_details_td_energy.mako
> Afegir el MAJ al PDF de la factura

- som_switching/giscedata_polissa_view.xml
- Solucionar la incidència on es trenca la vista de polissa per prioritats.
- https://secure.helpscout.net/conversation/2014767929/13349772?folderId=3063374
Vista trencada
Arreglat
`som_polissa`
> FIX: `giscedata.polissa` priority view added

- som_crawlers/data/som_crawlers_data.xml
- som_crawlers/models/som_crawlers_task.py
- som_crawlers/models/som_crawlers_task_step.py
- som_crawlers/tests/__init__.py
- som_crawlers/tests/som_crawlers_task_step_tests.py
- som_crawlers/views/som_crawlers_config_view.xml
Afegir crawlers i posar les captures de pantalla quan hi ha error, als adjunts del ERP
https://trello.com/c/5wTzFoGH/5369-0-0-p20-ep259-crawlers-altres-distris-de-lexcel?filter=member:erpcorreu
Els adjunts es guardaven al Minio
Ara es guarden a Mongo
> Migrar captures d'error a Mongo

- som_crawlers/data/som_crawlers_data.xml
- som_crawlers/models/som_crawlers_task_step.py
- som_crawlers/scripts/script_run_crawler.py
Actualitzar el data de som_crawlers
> Update som_crawlers data

- som_crawlers/models/som_crawlers_task.py
Que divendres tingui en compte que el pròxim dia d'execució és dilluns (el cap de setmana no compta)
> Arreglar dia pròxima execució quan és divendres

- scripts/clean_mailboxes.py
Add errors retry to existing mailboxes retry script. 
557 mails in outbox mailbox on 10/04/2022
Only retried for draft and outbox mailboxes
Also retries for errors
> Retry script also for errors

- som_crawlers/data/som_crawlers_data.xml
Fix viesgo to support inheritance and add crawler for process D
https://secure.helpscout.net/conversation/2036863123/13460494?folderId=3063374
All crawlers executed viesgo.py
Every task executes its file
> Fix viesgo and add D

- som_crawlers/data/som_crawlers_data.xml
- som_crawlers/models/som_crawlers_config.py
- som_crawlers/models/som_crawlers_task.py
- som_crawlers/models/som_crawlers_task_step.py
- som_crawlers/scripts/script_run_crawler.py
- som_crawlers/spiders
- som_crawlers/views/som_crawlers_config_view.xml
Spike primer crawler d'exportació
https://trello.com/c/NH2exW5s/5368-0-4-p24-ep259-revisar-crawler-endesa
No hi ha cap exportador
Primer exportador per la distri Anselmo
> Add anselmo exporter

- som_infoenergia/report/infoenergia_header.mako
- som_infoenergia/som_infoenergia_lot.py
De resultes d'una modificació de la forma del pdf d'Infoenergia cal modificar el header per tal de que la desanonimització del pdf resulti amb un pdf correcte amb les dades personals allà on toca.
https://trello.com/c/Pph0PzbQ/5468-0-2-add-html-som-desanonimitzador
PDF's d'infoenergia amb dades personals allà on no toca
PDF's d'infoenergia amb dades personals allà on toca
> Canvis al pdf de Infoenergia

- som_crawlers/data/som_crawlers_step_data.xml
- som_crawlers/data/som_crawlers_task_data.xml
- som_crawlers/tests/wizard_executar_tasca_tests.py
Afegir les tasques de descàrrega de fitxers F1
https://trello.com/c/0aed0uG0/5453-0-4-p23-ep259-crawler-cide-f1s
No es baixaven
Es baixen
> add cide f1

- som_inversions/wizard/wizard_liquidacio_interessos.py
El wizard de liquidació d'interessos donava error quan es clicava al botò de "Crear i mostrar factures". Aquest error era degut a que el new_cursor es tancava dins del for.
https://secure.helpscout.net/conversation/2053327851/13548499?folderId=3063374
No es creaven les factures
Les factures es crean i es mostren
> Fix liquidacio interessos

- som_crawlers/data/som_crawlers_config_data.xml
- som_crawlers/data/som_crawlers_step_data.xml
- som_crawlers/data/som_crawlers_task_data.xml
- som_crawlers/scripts/script_run_crawler.py
Fix multiple issues with som crawlers
Some data .xml were wrong, 
Fixed data, check path before creating file
> some fixes

- som_crawlers/__terp__.py
- som_crawlers/models/som_crawlers_config.py
- som_crawlers/security/ir.model.access.csv
- som_crawlers/views/som_crawlers_config_view.xml
- som_crawlers/wizard/__init__.py
- som_crawlers/wizard/wizard_canviar_contrasenya.py
- som_crawlers/wizard/wizard_canviar_contrasenya.xml
- som_crawlers/wizard/wizard_canviar_usuari.py
- som_crawlers/wizard/wizard_canviar_usuari.xml
- Posar camp `log` que guardi historial de canvis, l'usuari que l'ha fet, i el valor antic del camp.
> Add logs to som_crawlers_config

- powersms/wizard/wizard_send_sms.py
Permetre afegir telèfons des del formulari.
https://secure.helpscout.net/conversation/2003539317/13277566?folderId=3063374
Només s'fagien els telèfons del partner
Permet afegir telèfons des del formulari
> Allow add telephons from form

- som_crawlers/models/som_crawlers_task_step.py
Add milisecons to filenames to make them unique
Som crawlers can fail with multiple workers
every filename is different
> Add seconds to filename

- som_switching/giscedata_switching_data.xml
Crear una nova plantilla per quan el titular del D101 és diferent al titular de la pòlissa
https://trello.com/c/6ZFRzRan/5447-0-0-p10-auto-notificaci%C3%B3-d1-titular-contracte-diferent-titular-installaci%C3%B3
No existia la plantilla
Existeix la plantilla
> new template when D101 titular != titular

- som_crawlers/__terp__.py
- som_crawlers/models/__init__.py
- som_crawlers/models/som_crawlers_holiday.py
- som_crawlers/models/som_crawlers_task.py
- som_crawlers/security/ir.model.access.csv
- som_crawlers/tests/__init__.py
- som_crawlers/tests/som_crawlers_task_tests.py
- som_crawlers/views/som_crawlers_holiday_view.xml
- som_crawlers/views/som_crawlers_result_view.xml
Afegir la possibilitat de declarar dies on no s'executin les tasques de som_crawlers i que tampoc s'executin els festius declarats per REE
https://trello.com/c/Vv0U2Gix/5503-0-0-p28-ep259-desconectar-el-massive-els-festius-o-dates-que-let-no-treballa
No es tenien en compte els festius
Es tenen en compte i es poden crear
> Add som crawlers off days

- som_crawlers/models/som_crawlers_task.py
- som_crawlers/models/som_crawlers_task_step.py
Fix mongo errors
https://secure.helpscout.net/conversation/2067162805/13735335?folderId=3063411
> Fix mongo errors

- som_atc/__init__.py
- som_atc/__terp__.py
- som_atc/models/__init__.py
- som_atc/models/giscedata_atc.py
- som_atc/views/giscedata_atc_view.xml
Afegir nous filtres a la vista de casos atc
https://trello.com/c/xYcrXfIj/5455-0-2-p39-afegir-columnes-al-llistat-tots-els-casos-atc
No existien
Existeixen
> New filters

- som_atc/wizard/wizard_change_state.py
En rebre un cas ATR D1 d'auto si no tenim les dades de la titular de la generació es genera un CAC per a demanar el consentiment. En la obertura del cas es genera un email a la titular de la generació per a demanar-li el consentiment per a disposar de les seves dades. Es requereix que paral.lelament al primer mail s'envïi un altre email en el mateix sentit a la titular del contracte.
https://trello.com/c/6ZFRzRan/5447-0-0-p10-auto-notificaci%C3%B3-d1-titular-contracte-diferent-titular-installaci%C3%B3
S'envia mail només a la titular de la generació de l'autoconsum
S'envia (si cal) també un mail al titular de la pòlissa
> Notificar tant titular de generació com titular de contracte quan D101 sense relació contractual

- som_polissa_condicions_generals/report/condicions_particulars.mako
Fer que les CCPP mostrin l'IVA no reduit, quan ja no és aplicable
https://trello.com/c/lnw9RtEp/5502-0-2-p1-tarifes230101-actualitzaci%C3%B3-de-tarifes-creaci%C3%B3-del-lot-i-enviament
Es mostraven sempre els preus rebaixats, perquè es discriminava només per potència <= 10
A més a més de la potència, es fan servir les variables de configuració `charge_iva_10_percent_when_start_date`, `iva_reduit_get_tariff_prices_end_date` i `charge_iva_10_percent_when_available`.
> Fer que les CCPP mostrin l'IVA no reduit, quan ja no és aplicable

- som_polissa_condicions_generals/i18n/som_polissa_condicions_generals.pot
- som_polissa_condicions_generals/report/condicions_particulars.mako
Posar la data d'avui a la "data de firma" del contracte
Reunió "Data signatura de contracte CCPP" del 29/11/2022
Sortia la data en que s'havia omplert el formulari
Surt la data en que s'ha imprés
> CCPP data de firma al dia que s'envia

- som_atc/views/giscedata_atc_view.xml
Fer que el llistat de "Tots els casos ATC" et mostri els casos de les pòlisses de baixa
https://secure.helpscout.net/conversation/2080590515/13808889?folderId=3063374
Només sortien els casos ATC de pòlisses actives
Surten els casos ATC  de pòlisses actives i no actives
> Afegir "active_test" a l'acció de "Tots els casos"

- som_account_invoice_pending/demo/som_account_invoice_pending_demo_data.xml
- som_account_invoice_pending/som_account_invoice_pending_data.xml
- som_account_invoice_pending/tests/update_pending_states_tests.py
Arreglar tests
Necessari per fer la targeta https://trello.com/c/0wmismMk/5371-0-6-p12-modificar-la-data-de-lestat-pendent-duna-factura
No passava testos
Passen testos
> Fix FIX som_account_invoice_pending tests

- scripts/reset_sequences_january_1th.py
Script que actualitza les seqüències de factures, el primer dia de l'any.
Es feia manual
Es fa automàtic
S'ha d'afegir al cron
> Add script update sequence on January 1th

- som_facturacio_switching/tests/tests_wizard_refund_rectify_from_origin.py
- som_facturacio_switching/wizard/wizard_refund_rectify_from_origin.py
- som_facturacio_switching/wizard/wizard_refund_rectify_from_origin_view.xml
Afegir detecció de factures amb generationkwh, activar l'enviament per email al wizard d'abonar i rectificar i solucioar problemes.
https://trello.com/c/pR4wkVef/5574-0-5-p4-ep285-get-millores-en-el-bot%C3%B3-refacturacions-erp
No ho feia
Ho farà
> Add generation kwh detection to f1 observation field

- som_facturacio_comer/wizard/wizard_informe_factures_dades_desagregades.py
Afegir les tarifes de tipus TDVE al wizard per obtenir dades desagregades per contracte
https://secure.helpscout.net/conversation/2098625739/13901223?folderId=3063374
No es buscaven les TDVE
es busquen les TDVE
> Add TDVE to wizard

- som_crawlers/models/som_crawlers_task_step.py
Arreglar error en blanc quan el crawler no retorna 
https://secure.helpscout.net/conversation/2130818800/14102158/
Abans l'error estava buit
Ara et diu quan ha petat quan el crawler retorna error buit
> Fix blank error when crawler return nothing

- som_account_invoice_pending/update_pending_states.py
Arreglar el codi introduït a la PR 275
https://secure.helpscout.net/conversation/2129672765/14096163?folderId=3063374
Es canviava l'estat pendent de totes les factures en procés de tall diàriament
Ja no
> fix pr 275

- som_crawlers/models/som_crawlers_task.py
- som_crawlers/models/som_crawlers_task_step.py
- som_crawlers/tests/wizard_executar_tasca_tests.py
Arreglar els missatges d'error buits
Es reescriu el missatge d'output per cada step de la tasca 
Es guarda l'ouput de cada tasca
> refactor messages

- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
Eliminar de la cua els errors originat sper les factures amb id 17300366,17818668,17626642, 17626642, 17615463
https://secure.helpscout.net/conversation/2142708166/14161166?folderId=3063374
Genera errors repetits a la cua failed del rq
Genera els pdf amb els camps en blanc
> Arreglar errors recurrents a la cua del rq referents al pdf de factura

- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
- giscedata_facturacio_comer_som/report/components/amount_destination_td/amount_destination_td.mako
Actualitzar els percentatges de repartiment dels càrrecs i peatges.
https://trello.com/c/pPa0cHsu/5508-0-4-p16-canviar-el-cos-del-correu-de-factura
Percentatges desactualitzats.
Percentatges actualitzats.
> Update percentage of charges and tolls to 2023 BOE

- som_informe/i18n/es_ES.po
- som_informe/i18n/som_informe.pot
- som_informe/report/components/CollectExpectedCutOffDate/CollectExpectedCutOffDate.mako
- som_informe/report/components/InvoiceF1NG/InvoiceF1NG.mako
- som_informe/report/components/InvoiceF1NG/InvoiceF1NG.py
- som_informe/report/components/InvoiceF1R/InvoiceF1R.mako
- som_informe/report/components/InvoiceFE/InvoiceFE.mako
- som_informe/report/components/InvoiceFE/InvoiceFE.py
- som_informe/report/components/R102/R102.mako
- som_informe/report/components/TableInvoices/TableInvoices.mako
- som_informe/report/components/footer/footer.mako
- som_informe/report/components/header/header.mako
- som_informe/report/components/header/header.py
Afegir linea de potència contractada a la capçalera del informe tècnic i corregir typos i traduccions.
https://trello.com/c/sA1RtHah
no la mostrava la potència contractada, hi havien typos i faltaven traduccions.
ara la mostra la potència contractada,i el informe ix correctament sense typos i amb totes les traduccions correctes.
> Add include contracted energy in technical report

- powersms/wizard/wizard_send_sms.py
Arreglar un error que no permetia enviar SMS de manera massiva.
https://secure.helpscout.net/conversation/2085619802/13850511
En enviar diversos SMS a diferents persones no es buscava de manera correcta els telèfons destí.
Es van a buscar correctament els telèfons on enviar cada SMS.
> Fix malfunction when sending SMS from multiple invoices

- som_webforms_helpers/giscedata_polissa_tarifa.py
Que traga bé les tarifes a la web
https://sentry.somenergia.coop/organizations/som-energia/issues/128588/?project=11&query=is%3Aunresolved
fallava i no les treria
les ha de traure
> Fix include cases without '/' in the name of unit meassures

- som_informe/report/components/M106/M106.mako
Fix data creacio forgotten in commit https://github.com/Som-Energia/openerp_som_addons/commit/f6cac51fa4830bb9d42379cc67e385d2d0fa9fdb
https://secure.helpscout.net/conversation/2171325806/14325732?folderId=3063374
Petava al fer el informe
No peta
> Fix field data_creacio

- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
- giscedata_facturacio_comer_som/report/components/partner_info/partner_info.mako
- giscedata_facturacio_comer_som/tests/tests_FacturacioFacturaReport_some.py
- Eliminar de la factura el titular del compte bancari
- Eliminar el NIF/CIF de dades del pagament
- Mostar només últims dígits del compte bancari
https://trello.com/c/82pnFDPM/5657-0-2-get-modificar-pdf-dades-de-pagament
- Es mostrava el titular, el NIF/CIF i es mostrava tot el compte bancari excepte els últims dígits
- No es mostra el titular del compte bancari
- No es mostra el NIF/CIF de dades del pagament
- Només es mostren els últims dígits del compte bancari
- S'han arreglat els testos
> Modificar camps del component de la factura partner_info

- som_facturacio_switching/wizard/wizard_refund_rectify_from_origin.py
Acabar les millore proposades a la targeta https://trello.com/c/Z2WaTYy3/5600-0-2-p14-ep285-get-millores-en-el-bot%C3%B3-refacturacions-erp
https://trello.com/c/Z2WaTYy3/5600-0-2-p14-ep285-get-millores-en-el-bot%C3%B3-refacturacions-erp
Errors
No errors
> millores al wizard de re-facturació de f1's

- som_infoenergia/wizard/wizard_create_enviaments_from_csv.py
Solucionar enviament
Pollastre
> fix to int

- som_webforms_helpers/exceptions/__init__.py
- som_webforms_helpers/exceptions/som_webforms_exceptions.py
- som_webforms_helpers/giscedata_polissa_tarifa.py
- som_webforms_helpers/som_webforms_helpers_data.xml
- som_webforms_helpers/tests/tarifes_demo.xml
- som_webforms_helpers/tests/test_tarifes.py
Obtenir preus d'una tarifa segons un rang de dates. 
Obtenir preus històrics per un contracte.
https://trello.com/c/CmZot0Oo/5345-0-8-p3-infoenergia-api-com-usuari-de-lapi-dinfoenergia-vull-obtenir-el-llistat-de-tarifes-de-la-cooperativa
Només es tornaven preus de l'última llista de preus
Torna preus en un rang de dades.
- som_webforms_helpers
> New get tariff prices by date range

- som_infoenergia/report/infoenergia_header.mako
Que el cups no sobreescrigui
https://secure.helpscout.net/conversation/2202524778/14602121
https://trello.com/c/4RxCsjtj/4313-0-2-ajustos-cap%C3%A7alera-informes-infoenergia
sobreescrivia
no sobreescriu
> Moure el cups a la dreta per l'informe de infoenergia

- som_crawlers/data/som_crawlers_config_data.xml
- som_crawlers/data/som_crawlers_step_data.xml
- som_crawlers/data/som_crawlers_task_data.xml
Afegir el crawler de Santa Coloma de Queralt
https://trello.com/c/RYcRKjcy/5714-0-1-ep259-m-afegir-crawler-del%C3%A9ctrica-municipal-de-santa-coloma-de-queralt-sl
> add scq crawler

- som_facturacio_switching/wizard/wizard_refund_rectify_from_origin.py
Afegir tolerància a la comprovació de factures generades.
Arreglar comentaris  quan es fan múltiples F1's 
https://trello.com/c/Z2WaTYy3/5600-0-2-p14-ep285-get-millores-en-el-bot%C3%B3-refacturacions-erp
no ho feia
ho fa
> modificar el wizard de refacturació per afegir toleràncies i arreglar errors

- som_facturacio_switching/wizard/wizard_refund_rectify_from_origin.py
Aplicar una nova lògica a la hora de refacturar F1 tipus R
https://trello.com/c/Z2WaTYy3/5600-0-2-p14-ep285-get-millores-en-el-bot%C3%B3-refacturacions-erp
no era el comportament esperat
comportament esperat
> Nova logica per wizard de refacturació de f1 tipus R

- som_switching/giscedata_switching_view.xml
Eliminar la duplicitat
Incidència verbal
no es mostren
- som_switching
> Eliminar duplicats a la vista de arbre de fitxers f1 importats

- som_facturacio_comer/giscedata_facturacio_contracte_lot_view.xml
Que aparega el camp 'Nombre total de incidencies' com a filtre en el tree de Pòlisses amb incidències.
https://secure.helpscout.net/conversation/2217806539/14678563?folderId=3063374
Després de l'actualització a la 108 ja no apareixia
Ja apareix. Ja aplicat a la vista de producció.
> Habilitar camp 'Nombre total de incidencies' a Pòlisses amb incidències

- som_indexada/__init__.py
- som_indexada/__terp__.py
- som_indexada/data/email_template_data.xml
- som_indexada/data/giscedata_polissa_category_data.xml
- som_indexada/data/product_pricelist_data.xml
- som_indexada/data/res_partner_category_data.xml
- som_indexada/exceptions/__init__.py
- som_indexada/exceptions/indexada_exceptions.py
- som_indexada/giscedata_polissa.py
- som_indexada/giscedata_polissa_modcontractual.py
- som_indexada/security/ir.model.access.csv
- som_indexada/som_indexada_webforms_helpers.py
- som_indexada/tests/__init__.py
- som_indexada/tests/test_indexada_exceptions.py
- som_indexada/tests/test_wizard_change_to_indexada.py
- som_indexada/wizard/__init__.py
- som_indexada/wizard/wizard_change_to_indexada.py
- som_indexada/wizard/wizard_change_to_indexada.xml
Afeigr un nou mòdul per gestionar la tarifa indexada
https://trello.com/c/dF6SJWZv/5648-ep288-a7-indexada-crear-al-erp-la-modcon-en-estat-pendent-quan-lusuari-ho-sollicita-a-la-ov
No hi havia indexada
Wizard per passar a tarifa indexada
> Add som indexada

- som_polissa_condicions_generals/report/condicions_particulars.mako
- som_polissa_condicions_generals_m101/report/condicions_particulars_m101.mako
> hotfix k from polissa

- som_polissa_condicions_generals/report/condicions_particulars.mako
- som_polissa_condicions_generals_m101/report/condicions_particulars_m101.mako
https://secure.helpscout.net/conversation/2227005675/14733530?folderId=3063374
https://secure.helpscout.net/conversation/2227005675/14733530?folderId=3063374
https://secure.helpscout.net/conversation/2227005675/14733530?folderId=3063374
https://secure.helpscout.net/conversation/2227005675/14733530?folderId=3063374
> fix esborrany contracts

- som_facturacio_switching/__terp__.py
- som_facturacio_switching/giscedata_facturacio_switching_view.xml
Hacer el campo factura_rectificada readonly
https://trello.com/c/qqh2mSD8/5719-camp-duplicat-a-fitxers-f1-importats
Campo editable
Campo no editable
> Hacer el campo factura_rectificada readonly

- som_indexada/__terp__.py
- som_indexada/demo/product_pricelist_demo_data.xml
- som_indexada/exceptions/indexada_exceptions.py
- som_indexada/som_indexada_webforms_helpers.py
- som_indexada/tests/__init__.py
- som_indexada/tests/test_wizard_change_to_indexada.py
- som_indexada/tests/test_wizard_change_to_periodes.py
- som_indexada/wizard/wizard_change_to_indexada.py
- som_indexada/wizard/wizard_change_to_indexada.xml
Poder passar pòlisses de tarifa indexada a períodes.
https://trello.com/c/EXB6sia3
No hi havia la funcionalitat de canvi de indexada a períodes.
S'ha adaptat el _wizard_ i s'ha afegit una acció a la pòlissa per poder fer aquest canvi. S'ha adaptat el `webforms_helpers` perquè el canvi a indexada segueixi funcioni com fins ara, a l'espera de permetre també el canvi invers.
> Afegim funcionalitat de canvi de indexada a períodes

- som_facturacio_switching/giscedata_facturacio_importacio_linia.py
- som_facturacio_switching/giscedata_facturacio_importacio_linia_view.xml
- som_facturacio_switching/migrations/5.0.2.108.0/post-0001_delete_codi_rectificada_anulada.py
- som_facturacio_switching/migrations/5.0.2.108.0/pre-0001_delete_codi_rectificada_anulada.py
Eliminar camp antic i crear script de migració per guardar les dades (por si aca)
https://trello.com/c/AeAh5kGt/5721-0-1-extraure-camp-duplicat-a-fitxers-f1-importats
Sortien dos camps, el de GISCE i el de Som
Surt només el camp de GISCE
> Eliminar camp antic i crear script de migració per guardar les dades (por si aca)

- som_indexada/wizard/wizard_change_to_indexada.py
https://secure.helpscout.net/conversation/2245273216/14924324?folderId=3063374
https://secure.helpscout.net/conversation/2245273216/14924324?folderId=3063374
https://secure.helpscout.net/conversation/2245273216/14924324?folderId=3063374
https://secure.helpscout.net/conversation/2245273216/14924324?folderId=3063374
> fix canaries

- som_facturacio_switching/giscedata_facturacio_importacio_linia.py
Corregir la cerca de F1s en fase 1
https://trello.com/c/wx1666Mk/5746-0-6-get-analitzar-cron-per-reimportar-f1s-a-la-nit
No trobava els F1s en fase 1
Trobarà els F1s en fase 1
> Fix phase 1 f1s search

- som_infoenergia/report/infoenergia_header.mako
Arreglar espaiament i lletres a Informe Infoenergia
https://trello.com/c/4RxCsjtj/5671-0-2-ajustos-cap%C3%A7alera-informes-infoenergia
Saltava el text malament i quedaven les lletres solapades
En principi no hauria de passar més a menys que sigui un text llarguíssim
Realment no s'ha de fer res, només desplegar
> Arreglar espaiament i lletres a Informe Infoenergia

- som_informe/i18n/es_ES.po
- som_informe/report/components/InvoiceF1A/InvoiceF1A.py
- som_informe/report/components/InvoiceF1C/InvoiceF1C.py
- som_informe/report/components/InvoiceF1NG/InvoiceF1NG.py
- som_informe/report/components/InvoiceF1R/InvoiceF1R.py
- som_informe/report/components/InvoiceF1Unsupported/InvoiceF1Unsupported.py
- som_informe/report/components/InvoiceFE/InvoiceFE.py
- som_informe/report/components/TableReadings/TableReadings.mako
- som_informe/report/components/TableReadings/TableReadings.py
- Millores en l'informe tècnic.
https://trello.com/c/FKmbgUA5/5709-0-4-afegir-columna-informe-t%C3%A8cnic
- Hi havia petits errors i faltava una columna en el resum de factures de distribuïdora.
- Columna a la dreta en el quadre resum de factures de distribuïdora amb la informació de la factura que anul·la o rectifica l’F1 tipus R o A.
- Es modifica informació de la columna “tipus factura” perquè quan l'F1 és R, hi aparegui R i no RA.
- A la cronologia, les factures de distribuïdora es mostra la data correcta.
> Millores en l'informe tècnic

- som_indexada/wizard/wizard_change_to_indexada.py
Deixar correctament les modcons actuals
La modcon actual passava a baixa 2
La modcon actual es queda activa
> remove baixa2 from prev modcon

- dx_invoice_supplier_renumber/__init__.py
- dx_invoice_supplier_renumber/__terp__.py
- dx_invoice_supplier_renumber/account_invoice.py
- dx_invoice_supplier_renumber/account_invoice_view.xml
- dx_invoice_supplier_renumber/wizard/__init__.py
- dx_invoice_supplier_renumber/wizard/wizard_invoice_supplier_renumber.py
> Format dx_invoice_supplier_renumber directory

- som_informe/report/components/InvoiceF1A/InvoiceF1A.py
- som_informe/report/components/InvoiceF1C/InvoiceF1C.py
- som_informe/report/components/InvoiceF1NG/InvoiceF1NG.py
- som_informe/report/components/InvoiceF1R/InvoiceF1R.py
- som_informe/report/components/InvoiceF1Unsupported/InvoiceF1Unsupported.py
- som_informe/report/components/InvoiceFE/InvoiceFE.py
- Arreglar data factura de l'informe tècnic, en alguns casos no es mostrava
https://trello.com/c/FKmbgUA5/5709-0-4-afegir-columna-informe-t%C3%A8cnic
- Quan no hi havia F1 relacionat no es mostrava cap data
- Si no hi ha F1 relacionat, es mostra la data de la factura
> Arreglar data factura de l'informe tècnic

- scripts/change_partner_in_invoice.py
- scripts/clean_mailboxes.py
- scripts/cron_informe_cnmc_canvi_comer.py
- scripts/cron_switchingreport.sh
- scripts/reimport_som_crawlers_zips.py
- scripts/requeue_failed.py
- scripts/reset_sequences_january_1th.py
- scripts/run_all_som_crawlers_tasks.py
- scripts/send_invoice_emails.py
> Add code format scripts

- som_facturacio_switching/giscedata_facturacio_importacio_linia.py
Crea un job per cada línia a importar
https://trello.com/c/wx1666Mk/5746-0-6-get-analitzar-cron-per-reimportar-f1s-a-la-nit
Feia totes les importacions en un sol job
Fa diferents jobs per cada línia
> [FIX] Crea un job per cada linia a importar

- som_polissa_condicions_generals/report/condiciones_especificas_indexada.mako
- som_polissa_condicions_generals/report/condicions_especifiques_indexada.mako
Canviar el tag blockquote per un padding. Aquests fitxers són agafats des de webforms com a base dels documents que es mostran a la Oficina Virtual. Aquest tag es renderitza malament a la web.
https://trello.com/c/vbLcoGUy/5741-ep288-b2-indexada-com-usuaria-vull-triar-la-meva-tarifa-periodos-o-indexada-quan-faig-un-nou-contracte
El tag blockquote te un comportament no desitjat a la web.
s'ha reemplaçat el tag blockquote per un padding.
> Change blockquote by padding

- som_facturacio_switching/giscedata_facturacio_importacio_linia.py
S'agafava un valor de f1 que podia no estar ple perquè s'emplena durant la fase 1
https://trello.com/c/wx1666Mk/5746-0-6-get-analitzar-cron-per-reimportar-f1s-a-la-nit
No es reimportava bé
Ara es reimporta bé
Reiniciar ERP crons
> Arreglar reimportació de F1's agafant el cups que toca

- som_indexada/__terp__.py
- som_indexada/data/email_template_data.xml
- som_indexada/giscedata_polissa_modcontractual.py
- som_indexada/security/ir.model.access.csv
- som_indexada/wizard/__init__.py
- som_indexada/wizard/wizard_massive_k_change.py
- som_indexada/wizard/wizard_massive_k_change.xml
> Create new wizard to change indexed contracts K from CSV

- som_indexada/__terp__.py
- som_indexada/data/res_config_data.xml
- som_indexada/som_indexada_webforms_helpers.py
- som_indexada/tests/test_wizard_change_to_indexada.py
- Poder fer el canvi des de l'oficina virtual de tarifa indexada a períodes.
https://trello.com/c/EXB6sia3/5697-ep288-a14-indexada-erp-modi-ov-20td-30td-dindexada-a-periodes
- El canvi sempre era de períodes a indexada.
- Es fa el canvi depenent del mode de facturació de la pòlissa, es fa de la mateixa manera al consultar la nova llista de preus.
> Adaptar webforms helpers per fer el canvi d'indexada a períodes

- som_facturacio_comer/__init__.py
- som_facturacio_comer/giscedata_facturacio_report_v2.py
Arreglar el càlcul del preu de la energia amb generation GwKh al generar el codi QR de la factura
https://trello.com/c/VWch3SZk/5801-add-get-canvis-al-codi-qr-de-la-factura
No es calculava bé
Es calcula bé
> Arrreglar el càlcul del preu de la energia amb generation GwKh al generar el codi QR de la factura

- som_inversions/report/report_liquidacions_unificat.py
> Add total_amount_untaxed to data

- som_facturacio_comer/giscedata_facturacio_report_v2.py
- Afegir correccions al QR per a complir normativa de la CNMC
https://trello.com/c/VWch3SZk/5801-add-get-canvis-al-codi-qr-de-la-factura
- El QR no complia la normativa
- Compleix! :partying_face:
> Correccions al QR per a complir normativa de la CNMC

- som_facturacio_switching/giscedata_polissa.py
- som_indexada/wizard/wizard_change_to_indexada.py
- som_switching/__terp__.py
- som_switching/giscedata_switching.py
- Seleccionar llista de preus correcta quan hi ha un canvi de tarifa d'accés
https://secure.helpscout.net/conversation/2300539653/15198844?folderId=3063374
- No es trobava llista de preus perquè no es contemplava un canvi de tarifa d'accés
- Es selecciona la llista de preus corresponent inclús si hi ha canvi de tarifa d'accés
> Force tariff to take into account tariff changes

- som_informe/report/components/InvoiceF1NG/InvoiceF1NG.py
Poder generar un informe quan no es troba le F1 de la factura (cassos molt antics)
https://secure.helpscout.net/conversation/2305734507/15239183/
L'informe fallava
L'informe es genera
> Solucionar problemes al generar Som informe quan no es troba F1 de la factura

- som_indexada/giscedata_polissa_modcontractual.py
> fix condition pending modcons

- som_polissa_condicions_generals/report/condicions_particulars.mako
- som_polissa_condicions_generals_m101/report/condicions_particulars_m101.mako
Adaptar condicions generals en report contracte quan es canvia de indexada a periodes
https://trello.com/c/mtgIYekL
Apareixien encara les condicions de indexada
Apareixen les de períodes
> Adaptar condicions generals en report contracte quan es canvia de indexada a periodes

- som_polissa_condicions_generals/report/condicions_particulars.mako
> FIX: Merged function

- som_indexada/wizard/wizard_change_to_indexada.py
Solucionar casuística en què no es troba la **_location_** de la pòlissa en contractar o canviar de tarifa.
https://secure.helpscout.net/conversation/2316888707/15302978?folderId=3063374
Hi havia casos en què la funció 'get_location_polissa' no tornava location, i en el moment de obtindre la llista de preus definitiva donava error.
Ara per defecte sempre retorna **_location_** 'peninsula'
> Fix function get_location_polissa and refactor

- som_facturacio_comer/giscedata_polissa_view.xml
- Fer grup de pagament readonly
- https://trello.com/c/Yzpc5nvb/5644-0-2-modificacions-grup-de-pagament
> Fer grup de pagament readonly

- som_facturacio_comer/giscedata_facturacio_factura_view.xml
Posar com a buscable el camp generation kwh 
https://trello.com/c/iXXPIQGF/104-bateria-t08-nous-camps-de-filtre-llistat-factures-client
No es podia buscar
Es pot buscar
> Posar com a cercable generation_kwh

- som_facturacio_switching/giscedata_facturacio_importacio_linia.py
Millorar els logs del cron de reimportació
https://secure.helpscout.net/conversation/2328153475/15369173?folderId=3063374
> improve logs

- som_informe/report/components/InvoiceF1NG/InvoiceF1NG.mako
- som_informe/report/components/InvoiceF1NG/InvoiceF1NG.py
Arreglar com es mostra l'excés de potència
https://secure.helpscout.net/conversation/2334912658/15398816?folderId=3063374
Es mostrava la quantitat
Es mostra el preu
> fix exces potencia

- som_informe/report/components/InvoiceF1NG/InvoiceF1NG.mako
- som_informe/report/components/InvoiceF1NG/InvoiceF1NG.py
Reverts Som-Energia/openerp_som_addons#415
> Revert "fix exces potencia"

- som_facturacio_switching/giscedata_facturacio_importacio_linia.py
Arreglar el script de reimportació
https://secure.helpscout.net/conversation/2340295002/15423051?folderId=3063374
petava
funciona
> code -> codes

- som_account_invoice_pending/som_account_invoice_pending_data.xml
👔 Afegir fue pending states
https://trello.com/c/Sa4ckF3d/107-modificaci%C3%B3-nom-estat-pendent-de-factures
No existia aquest pending state
Ara ja existeix
> 👔 Afegir fue pending states

- som_polissa/migrations/5.0.2.108/pre-0001_business_tariff_semantic_id_creation.py
- som_polissa/som_polissa_data.xml
- som_polissa_condicions_generals/i18n/es_ES.po
- som_polissa_condicions_generals/report/condicions_particulars.mako
- som_polissa_condicions_generals_m101/i18n/es_ES.po
- som_polissa_condicions_generals_m101/report/condicions_particulars_m101.mako
- Mostrar un text diferent de signat per les pòlisses amb categoria "Tarifa Empresa".
https://trello.com/c/mLTmX5Zf/146-canvis-a-la-firma-de-les-cp-dels-contractes-amb-tarifa-empresa
- No hi havia aquest text.
- Es crea ID semàntica per la categoria i es mostra un text diferent segons convingui.
> 👔 Modify condicions particulars signed text for contracts with business tariff category

- som_polissa/giscedata_polissa_view.xml
- som_polissa/migrations/5.0.2.108/post-0001_modify_autoconsum_field.py
Canviar nom del camp de cerca: Autoconsum -> CAU
Canviar el nombre màx de caràcters per filtrar per aquest camp
SAC: 230507
Nom: Autoconsum
Size: 18
Nom: CAU
Size: 26
> modificacions camp autoconsum id

- som_facturacio_switching/wizard/wizard_model_list_from_file_data.xml
Permetre seleccionar polisses per codi postal de CUPS a l'assitent de csv
free
no existia
ho fa però va lent
som_facturacio_switching
> Permetre seleccionar polisses per codi postal de CUPS a l'assitent de csv

- som_polissa/__init__.py
- som_polissa/giscedata_polissa_view.xml
- som_polissa/giscedata_switching_helpers.py
- som_polissa/migrations/5.0.23.9.0/post-0001_rename_bateria_virtual.py
- som_polissa/migrations/5.0.23.9.0/post-0001_rename_category_desestiment.py
- som_polissa/som_polissa_data.xml
Requires:
https://github.com/gisce/erp/pull/17835
> Change name bateria virtual to flux solar

- som_account_invoice_pending/data/custom_search_data.xml
> MOD custom search pobresa

- giscedata_facturacio_comer_som/i18n/es_ES.po
- giscedata_facturacio_comer_som/i18n/giscedata_facturacio_comer_som.pot
- giscedata_facturacio_comer_som/report/report_giscedata_facturacio_rebut_comer.mako
Canviar el text data venciment de les plantilles N57
https://trello.com/c/hrpWdTXg/164-canvi-text-data-venciment-a-document-n57
Data venciment
Document vàlid fins a:
> change data venciment text

- som_facturacio_comer/giscedata_facturacio_correu_backend.py
Afegir informació de si la pòlissa té tarifa empresa en el `data` retornat pel _report backend_ del correu de la factura per millorar el condicional que es fa servir a la plantilla.
No hi havia aquesta informació.
Retornem en el `data` aquesta informació.
> 👔 Add has_business_tariff to invoice email report backend data

- som_polissa/giscedata_polissa.py
- som_polissa/giscedata_polissa_view.xml
This reverts commit b0d05c00bfd6797fded299b3093f2c0c582869d5.
> Revert "comentar codi bateria virtual"

- www_som/__terp__.py
- www_som/security/ir.model.access.csv
Eliminar security on fa helpers
Hi ha security
Ara no hi ha security
> FIX: Eliminar Security Permisos

- som_polissa/__terp__.py
No hi havia una dependència important al terp
-
No fallava però al fer un destral podies tenir errors
Ara ja no hi ha errors als destrals
> Afegir dependència al terp

- som_atc/models/giscedata_atc.py
https://secure.helpscout.net/conversation/2377695902/15589493?folderId=3063374
> add step ids to trigger function

- som_facturacio_flux_solar/__init__.py
- som_facturacio_flux_solar/giscedata_polissa.py
- som_facturacio_flux_solar/wizard/__init__.py
- som_facturacio_flux_solar/wizard/wizard_afegir_contracte_bateria_virtual.py
Canviar el nom per defecte del Flux Solar
> Custom name for Flux solar

- som_polissa_condicions_generals/giscedata_polissa_condicions_generals_report.xml
Afegir marges automàtics al PDF del Contracte
https://trello.com/c/ei8AUlAu/157-enviament-actualitzaci%C3%B3-ccgg-aplicar-els-canvis-del-text-de-les-ccgg-a-lerp
Els marges de dalt i baix de cada pàgina es feien amb salts de línia
Els marges de dalt i baix de cada pàgina es fan amb un paràmetre del wkhtmltopdf
> Afegir marges automàtics al PDF del Contracte

- som_atc/models/giscedata_atc.py
> try new priorities

- som_facturacio_switching/__init__.py
- som_facturacio_switching/giscedata_refacturacio.py
- Mercar autorefacturat en F1 tipo G
- https://trello.com/c/z9s3SQa4/5869-get-m%C3%B2dul-refacturacions-ii-massives
> Refacturacions massives

- som_account_invoice_pending/update_pending_states.py
https://secure.helpscout.net/conversation/2400344442/15829865?folderId=3063374
https://secure.helpscout.net/conversation/2400344442/15829865?folderId=3063374
https://secure.helpscout.net/conversation/2400344442/15829865?folderId=3063374
https://secure.helpscout.net/conversation/2400344442/15829865?folderId=3063374
> 🐛 (pending_states) Fix Jaumet

- som_polissa/giscedata_polissa.py
- som_polissa/giscedata_polissa_view.xml
- som_polissa/migrations/5.0.23.12.0/pre-0001_bateria_virtual_polissa_fields.py
Requires #367 
https://trello.com/c/afLswmge/5911-gex-camp-data-alta-data-baixa-i-xec-bateria
-La PR #367 afegia camps  bateria_activa, data_activacio_bateria pero no s'omplien mai
-Els camps bateria_activa i data_activacio_bateria s'han convertit en camps funció
-S'ha afegit el camp data_baixa_bateria com a camp funció
-som_polissa
-som_polissa, pre-0001_bateria_virtual_polissa_fields.py **(v23.12.0)**
> Modificar camps referents a flux solar en la vista de polissa

- som_autoreclama/__init__.py
- som_l10n_ES_aeat_mod347/demo/som_l10n_ES_aeat_mod347_demo.xml
Al passar el mòdul fulla, petaven alguns testos
> Fix modulfulla test

- som_leads_polissa/__init__.py
- som_leads_polissa/__terp__.py
- som_leads_polissa/giscedata_crm_lead.py
- som_leads_polissa/giscedata_crm_lead_view.xml
- som_leads_polissa/wizard/wizard_crm_lead_create_entities_view.xml
- som_polissa_condicions_generals/__terp__.py
- som_polissa_condicions_generals/report/condicions_particulars.mako
> INITIAL: CRM leads Som module

- .gitignore
- som_facturacio_comer/giscedata_polissa.py
- som_facturacio_flux_solar/giscedata_bateria_virtual.py
- som_facturacio_flux_solar/giscedata_bateria_virtual_origen.py
- som_facturacio_flux_solar/giscedata_bateria_virtual_polissa.py
FIX en dates d'aplicació de descomptes i canvis en dates en general de FS
> FIX en dates d'aplicació de descomptes i canvis en dates en general de FS

- som_polissa_condicions_generals/report/condicions_particulars.mako
Corregir error per a imprimir condicions particulars de pòllissa.
https://secure.helpscout.net/conversation/2415507617/15872544?folderId=3063374
Donava error al imprimir contracte.
Ja ho trau correctament.
> (FIX) fix bug in report

- scripts/update_gisce_forks.sh
Script per actualitzar els forks que tenim de GISCE des de erp01
> Add script update forks

- som_atc/models/__init__.py
- som_atc/models/giscedata_atc.py
- som_atc/models/giscedata_switching_helpers.py
Reforçar el camp process_step per tal d'evitar falsos positius
https://secure.helpscout.net/conversation/2377695902/15589493?folderId=3063374
El camp process_step no s'actualitzava correctament
El camp process_step s'actualitza
som_atc
> Codi per reforçar l'update del camp stored process_step

- som_polissa/security/ir.model.access.csv
- som_polissa/som_polissa_webforms_helpers.py
Depends: https://github.com/gisce/erp/pull/17265
Que quan es canviï un compte bancari des de la Oficina Virtual, no només es canviï del Contracte (per a les properes factures) sinó que també es canviï de les factures pendent de pagament.
https://trello.com/c/UEFpUD3U/154-millora-canvi-n-de-compte-ov
Només canviava l'IBAN a la fitxa del Contracte
Canvia l'IBAN també a les factures que s'han emès però encara no s'han pagat (inclús les que estan en una remesa no enviada al banc).
> Actualitzar IBAN de les factures no pagades

- .github/workflows/integration_config.yml
- giscedata_facturacio_iva_10_som/__terp__.py
- giscedata_facturacio_iva_10_som/demo/giscedata_facturacio_iva_10_demo.xml
- scripts/update_gisce_forks.sh
- som_informe/requirements.txt
Crear una línia de factura no és possible si no es defineix abans la variable de `res.config` amb nom `charge_iva_10_percent_when_available`. Per defecte aquesta està a `-1` i es va afegir una validació en [aquest commit](https://github.com/gisce/erp/commit/f398d2924da8edc103cb6e14ed7503ac49889bd1) d'aquesta PR https://github.com/gisce/erp/pull/14716.
Ara hi ha un fitxer demo que defineix el valor a `1`.
> Nou mòdul per sobrescriure iva 10 en destral

- som_facturacio_flux_solar/wizard/wizard_afegir_contracte_bateria_virtual.py
Modificar métode genèric per a crear origens de Flux Solar
Per Slack
Requereix https://github.com/gisce/erp/pull/18632
> Afegeix métode custom per a crear origens de Flux Solar

- som_facturacio_comer/giscedata_polissa.py
Millorar obtenció de factures per a calcular descomptes Flux solar per nou camp a l'origen data_inici_descomptes
Slack
> Millora obtenció de factures per a calcular descomptes Flux solar per nou camp a l'origen

- som_polissa_condicions_generals/report_backend_mailcanvipreus.py
Afegir cost estimat indexada en el backend del correu
https://trello.com/c/X63v2MHM/259-add-correu-canvi-de-tarifes-01-01-2024
> Add indexada estimation cost

- som_polissa_condicions_generals/report_backend_mailcanvipreus.py
Fix mode facturacio indexada
https://trello.com/c/X63v2MHM/259-add-correu-canvi-de-tarifes-01-01-2024
> 🐛 (backend preus): Fix mode facturacio indexada

- som_facturacio_comer/giscedata_polissa.py
Fix typo a data_inici per a càlcul de descomptes de flux solar
[232604] 7873 Error al Comprovar nous descomptes Flux Solar Àmbit Comercialització
Hi havia una typo
Ja no hi ha una typo
> Fix typo a data_inici per a càlcul de descomptes de flux solar

- som_polissa_condicions_generals/report_backend_mailcanvipreus.py
Backend correu canvi preus: Afegir bo_social, autoconsum i info de modcon
https://trello.com/c/X63v2MHM/259-add-correu-canvi-de-tarifes-01-01-2024
> Backend correu canvi preus: Afegir bo_social, autoconsum i info de modcon

- som_polissa_condicions_generals/report/condicions_particulars.mako
Reverts Som-Energia/openerp_som_addons#317
> Revert "Update ccpp"

- .github/labeler.yml
- .github/workflows/labeler.yml
Afegir tags de mòdul automàticament
> Afegir tags de mòdul automàticament

- som_crawlers/data/som_crawlers_config_data.xml
- som_crawlers/data/som_crawlers_step_data.xml
- som_crawlers/data/som_crawlers_task_data.xml
Afegir el crawler de la dstribuïdora escuer
https://trello.com/c/y6KlYv7U/268-afegir-crawler-agr-distribuidora-de-escuer
No existia
Existeix
> new escuer crawler

- som_crawlers/models/som_crawlers_task_step.py
https://secure.helpscout.net/conversation/2441772632/16129197?folderId=3063374
> Fix crawler result error when import fails

- som_facturacio_comer/wizard/wizard_afegir_contracte_bateria_virtual.py
Afegir conversió a int despres de un obj.read per resoldre un error trobat.
SAC 232745
> Afegir una conversió a int per resoldre un error.

- som_leads_polissa/giscedata_crm_lead.py
- som_leads_polissa/giscedata_crm_lead_view.xml
- som_polissa_condicions_generals/report/condicions_particulars.mako
Utilitzar preus de potencies de tarifes existents en els leads
https://trello.com/c/S3LrZckq/263-continuaci%C3%B3-targeta-fer-servir-el-crm-ofertes-oportunitats-per-generar-els-contractes-que-fem-eie
No es podia
Es pot
> ✨ (leads) Utilitzar preus de potencies de tarifes existents

- som_indexada/__terp__.py
- som_indexada/security/ir.model.access.csv
- som_indexada/wizard/__init__.py
- som_indexada/wizard/wizard_change_to_indexada.py
- som_indexada/wizard/wizard_change_to_indexada_multi.py
- som_indexada/wizard/wizard_change_to_indexada_multi.xml
Agilitzar el canvi massiu a tarifa idnexada
https://trello.com/c/xy83s2un/280-canvis-a-tarifa-indexada-empresa-massius
Només es podia fer d'una pòlissa en una pòlissa
Es pot fer en varies
> New wizard change to indexada

- som_facturacio_comer/giscedata_facturacio_report_v2.py
Realitzar el càlcul del valor de impSA pel codi QR
https://trello.com/c/J2wsujWp/273-bateria-revisar-qr-amb-flux-aplicat
> Modificar el càlcul del valor de impSA pel codi QR

- som_polissa_condicions_generals/report/condicions_particulars.mako
Arreglar les ccpp
- end_date_mecanisme_ajust_gas
- iva_reduit_get_tariff_prices_end_date
- Canviar posició fiscal fp_iva_reduit a IVA 10% i IESE 2.5%
> update 2024 taxes ccpp

- som_polissa_condicions_generals/report/condicions_particulars.mako
CCPP: Arreglar obtenir posició fiscal quan pot > 10
https://trello.com/c/smlbJcyv/287-adaptar-ccpp-als-nous-impostos
> CCPP: Arreglar obtenir posició fiscal quan pot > 10

- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
- giscedata_facturacio_comer_som/i18n/es_ES.po
- giscedata_facturacio_comer_som/i18n/giscedata_facturacio_comer_som.pot
- giscedata_facturacio_comer_som/report/components/invoice_details_td_other_concepts/invoice_details_td_other_concepts.mako
Que la factura surti be
https://secure.helpscout.net/conversation/2470607922/16260397?folderId=3063374
no es mostra be
es mostra be
giscedata_facturacio_comer_som
> Afegir el 2.5 i 3.8 % de iese a la factura en pdf

- scripts/reset_sequences_january_1th.py
Afegir seqüences a reiniciar l'1 de gener
https://secure.helpscout.net/conversation/2468164664/16258027?folderId=3063379
Es reiniciaven només factures d'energia
S'afegeixen les següents:
- Payment order
- Receivable payment order
- Account Invoice Out
- Account Invoice In
- Account Refund Out
- Account Refund In
> Afegir seqüences a reiniciar l'1 de gener

- som_indexada/wizard/wizard_change_to_indexada_multi.py
Areglar wizard canvi massiu a indexada
https://trello.com/c/xy83s2un/280-canvis-a-tarifa-indexada-empresa-massius / Xat
Es mostraven ids
Es mostra el número de pòlissa
> name instead of id

- som_facturacio_comer/wizard/wizard_informe_factures_dades_desagregades.py
Afegir el flux soar al informe de dades desagregades
https://trello.com/c/8i9lTEHa/281-afegir-el-flux-solar-a-leina-generar-informe-dades-desagregades-30-i-6x
No hi apareixia
Hi apareix
> add flux to informe

- som_polissa/giscedata_polissa_view.xml
- som_polissa/migrations/5.0.23.12.0/post-0001_afegir_columnes_autoconsum_i_provincies_cups.py
Noves columnes a les polisses
Noves columnes a les polisses
> Noves columnes a les polisses

- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
- giscedata_facturacio_comer_som/i18n/es_ES.po
- giscedata_facturacio_comer_som/i18n/giscedata_facturacio_comer_som.pot
- giscedata_facturacio_comer_som/report/components/invoice_details_td_other_concepts/invoice_details_td_other_concepts.mako
Canviar Frase IVA
https://trello.com/c/ZAbc4zYo/290-get-afegir-frase-de-liva-redu%C3%AFt-al-10-al-pdf-de-les-factures
Sortia Frase Antiga
Surt frase nova
> Add iva 10 phrase to pdf

- www_som/migrations/5.0.23.12.0/pre-0001_afegir_permisos_helper_indexada.py
No hi havia migració i l'hem afegit per modificar els permisos afegit a la PR 
https://github.com/Som-Energia/openerp_som_addons/pull/511
> 🧹 Afegir migració pels permisos del helper

- README.md
- docs/tech.md
Afegir fitxer de tecnologies de [StackShare.io](https://stackshare.io/stack-report) i completar el README.
Cap
NA
NA
> Add tech.md file and complete de README

- som_polissa/giscedata_polissa_view.xml
Arreglar bug en l'herència de les vistes que es modificaven a la PR https://github.com/Som-Energia/openerp_som_addons/pull/525
> 🐛 Arreglar vista agafant inherit

- som_polissa/giscedata_polissa.py
Solucionar la incidència
https://secure.helpscout.net/conversation/2503634487/16446296
Error en obrir certes pòlisses
Normal
> Solucionar caràcter erroni

- som_account_invoice_pending/update_pending_states.py
Arreglar els contractes de baixa i annex 3
https://secure.helpscout.net/conversation/2518402754/16526995?folderId=3063374
Es passaven a traspàs advocats i immediatament després s'enviava l'annex
Només es fa el traspàs a advocats
> Fix annex3 cancelled contracts

- .github/workflows/integration_config.yml
- .github/workflows/reusable_workflow.yml
Arreglar tests som_extend_facturacio_facturae
S'instal·lava per requirements.txt del mòdul.
S'instal·la abans d'arrancar l'ERP tal i com van fer a https://github.com/gisce/erp/pull/15397
> Arreglar tests som_extend_facturacio_facturae

- som_account_invoice_pending/tests/update_pending_states_tests.py
- som_account_invoice_pending/update_pending_states.py
Arreglar tests **som_account_invoice_pending**
https://trello.com/c/GhMe9pHe
No passaven testos
Passen testos
> Fix tests som_account_invoice_pending

- som_facturacio_calculada/giscedata_polissa.py
- som_facturacio_calculada/tests/test_polissa_lectures_calculades.py
Arreglar tests de som_facturacio_calculada
Fallaven els testos
Passen els testos
> Arreglar tests de som_facturacio_calculada

- som_inversions/tests/test_wizard.py
Arreglar tests **som_inversions**
https://trello.com/c/GhMe9pHe
No passaven testos
Passen testos
> Fix test som_inversions

- .github/labeler.yml
- .github/workflows/integration_config.yml
- .github/workflows/reusable_workflow.yml
Fix somutils
Peten els testos del GithubActions
Agafem una version específica del paquet somutils https://github.com/Som-Energia/somenergia-utils/pull/2
> Fix somutils

- som_facturacio_comer/__terp__.py
- som_facturacio_comer/data/res_config_data.xml
- som_facturacio_comer/giscedata_facturacio_report_v2.py
Obtenir una dada que es farà servir al cos del mail.
https://trello.com/c/jhfutspW
No teniem aquesta dada i no es podia aplicar la lògica requerida.
Obtenim la dada i apliquem la lògica requerida.
> backend 'te_iva21' property

- .github/workflows/reusable_workflow.yml
Make workflow reusable for other SomEnergia repositories with openerp modules
> Make workflow reusable for other SomEnergia repositories with openerp modules

- som_indexada/wizard/wizard_change_to_indexada_multi.xml
Recuperar el wizard canvi a indexada
Ho hem vist avui
Només es veia el wizard canvi a indexada massivament
Es poden utilitzar els dos
> Fix wizard change to indexada multi view

- .github/workflows/integration_config.yml
- .github/workflows/reusable_workflow.yml
Treure referències al mòdul spawn_oop
S'instal·lava el mòdul arxivat, i obligava a instal·lar una versio antiga de psutil que feia que no funcionés la parada del servidor i sortissin els testos en vermell.
Es manté versió nova de psutil
> Treure referències al mòdul spawn_oop

- .github/workflows/integration_config.yml
- .github/workflows/reusable_workflow.yml
Afegim variables al workflow de GA
Projecte Algemesí
No hi eren
Variables afegides
- export OPENERP_SII_TEST_MODE=1
- export OPENERP_SECRET="verysecret"
- export OPENERP_IGNORE_PUBSUB=1
> Afegim variables al workflow de GA

- som_polissa/tests/som_polissa_tests.py
Arreglar testos de som_polissa
[Projecte Algemesí](https://trello.com/c/GhMe9pHe/318-projecte-algemes%C3%AD-arreglar-tots-els-tests)
No passava un test en que la pòlissa ja tenia una categoria
Ara passen els tests
> Arreglar testos de som_polissa

- base_extended_som/demo/som_data.xml
- scripts/README.md
- www_som/tests/tests_factura.py
> Fix www_som tests

- som_extend_facturacio_comer/utils.py
- som_polissa_condicions_generals/report/condicions_particulars.mako
- som_polissa_condicions_generals/report_backend_mailcanvipreus.py
- som_polissa_condicions_generals_m101/report/condicions_particulars_m101.mako
> Actualitzar backend canvi de preus per propera renovació

- som_polissa/exceptions/exceptions.py
- www_som/__terp__.py
- www_som/som_indexada_webforms_helpers.py
- www_som/tests/indexed_prices_demo.xml
- www_som/tests/tests_indexada_helpers.py
Mostrar preus diaris de la indexada a la web de Somenergia
https://trello.com/c/D5nCJmw2/5881-crida-de-lapi-que-retorni-la-taula-dels-preus-24h
No existia
S'han creat dues funcions:
- get_indexed_prices: per obtenir preus diaris de la indexeda 
- get_compensation_prices: per obtenir preus de compensació
> New indexed prices

- account_invoice_som/tests/account_invoice_demo.xml
- destral/mamba.root_path.xml
- destral/som_facturacio_comer.xml
Arreglar testos de account_invoice_som
> Arreglar testos de account_invoice_som

- som_webforms_helpers/tests/tarifes_demo.xml
- som_webforms_helpers/tests/test_tarifes.py
> Fix som webforms helpers tests

- som_polissa_condicions_generals/report/condicions_particulars.mako
Fer que a les CCPP surti IVA 21% si l'últim més el preu ha set inverior a 45€/MWh
https://secure.helpscout.net/conversation/2537671147/16743099?folderId=7850674
Es mostrava la llegenda del 10% quan tocava el 21%
Es mostra la llegenda del 21%
> Fer que a les CCPP surti IVA 21% si l'últim més el preu ha set inverior a 45€/MWh

- som_facturacio_comer/__terp__.py
- som_facturacio_comer/migrations/5.0.23.6.0/pre-0002_add_permissions_to_bakend_invoice_email.py
- som_facturacio_comer/security/ir.model.access.csv
- som_facturacio_comer/tests/tests_wizard_open_factures_send_mail.py
Arreglar els tests de som facturacio comer
TREMENDA BARRACUDA
> Fix tests som facturacio Comer

- scripts/download_esios_files.py
Descarregar el fitxer A2_liquicomun i sinó hi és, el A1_liquicomun.
https://trello.com/c/Siy26QAW/5782-c1b-c%C3%A0lcul-a-erp-del-millor-valor-de-preu-properes-24h
https://secure.helpscout.net/conversation/2544353684/16776951?folderId=7850674
Trovaba un fitxer tipus "liquicomun" erroni que no es baixava.
Només intenta baixar un fitxer tipus A2_liquicomun o A1_liquicomun.
> Mod script esios

- som_leads_polissa/__terp__.py
- som_leads_polissa/giscedata_crm_lead.py
- som_polissa/giscedata_polissa.py
- som_polissa/migrations/5.0.24.5.0/post-0002-create_res_config_canarias.py
- som_polissa/som_polissa_data.xml
Millorar el comportament dels leads
https://trello.com/c/yIDv0Nnn/298-millores-creaci%C3%B3-de-p%C3%B2lissa-a-partir-dels-leads-del-crm
> Multiple som_leads improvements

- som_polissa/__terp__.py
- som_polissa/migrations/5.0.24.5.0/post-0003_add_wizard_add_cut_off_to_polissa_from_csv.py
- som_polissa/security/ir.model.access.csv
- som_polissa/wizard/__init__.py
- som_polissa/wizard/wizard_add_cut_off_to_polissa_from_csv.py
- som_polissa/wizard/wizard_add_cut_off_to_polissa_from_csv_view.xml
Afegir un wizard per a marcar subministraments com a no tallables
https://trello.com/c/qJK2TVtP/330-marcar-com-a-subministrament-no-tallable-a-partir-de-csv
No existia el wizard
Existeix el wizard
> Wizard no cut off to polisses

- .github/workflows/reusable_workflow.yml
Add pyversion to GA reusable ERP
> Add pyversion to GA reusable ERP

- .github/workflows/schedule_tests_powersms_py3.yml
- account_account_som/__init__.py
- account_account_som/wizard/__init__.py
> Fix account account som py3

- som_gurb/__terp__.py
- som_gurb/giscedata_switching.py
- som_gurb/tests/__init__.py
- som_gurb/tests/tests_gurb_switching.py
- Corregir uns casos que no es van contemplar a la PR #526 
Quan la pòlissa relacionada té la categoria GURB:
- No es tancaven els casos M102 d'auto de rebuig
- No es notificava cap M102
Quan la pòlissa relacionada té la categoria GURB:
- Es tanquen els casos M102 d'auto de rebuig
- No es notifiquen els M102 d'auto
> Fix GURB custom behaviour of some ATR cases

- som_indexada/wizard/wizard_change_to_indexada.py
Millorar la detecció dels contractes de canàries al canviar de tarifa
Es feia a partir de la posició fiscal de la pòlissa
Es fa a partir del subsistema del CUPS
> Detect canarias with subsistema

- account_invoice_som/tests/tests_wizard_payment_order_add_invoices.py
Arreglar tests del mòdul `account_invoice_som` .
- Fallava GitHub Actions
- No falla GitHub Actions
> Fix account_invoice_som tests

- som_polissa/tests/som_polissa_demo.xml
- som_switching/demo/som_switching_demo_data.xml
- som_switching/giscedata_switching_helpers.py
- som_switching/security/ir.model.access.csv
- som_switching/tests/tests_activaciones.py
- som_switching/tests/tests_activacions_m1.py
- som_switching/tests/tests_wizard_reexport_log.py
Arreglar testos
https://trello.com/c/GhMe9pHe
no passaven testos
passen testos
> Fix tests som_switching

- som_infoenergia/migrations/5.0.2.108/post-0002_add_template_essencials.py
- som_infoenergia/som_infoenergia_data.xml
Nova plantilla subministraments essencials
https://trello.com/c/gPnGMQOs/329-creaci%C3%B3-nova-plantilla-i-lot-enviament-massiu-confirmaci%C3%B3-essencials
> Nova plantilla subministraments essencials

- som_leads_polissa/wizard/wizard_crm_lead_create_entities_view.xml
Arreglar els inherits del canvis introduits a la PR https://github.com/gisce/erp/pull/16933
Ens ho hem trobat fent targetes de leads
amb 23.9 peta
no peta
> Fix wizard inherit view

- som_stash/__init__.py
- som_stash/__terp__.py
- som_stash/data/res_config_data.xml
- som_stash/models/__init__.py
- som_stash/models/som_stash.py
- som_stash/models/som_stash_setting.py
- som_stash/security/ir.model.access.csv
- som_stash/security/som_stash.xml
- som_stash/sql/query_partner_pol_expired.sql
- som_stash/sql/query_soci_expired.sql
- som_stash/tests/__init__.py
- som_stash/tests/test_som_stash.py
- som_stash/views/som_stash_setting_view.xml
- som_stash/views/som_stash_view.xml
- som_stash/wizard/__init__.py
- som_stash/wizard/wizard_som_stash_this.py
- som_stash/wizard/wizard_som_stash_this_view.xml
- som_stash/wizard/wizard_som_stasher.py
- som_stash/wizard/wizard_som_stasher_view.xml
- som_stash/wizard/wizard_som_unstasher.py
- som_stash/wizard/wizard_som_unstasher_view.xml
Crear un nou mòdul que permeti gestionar l'emmagatzematge temporal de les dades preparades per ser eliminades.
https://trello.com/c/HGNdpf1t/317-esborrat-de-correu-electr%C3%B2nic-de-partners-antics
No podem gestionar-ho
Ho podem gestionar
som_stash
> Nou mòdul som_stash 

- som_polissa/giscedata_polissa_view.xml
- som_polissa/migrations/5.0.24.5.1/post-0001_modify_polissa_tabs_bis.py
Recolocar els camps de Gers endarrerida i Gest massiva de manera que sigui mes fàcil consultar-los
https://trello.com/c/IEu2JeFE/348-gex-modificar-pestanya-observacions-per-ordenar-millor
Camps massa amagats
Camps mes visibles
som_polissa
> moure els camps gest massiva i gest endarrerida

- som_estalvi/i18n/es_ES.po
- som_estalvi/i18n/som_estalvi.pot
- som_estalvi/report/components/analisi_potencies.mako
- som_estalvi/report/components/footer.mako
- som_estalvi/report/components/resum_facturacio_anual.mako
- som_estalvi/report/som_estalvi.css
- Corregir el _layout_ de la taula de potències quan hi ha molts dígits.
- Correccions en el text i les traduccions.
https://trello.com/c/fpIP3WS4/297-disseny-components-informe-dassessorament-per-contractes-3x-i-6x-%C3%A0lies-infoenergia
> Small fixes in som_estalvi

- som_poweremail_common_templates/commontemplates_data.xml
Definir el disseny base per correus transaccionals
No existia una plantilla base
Ara hi ha una plantilla base
-
> Disseny base per correus transaccionals

- som_poweremail_common_templates/commontemplates_data.xml
- som_poweremail_common_templates/migrations/5.0.23.9/pre-0001_add_common_rejection_templates.py
- som_poweremail_common_templates/migrations/5.0.23.9/pre-0001_add_fue_reminder.py
Crear xml ids per les plantilles de desistiment
https://trello.com/c/o4IkwcWQ/347-actualitzaci%C3%B3-enlla%C3%A7-a-plantilla-de-desistiment-modificacions-erp
No existien
Existeixen
> new modi templates

- som_account_invoice_pending/migrations/5.0.23.9.0/post-0003_migrate_attachments_to_consultes.py
Migrar els adjunts de les consultes de pobresa
https://trello.com/c/V9VNHfhu/282-introduir-nous-camps-de-cerca-a-all-cases
Estaven en els crm.case
També hi són als som.consulta.pobresa
> New attachments script

- som_account_invoice_pending/models/giscedata_polissa.py
Arreglar la ff de consulta pobresa pendent
Xat + https://somenergia.openproject.com/projects/som-energia/work_packages/131/activity
Si hi havia una consulta fora de dates retornava True
Si hi ha una consulta dins dates retorna False
> Fix ff consulta pobresa pendent

- som_account_invoice_pending/migrations/5.0.23.9.0/post-0004_migrate_attachments_mongo_id.py
- som_account_invoice_pending/models/som_consulta_pobresa.py
- som_account_invoice_pending/models/update_pending_states.py
Corregir enllaç dels adjunts amb Mongo
> Corregir enllaç dels adjunts amb Mongo

- som_autoreclama/__terp__.py
- som_autoreclama/giscedata_polissa.py
- som_autoreclama/migrations/5.0.24.5.0/post-0001_reload_atc_states_and_new_conf_parameter.py
- som_autoreclama/res_config_data.xml
- som_autoreclama/som_autoreclama_state.py
- som_autoreclama/som_autoreclama_state_condition.py
- som_autoreclama/som_autoreclama_state_data.xml
- som_autoreclama/som_autoreclama_state_updater.py
- som_autoreclama/tests/test_som_autoreclama_states.py
Crear un nou estat 'Revisar' i configurar regles i condicions per funcionament esperat.
https://trello.com/c/NpxaRE6J
https://somenergia.openproject.com/projects/som-energia/work_packages/99/activity
No existia aquest estat
Contemplem aquest nou estat amb la lògica requerida.
> Limitació auto-reclama i nou estat

- som_facturacio_flux_solar/giscedata_bateria_virtual_percentatges_acumulacio_data.xml
- som_facturacio_flux_solar/migrations/5.0.23.9.0/post-0002_var_config_percentatge_acumulacio.py
Fix  id variable de configuració 
account_link_join_43 -> percentatge_acumulacio
> Fix var config percentatges

- powersms/requirements.txt
- powersms/tests/__init__.py
- powersms/wizard/__init__.py
- powersms/wizard/wizard_send_sms.py
Fer powersms compatible amb python 3
> Fer powersms compatible amb python 3

- som_informe/report/components/ProcesATR/ProcesATR.py
Solucionar un error al generar som informes amb D1 en pas 02
https://hs.somenergia.coop/conversation/2109?folder_id=87
Es penja
Genera l'informe
> Fix del error al generar som informes amb D1 pas 02

- som_gurb/__init__.py
- som_gurb/__terp__.py
- som_gurb/report/__init__.py
- som_gurb/security/ir.model.access.csv
Arreglar inits del gurb
Bé, és lamentable
No funcionava
Funciona!
> Arreglar inits del Gurb

- som_polissa_condicions_generals/report_backend_mailcanvipreus.py
Funcionalitats específiques per l'enviament del canvi de tarifes indexades.
https://somenergia.openproject.com/wp/246
https://somenergia.openproject.com/projects/indexada/work_packages/246
Actualitzar xml
> (canvi-preus): Segona adaptació per Juliol

- powersms/wizard/wizard_send_sms.py
> Fix py3 unicode error

- som_polissa_condicions_generals/report_backend_mailcanvipreus.py
> ✨ (canviPreus): Eie valiadtion

- som_switching/security/ir.model.access.csv
- som_switching/wizard/giscedata_switching_mod_con_wizard.py
https://hs.somenergia.coop/conversation/3743?folder_id=87
https://hs.somenergia.coop/conversation/3743?folder_id=87
https://hs.somenergia.coop/conversation/3743?folder_id=87
https://hs.somenergia.coop/conversation/3743?folder_id=87
> comment empowering fields

- som_gurb/models/som_gurb_cups.py
- som_gurb/wizard/wizard_create_gurb_cups_signature.py
> ✨ (gurb) More gurb things

- som_indexada/som_polissa_k_change.py
- som_polissa_condicions_generals/report_backend_mailcanvipreus.py
Funcionalitats específiques per l'enviament del canvi de tarifes indexades.
https://somenergia.openproject.com/wp/246
https://somenergia.openproject.com/projects/indexada/work_packages/246
Actualitzar xml
> (canvi-preus): Adaptació per Juliol 4

- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
Modificar el gràfic del pdf de factura per que sempre es faci espai per 12 grups de barres, millorant-ne la imatge.
iniciativa pròpia
Barres grosses i apaisades
Barres mes estilitzades
> Modificar el gràfic del pdf de factura per que sempre es faci espai per 12 grups de barres

- som_crawlers/data/som_crawlers_step_data.xml
- som_crawlers/data/som_crawlers_task_data.xml
- som_crawlers/migrations/5.0.23.9.0/post-0001_add_hc_crawlers.py
- som_crawlers/migrations/5.0.23.9.0/pre-0001_add_hc_crawlers.py
- som_crawlers/scripts/script_run_crawler.py
✨ Afegim crawlers HC concrets per procés
https://somenergia.openproject.com/projects/som-energia/work_packages/267/activity
Hi havia un de sol
Ha canviat el portal i cal crear-ne de diferents per a cada procés
> ✨ Afegim crawlers HC concrets per procés

- som_informe/report/components/TableReadings/TableReadings.py
Arreglar l'ordre de les lectures
https://hs.somenergia.coop/conversation/11008?folder_id=87
No hi havia ordre
Hi ha ordre
> Fix readings order

- som_atc/models/giscedata_switching_helpers.py
Fa una mica de magia (per evitar refactor a gisce) i arregla el problema de que el autoconsum no estava creat al intentar enviar el mail
> Fix D1 autoclose (send mail when autoconsum is created)

- som_polissa_condicions_generals/models/report_backend_ccpp.py
Arreglar les condicions particulars amb iva 10
https://hs.somenergia.coop/conversation/27981?folder_id=87
sempre 21
sempre el que toca
> Fix iva 10 date in ccpp

- som_polissa_condicions_generals/models/report_backend_ccpp.py
- som_polissa_condicions_generals/tests/tests_report_backend_ccpp.py
Arreglar la posició fiscal que s'aplica a la K
https://hs.somenergia.coop/conversation/27981?folder_id=87
No es calculava
Es calcula correctament
> Fix k taxes

- scripts/download_esios_files.py
Copiar ESIOS zip a servidor FTP
https://trello.com/c/Siy26QAW/5782-c1b-c%C3%A0lcul-a-erp-del-millor-valor-de-preu-properes-24h
No es copiava, només era accessible des del servidor
Es copia a un servidor FTP per a consulta pels usuaris
> Copiar ESIOS zip a servidor FTP

- som_webforms_helpers/giscedata_polissa_tarifa.py
Show prices with correct IVA
https://hs.somenergia.coop/conversation/27981?folder_id=87
Parameter check_date with format datetime in function has_to_charge_10_percent_requeriments_oficials.
Adapt parameter check_date to string when call has_to_charge_10_percent_requeriments_oficials function.
> 🐛 date format to string when asking for 10% IVA

- som_account_invoice_pending/data/som_account_invoice_pending_data.xml
- som_account_invoice_pending/migrations/5.0.23.9.0/post-0005_add_consulta_pobresa_states.py
✨ Afegir estats pendents de factures tipus calaix de sastre 
https://somenergia.openproject.com/wp/268
No existien
Existeixen
> ✨ Afegir estats pendents de factures tipus calaix de sastre

- som_informe/report/components/TableInvoices/TableInvoices.py
- som_informe/report/components/TableReadings/TableReadings.py
Canviar l'ordre de les lectures
https://hs.somenergia.coop/conversation/11008?folder_id=87
D'antic a recent 
De recent a antic
> Sorting in reverse

- som_informe/report/components/TableInvoices/TableInvoices.py
- som_informe/report/components/TableReadings/TableReadings.py
Ordenar de més recent a més antic
https://hs.somenergia.coop/conversation/11008?folder_id=90
S'ordenava al revés
S'ordena correctament
> revert reverse

- som_polissa_condicions_generals/models/report_backend_ccpp.py
Diria molt que no funcionava
Trobat de casualitat per degut a la incidència https://hs.somenergia.coop/conversation/45503?folder_id=90
Entenc que aquest camp no ha sortit bé
Entenc que ara sí que funcionarà
> 🐛 Error tipogràfic en consulta de valor d'un camp

- som_gurb/models/som_gurb_cups.py
- som_gurb/views/som_gurb_cups_view.xml
- som_gurb/wizard/wizard_create_gurb_cups_signature.py
[#286] [GURB036] Petits retocs GURB Mataró
https://somenergia.openproject.com/work_packages/286
https://somenergia.openproject.com/wp/286
OP#286
> Petites millores en el gurb

- som_account_invoice_pending/__terp__.py
- som_account_invoice_pending/data/som_account_invoice_pending_data.xml
- som_account_invoice_pending/migrations/5.0.23.9.0/post-0006_add_template_impagament_fraccionament.py
Afegir plantilla impagament fraccionament
https://somenergia.openproject.com/wp/304
No existia
Existeix
> ✨ Afegir plantilla impagament fraccionament

- som_crawlers/migrations/5.0.23.9.0/post-0002_add_lazy_one2many_field.py
Fix migration script
NS/NC
Petava l'script de migració
Ja no peta
> Fix migration script

- som_gurb/demo/som_gurb_demo.xml
- som_gurb/i18n/es_ES.po
- som_gurb/i18n/som_gurb.pot
- som_gurb/models/som_gurb_cups.py
- som_gurb/tests/tests_gurb_base.py
- som_gurb/tests/tests_gurb_cups.py
- som_gurb/tests/tests_gurb_services.py
- som_gurb/wizard/wizard_create_gurb_cups_signature.py
- som_polissa_condicions_generals/__terp__.py
> 🐛 Intent fallit de solucionar testos de GURB I

- som_gurb/models/__init__.py
> Afegir utf8 a som_gurb

- som_informe/report/components/TableInvoices/TableInvoices.py
- som_informe/report/components/TableReadings/TableReadings.py
Milorar ordenació
Xat
més antic a més recent
més recent a més antic i alfabètic per tipus
> sort by type

- som_gurb/data/som_gurb_data.xml
- som_gurb/views/som_gurb_cups_view.xml
[286] [GURB036] Petits retocs GURB Mataró
https://somenergia.openproject.com/work_packages/286
> 🎨 Petits retocs GURB Mataró

- som_facturacio_comer/giscedata_polissa.py
Partir facturació per modificació de fórmula indexada
No partia la facturació i feia una única factura
Partir facturació per modificació de fórmula indexada
> Partir facturació per modificació de fórmula indexada

- som_crawlers/data/som_crawlers_config_data.xml
- som_crawlers/data/som_crawlers_step_data.xml
- som_crawlers/data/som_crawlers_task_data.xml
Afegir crawler UDESA
https://somenergia.openproject.com/wp/290
no existia
existeix
> new udesa crawler

- som_indexada/migrations/5.0.2.108/post-0002_wizard_massive_k_change_modcon_update.py
- som_indexada/wizard/wizard_massive_k_change.py
- som_indexada/wizard/wizard_massive_k_change.xml
Permetre modificar la modcon actual
Xat
No es podia
> allow current modcon

- som_gurb/__terp__.py
- som_gurb/models/report_backend_som_gurb_documents.py
- som_gurb/models/som_gurb.py
- som_gurb/models/som_gurb_cups.py
- som_gurb/report/__init__.py
- som_gurb/report/acord_repartiment.mako
- som_gurb/report/representant.py
- som_gurb/report/som_gurb_reports.xml
- som_gurb/security/ir.model.access.csv
- som_gurb/views/som_gurb_view.xml
- som_gurb/wizard/__init__.py
- som_gurb/wizard/wizard_create_coef_file.py
- som_gurb/wizard/wizard_create_coef_file_view.xml
- som_gurb/wizard/wizard_create_distribution_agreement_file.py
- som_gurb/wizard/wizard_create_distribution_agreement_file_view.xml
Crear reports i fitxers per adjuntar en els M1
https://somenergia.openproject.com/work_packages/84
Abans es creaven manualment
Ara es poden generar des de l'ERP
> ✨ GURB: Generar l'acord de repartiment, fitxer de coeficients i documents de representació

- som_gurb/report/acord_repartiment.mako
Millorar CSS dels reports de GURB
Converses amb grup impulsor
Es veia bastant pitjor
La taula s'enten i va millor
RES
> 💄Millorar CSS dels reports de GURB

- som_polissa/exceptions/exceptions.py
- som_polissa/giscedata_polissa.py
- som_polissa/tests/test_exceptions.py
Afegir excepció per pòlisses en estat modcontractual
xat
no existia
Existeix
> new modcontractual exception

- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
Millorar rendiment de la funció get_readings_data_fill, fent servir OOQUERY en el punt concret que hem vist fent profiling que trigava molt s'ha millorat uns 100 cops la velocitat.
https://somenergia.openproject.com/wp/397
> Optimize get_readings_data_fill with ooquery

- som_polissa_condicions_generals/i18n/es_ES.po
- som_polissa_condicions_generals/i18n/som_polissa_condicions_generals.pot
- som_polissa_condicions_generals/migrations/5.0.23.9.0/post-0001_load_translations.py
- som_polissa_condicions_generals/report/components/prices_info.mako
🌐 Fix traslation
https://freescout.somenergia.coop/conversation/45647?folder_id=283
> Arreglar traducció del contracte

- som_polissa_condicions_generals/models/report_backend_ccpp.py
https://freescout.somenergia.coop/conversation/1652226?folder_id=87
https://freescout.somenergia.coop/conversation/1652226?folder_id=87
https://freescout.somenergia.coop/conversation/1652226?folder_id=87
https://freescout.somenergia.coop/conversation/1652226?folder_id=87
> fix upcoming ccpp

- som_polissa_condicions_generals/models/report_backend_ccpp.py
Corregir els valors dels preus futurs en cas de tarifa vinent
https://somenergia.openproject.com/wp/327
Mostrava els preus actuals als 2 blocs de preus
Ja mostra els preus de tarifa vinent
> 🐛 fix upcoming prices

- som_facturacio_comer/giscedata_facturacio_correu_backend.py
- som_facturacio_comer/tests/tests_facturacio_warnings.py
Afegeix un boolea "is_provincia" a les dades del CUPS per tal de que desde la plantilla del mail es pugui mostrar una info extra
https://somenergia.openproject.com/wp/343
> Add is_peninsula for indexada prices link

- som_polissa_condicions_generals/report_backend_mailcanvipreus.py
Actualitzar el backend pel canvi de preus de novembre 2024
https://somenergia.openproject.com/wp/327
> Update price change backend to november 2024

- som_polissa_condicions_generals/models/report_backend_ccpp.py
Arreglar les ccpp dels contractes en esborrany
https://freescout.somenergia.coop/conversation/6323192?folder_id=87
No es mostraven els preus nous i vells
Es mostren els preus nous i vells
> fix ccpp esborrany

- som_indexada/wizard/wizard_change_to_indexada.py
- som_polissa/exceptions/exceptions.py
Mostrar si hi ha error quan es passa a indexada amb el wizard, ara tant el normal com el massiu diuen que ha anat bé tot i que falli, amagant possibles errors.
https://freescout.somenergia.coop/conversation/5622789?folder_id=90
> Fix wizards move to indexada to show errors

- scripts/cron_switchingreport.sh
Actualitzar correu referent gc
https://freescout.somenergia.coop/conversation/7277459?folder_id=87
> update gc referent

- som_leads_polissa/giscedata_crm_lead.py
- som_polissa_condicions_generals/models/report_backend_ccpp.py
Arreglar l'idioma de les condicions particulars a partir de leads
https://freescout.somenergia.coop/conversation/7052712?folder_id=87
S'imprimia en català
S'imprimeix en l'idioma corresponent
> fix ccpp lead lang

- giscedata_facturacio_comer_som/report/components/invoice_details_td/invoice_details_td.css
- giscedata_facturacio_comer_som/report/components/invoice_details_td/invoice_details_td.mako
- giscedata_facturacio_comer_som/report/components/invoice_details_td_flux_solar/invoice_details_td_flux_solar.mako
- giscedata_facturacio_comer_som/report/components/invoice_summary_td/invoice_summary_td.mako
Modificació de la posició d'elements informatius del flux solar a la factura en pdf
https://somenergia.openproject.com/projects/som-energia/work_packages/438/activity
Ordre original
Ordre modificat
> Modificació de la posició d'elements informatius del flux solar a la factura en pdf

- som_polissa_condicions_generals/models/report_backend_ccpp.py
Arreglar contractes amb context lang que no són lead
https://freescout.somenergia.coop/conversation/7278242?folder_id=87
S'imprimien amb l'idioma del context
S'imprimeixen amb l'idioma del cotnracte
> fix lang when not lead

- som_auvidi/wizard/wizard_load_servei_gen_records_from_file.py
Millores en wizard de carregar registres AUVIDI
https://somenergia.openproject.com/projects/som-energia/work_packages/466
Comportament genèric
S'adapta el format del fitxer per a disposar de les següents columnes:
DNI;CUPS;FECHA SALIDA (pot estar buit);%
> Millores en wizard de carregar registres AUVIDI

- som_facturacio_flux_solar/giscedata_facturacio.py
Arrodonir mode 0 de Flux Solar amb round en comptes de decimal_round
S'arrodonia amb decimal_round
S'arrodoneix amb round
> Arrodonir mode 0 de Flux Solar amb round en comptes de decimal_round

- som_gurb/models/giscedata_switching.py
- som_gurb/models/som_gurb_cups.py
- som_gurb/tests/tests_gurb_switching.py
- som_gurb/views/som_gurb_cups_view.xml
> Solucionar diferents errors de GURB durant la importació ATR

- som_gurb/models/giscedata_switching.py
- som_gurb/tests/tests_gurb_switching.py
> 🐛 (gurb): Més errors per solucionar

- som_l10n_ES_aeat_mod347/__init__.py
- som_l10n_ES_aeat_mod347/migrations/5.0.25.1.0/post-0001_update_backend_security.py
- som_l10n_ES_aeat_mod347/security/ir.model.access.csv
- som_l10n_ES_aeat_mod347/som_347_email_backend.py
Fer un backend perquè els imports quedin macos
https://somenergia.openproject.com/wp/101
> add 347 email backend

- som_indexada/__init__.py
- som_indexada/giscedata_hourly_energy_price.py
- Adaptar el càlcul del preu de demà amb les noves indexades per 2024
https://somenergia.openproject.com/projects/som-energia/work_packages/240/
> Preu de demà amb Indexades 2024

- som_crawlers/models/som_crawlers_task.py
- som_municipal_taxes/migrations/5.0.24.9.0/post-00002_new_fields_in_view_config.py
- som_municipal_taxes/models/som_municipal_taxes_config.py
- som_municipal_taxes/views/som_municipal_taxes_config_view.xml
Arreglar tipus en fitxer de taxa municipal
https://freescout.somenergia.coop/conversation/7280005?folder_id=87
- El fitxer es generava malament perquè no es passava el tipus
- Es passa el tipus del 1,5% correctament
- S'afegeix el camp llengua i tipus de pagament (trimestral/anual) a la vista
> 🐛 Arreglar tipus en fitxer de taxa municipal

- som_auvidi/giscedata_serveis_generacio.py
- som_auvidi/giscedata_serveis_generacio_data.xml
- som_auvidi/migrations/5.0.25.1.0/post-0001_loads_auvidi_new_categories_again.py
Modificar referències a AUVI amb nomenclatura correcte
https://somenergia.openproject.com/wp/504
Nomenclatura incorrecte
Es referencia com a AuVi allà on no era correcte el nom.
> Modificar referències a AUVI amb nomenclatura correcte

- som_gurb/wizard/wizard_create_coef_file.py
- som_gurb/wizard/wizard_create_coef_file_view.xml
Corregir diferents errors del wizard
https://somenergia.openproject.com/wp/457
No ficava bé el nom i ficava un intro al final que no estava bé
Ara fica bé el nom i no posa l'intro
> Targeta/457 gurb044 correcció errors del txt (targeta 43)

- som_facturacio_flux_solar/giscedata_facturacio.py
Nou fix a flux solar per a intentar controlar les cosetes que te Python amb les operacions aritmètiques amb els floats
[240685] Sac de Gisce
Errors produïts pels decimals i l'arrodoniment dels float que fa Python
S'arrodoneix a 6 decimals i després a 2 per eviat aquests errors (o intentar-ho)
> Nou fix a flux solar per a intentar controlar les cosetes que te Python amb les operacions aritmètiques amb els floats

- .github/workflows/reusable_workflow.yml
Netejar una mica el fitxer perque sigui mes fàcil de mantenir
> Simplify and clean GA reusable workflow

- som_facturacio_comer/__terp__.py
- som_facturacio_comer/tests/tests_wizard_revert_incident_fact_contracte_lot.py
- som_polissa_soci/__terp__.py
- som_polissa_soci/tests/tests_facturacio.py
✅ change module dependency and install in tests due Destral PR [#156](https://github.com/gisce/destral/pull/156)
[RFC](https://rfc.gisce.net/t/atualizacion-requerida-en-destral-para-la-instalacion-de-modulos-en-tests/2246) de GISCE
Instal·lava els mòduls al setup de cada test
Instal·la un sol cop al instal·lar el mòdul per a test
> ✅ change module dependency and install in tests due Destral PR #156

- som_facturacio_flux_solar/giscedata_facturacio.py
Correcció de càlcul d'IESE en factures on després s'eliminarà pel Flux Solar
Incidència [241507]
Es calculava l'IESE normal
No es calcula IESE doncs la factura no te consum i lectures reals. Per tant no aplica IESE
> Correcció de càlcul d'IESE en factures on després s'eliminarà pel Flux Solar

- scripts/download_esios_files.py
Modificar script ESIOS per baixar tots els fitxers i amb dos certificats diferents
https://somenergia.openproject.com/projects/som-energia/work_packages/100/activity
Només baixava liquicomuns de Som Energia
Baixa tots els disponibles de Som Energia i Som Renovables
> Modificar script ESIOS per baixar tots els fitxers i amb dos certificats diferents

- som_factures_paper/wizard/wizard_paper_invoice_som.py
Fer que som_factures_paper emmagatzemi les factures al imprimir-les
https://somenergia.openproject.com/projects/som-energia/work_packages/488/activity
No emmagatzema
Emmagatzema, prèvia instal·lació https://github.com/Som-Energia/openerp_som_addons/pull/752
> Fer que som_factures_paper emmagatzemi les factures al imprimir-les

- somre_giscere_facturacio/giscere_facturacio.py
- somre_giscere_facturacio/tarifes.py
Que no doni error per precommit
Equip
Vermell
Verd
> Auto flake8 sobre mòdul somre_giscere_facturacio que no compleix coding style de som_energia

- som_polissa_soci/migrations/5.0.24.9.0/post-0002_field_baixa_readonly.py
- som_polissa_soci/somenergia_soci_view.xml
> 💄  Make field baixa_soci readonly from partner view

- .github/workflows/pre-commit.yml
- .github/workflows/reusable_workflow.yml
- som_crawlers/migrations/5.0.24.9.0/post-0001_increase_username_size.py
- som_crawlers/models/som_crawlers_config.py
- som_crawlers/models/som_ftp.py
Preparar som_crawlers per funcionar amb els 2 FTPs que queden que ara necessiten connexió activa:
- Per una banda, posar aquest tipus de connexió a la llibreria d'FTP
- Per altre, sistemes ha muntat un proxy per connectarse que requereix noms d'usuari més llargs, per tant aquest PR també amplia el camp usuari
> Fix ftp crawlers using active and preparing to proxy

- som_crawlers/migrations/5.0.24.9.0/post-0002_change_password_view.py
- som_crawlers/views/som_crawlers_config_view.xml
Millora la vista del crawler, posa les contrasenyes en ********
@jsarola 
Es veien les contrasenyes en text pla
Es veuen amb asterisc
> 💄 (crawlers): Millorar vista de crawler

- somre_giscere_facturacio/giscere_facturacio.py
- somre_giscere_facturacio/tarifes.py
- Adaptar càlculs de desviaments a format ISP15.
- https://trello.com/c/oYIMBxNx
- Els càlculs suporten només corbes horàries.
- Els càlculs suporten tant corbes horàries com quart-horàries.
- Requires https://github.com/gisce/erp/pull/22901
- Requires https://github.com/gisce/libFacturacioATR/pull/305
>  Adaptacions a quart-horària a Representació

- som_auvidi/__init__.py
- som_auvidi/giscedata_servei_generacio_facturacio.py
- som_auvidi/giscedata_serveis_generacio_facturacio.py
Poder personalitzar el missatge d'error al crear factura auvidi al comprobar si hi ha una factura per mateix periode y polissa
https://somenergia.openproject.com/projects/auvidi/work_packages/393/activity
https://github.com/gisce/erp/pull/21966
> Poder personalitzar el missatge d'error al crear factura auvidi repetida

- som_facturacio_comer/giscedata_facturacio_report_v2.py
Error detectat en un grup de factures
Bugbuster, cua de faileds
Es quedava a la cua no s'enviava
Es genera el pdf s'envia
> Bug en la generació de factures

- scripts/check_cchloader_version.py
- scripts/kill_firefox.sh
- scripts/requeue_failed.py
- scripts/update_gisce_forks.sh
Afegir scripts que tenim en funcionament a productiu
Bugbuster, acord d'equip de l'standup de 2025/02/06
Codi brut
> Afegir codi i scripts que ja estan en producció

- Keepup.md
> Test Keepup

- giscedata_facturacio_comer_som/giscedata_facturacio_comer_data.xml
- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
- giscedata_facturacio_comer_som/migrations/5.0.24.11.0/post-0002_update_rep_boe_data.py
Actualitzar el repartiment dels càrrecs i crear una variable de configuració
https://somenergia.openproject.com/wp/634
> ♻️ update rep boe and add conf var

- .github/workflows/pre-commit.yml
Actualitzar la versió del @actions/cache
[https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/](https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/
)
Feia servir la v1
Fa servir la v4
> Upgrade actions cache version

- som_polissa_condicions_generals/demo/res_partner_demo.xml
- som_polissa_condicions_generals/migrations/5.0.23.9.0/post-0001_migrate_report_puppeteer.py
- som_polissa_condicions_generals/tests/tests_report_backend_ccpp.py
🗃️ Afegir script de migració post migració puppeteer
Estava afegit directament al servidor, ja s'havia executat.
> 🗃️ Afegir script de migració post migració puppeteer

- som_auvidi/giscedata_serveis_generacio_view.xml
Arreglar tests de som_auvidi. Fan referència a aquesta PR que no està a productiu https://github.com/gisce/erp/pull/20693
Bugbuster arreglant tests
Es fa referència a camps que no existeixen encara a les vistes
> Arreglar tests de som_auvidi

- som_municipal_taxes/__terp__.py
- som_municipal_taxes/tests/test_wizard_creacio_remesa_pagament_taxes.py
✅ Arreglar tests som_municipal_taxes
RedTestBuster
> ✅ Arreglar tests som_municipal_taxes

- som_webforms_helpers/tests/test_tarifes.py
✅ Fix tests bugged in #636 changed prices IVA 10%
Ara els tests tenen en compte quan està actiu la reducció del IVA i quan no, alhora de fer els asserts dels preus.
RedTestBuster
> ✅ Fix tests som_webforms_helpers

- .github/workflows/reusable_workflow.yml
- somre_giscere_oferta/__terp__.py
✅ Clone repo module giscedata_omie_api 
RedTestBuster
> ✅ Arreglar els tests de giscedata_omie_api

- som_switching/wizard/wizard_create_r1.py
Poder crear reclamacions desde webclient i que no salti l'error:
> Poder crear reclamacions desde webclient

- som_atc/models/giscedata_switching_helpers.py
- som_switching/wizard/wizard_validate_d101.py
https://freescout.somenergia.coop/conversation/7983667?folder_id=185
No tancava el D101 quan era acceptació
Tanca el D101 quan era acceptació
> 🩹 We close the D101 when is accepted and others

- scripts/open_invoices.py
Integrar al repo un script de for el control de versions
Netejant PR antigues
> Add script open proveiders invoices

- som_switching/giscedata_switching_notification_data.xml
- som_switching/migrations/5.0.24.5.1/post-0002-create-notification-atr.py
Afegir noves notificacions de switching i ordenar algunes que hi havien
https://somenergia.openproject.com/projects/som-energia/work_packages/693/activity
No hi eren
Ja hi són
> 🗃️✨  Afegim noves notificacions i script de migració

- scripts/create_migration_script.py
Fix python 2 execution error (name of script)
Avoid file creation when there are no changes
Add script doc how to
> 🐛 Fix python 2 execution error (name of script).

- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
Arreglar bug de factures
bugbuster
Error
Imprimeix
> 🐛 do not read the cau if there is no autoconsum

- .github/workflows/reusable_workflow.yml
Afegir coverage dels nostres tests
https://somenergia.openproject.com/projects/som-energia/work_packages/752/activity
No teníem en compte el coverage
S'analitza el coverage
> Afegir coverage dels nostres tests

- .github/workflows/reusable_workflow.yml
Afegir el Coveralls GitHub Action
https://somenergia.openproject.com/projects/som-energia/work_packages/752/activity
> Add Coveralls GitHub Action

- .github/workflows/reusable_workflow.yml
Afegir el nom del mòdul com a tag en els dos serveis de coverage.
https://somenergia.openproject.com/projects/som-energia/work_packages/752/activity
> Add support for flags by module to create module coverage badges

- som_municipal_taxes/models/som_municipal_taxes_config.py
- som_municipal_taxes/tests/test_som_municipal_taxes_config.py
🐛 Arreglar generació fitxer impostos municipals per canvi de paràmetres del wizard
https://freescout.somenergia.coop/conversation/7993508?folder_id=283
Es generava un fitxer buit que després no es podia pujar a redsaras
Es genera correctament
> 🐛 Arreglar generació fitxer impostos municipals per canvi de paràmetres del wizard

- som_inversions/report/report_retencions_interessos_apo.mako
- som_inversions/report/report_retencions_interessos_apo.py
Enviament correcte de certificats de retencions d'aportacions.
https://somenergia.openproject.com/wp/789
Text incorrecte en 19%
Text incorrecte en 19% i métode d'obtenció de dades reutilitzable en report similar ' 'Retenció sobre el rendiment Generationkwh' .
**PR relacionada:**
https://github.com/Som-Energia/somenergia-generationkwh/pull/164
> Enviament certificats de retencions d'aportacions 2024

- scripts/cron_switchingreport.sh
✨ Canvi email informe de switching
Xat
> ✨ Canvi email informe de switching

- som_account_invoice_pending/models/update_pending_states.py
Arreglar quan un contracte canvi a default process en mig d'una factura impagada
https://freescout.somenergia.coop/conversation/7999417?folder_id=89
Fallava tot el canvi d'estat
Canvia la pòlissa a avís impagament confirmat
> 🚑️ Fix changing process during pending states

- som_crawlers/data/som_crawlers_step_data.xml
- som_crawlers/data/som_crawlers_task_data.xml
- som_crawlers/migrations/5.0.24.10.0/post-0001_add_e2m2_endesa_tasks.py
Descarregar de forma automàtica els casos E2 i M2 del portal d'Endesa.
https://somenergia.openproject.com/wp/741
No es desacarrega de forma automàtica els casos  E2 i M2 del portal d'Endesa i cal fer-ho a mà.
Es descarreguen de forma automàtica,
Depen d'aquesta PR
https://gitlab.somenergia.coop/IT/massive_importer_crawlers/-/merge_requests/109
> ✨ Afegir processos E2 i M2 als crawlers d'Endesa

- som_account_invoice_pending/models/update_pending_states.py
🐛  Fix doble assignation of variable
Fallaven els tests
https://github.com/Som-Energia/openerp_som_addons/runs/40665102413
> 🐛  Fix doble assignation of variable

- som_gurb/tests/tests_gurb_switching.py
Arreglar testos de gurb
Projecte Algemesí
No passava aquest tests
Ara es canvia el tipus de subsecció al d1 ? (preguntar)
> ✅ (gurb) Arreglar subseccio no canvia si no hi ha cau

- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
- giscedata_facturacio_comer_som/i18n/es_ES.po
- giscedata_facturacio_comer_som/i18n/giscedata_facturacio_comer_som.pot
- giscedata_facturacio_comer_som/migrations/5.0.24.11.0/post-0004_update_old_excess.py
- giscedata_facturacio_comer_som/report/components/invoice_details_td_excess_power_maximeter/invoice_details_td_excess_power_maximeter.mako
Arreglar el text pels excessos pre 2025 04
https://freescout.somenergia.coop/conversation/7994055?folder_id=87
es mostraven com els nous
Es mostren 2x
> Fix pre 2025 04 excess

- som_polissa_condicions_generals/report_backend_mailcanvipreus.py
Fer modificacions per canvi de preus
https://somenergia.openproject.com/wp/746
> ✨Update price change backend to June 2025

- som_facturacio_flux_solar/giscedata_bateria_virtual.xml
- som_facturacio_flux_solar/giscedata_bateria_virtual_percentatges_acumulacio.py
- som_facturacio_flux_solar/migrations/5.0.25.1.0/post-0002_update_nom_sols_generats_aplicats.py
- som_facturacio_flux_solar/migrations/5.0.25.5.0/post-0001_resum_facturacio_bateria_virtual.py
Canviar nombres de los enlazes de la PR #22898
- https://github.com/gisce/erp/pull/22898
> Canviar nombres de los enlazes de la PR 22898

- .github/workflows/schedule_tests_som_leads_polissa.yml
Afegir codecov token a som_leads_polissa
-
No hi era
Hi és
X
> 🐛(ci) Afegir codecov token a som_leads_polissa

- som_crawlers/data/som_crawlers_step_data.xml
- som_crawlers/data/som_crawlers_task_data.xml
- som_crawlers/migrations/5.0.24.5.0/post-0002_NEW_constancia_crawler_f1_update_views_and_fields.py
Afegir crawler La Constancia per als F1s
https://somenergia.openproject.com/projects/som-energia/work_packages/769/activity
El crawler només baixava els casos ATR
Ara n'hi ha un altre que baixa els F1s
> Afegir crawler La Constancia per als F1s

- .github/workflows/all_modules_test.yml
- .github/workflows/reusable_workflow.yml
- codecov.yml
Tractar el coverage de manera independent per mòdul
Projecte Algemesí
Sempre es compara el coverage amb la darrera execució, barrejant coverage entre mòduls.
Tractar el coverage de manera independent per mòdul, comparant amb el darrer coverage del mòdul.
> Add coverage by module independent

- som_switching/giscedata_polissa_view.xml
- som_switching/migrations/5.0.24.5.0/post-0001_NEW_add_collectiu_column_to_lot_view_update_views_and_fields.py
Afegir columna col·lectiu a les vistes:
- polissa
https://somenergia.openproject.com/projects/som-energia/work_packages/729/activity
no es mostra
es mostra
> 💄Afegir columna col·lectiu i subsecció a la vista de Polissa

- som_polissa/giscedata_polissa_view.xml
- som_polissa/migrations/5.0.24.5.0/post-0004_FIX_strange_error_when_modifyng_polissa_view_update_views_and_fields.py
- som_switching/giscedata_polissa_view.xml
- som_switching/migrations/5.0.24.5.0/post-0002_FIX_strange_error_when_modifyng_polissa_view_update_views_and_fields.py
Arreglar bug de vista de polisses que salta al mòdul som_autoreclama
Incidència, dilluns matí
Mòdul en vermell
Mòdul en verd
> Solucionar error al modificar la vista de polissa

- som_facturacio_switching/giscedata_facturacio_importacio_linia.py
- som_facturacio_switching/giscedata_facturacio_importacio_linia_view.xml
- som_facturacio_switching/migrations/5.0.24.5.0/post-0001_NEW_add_subseccio_collectiu_to_imported_f1_update_views_and_fields.py
Afegir tipus_subsecció i es_collectiu informats al F1 a la vista de F1's importats
https://somenergia.openproject.com/projects/som-energia/work_packages/729/activity
no es mostra ni es pot cercar
es mostra i es pot cercar
> ✨ Afegir tipus_subsecció i es_colectiu informats al F1 a la vista de F1's importats

- .github/labeler.yml
- .github/workflows/schedule_tests_som_stash.yml
- som_stash/sql/query_partner_pol_expired.sql
- som_stash/sql/query_soci_expired.sql
Ajustar el filtre fet per obtenir els partner vinculats a les sòcies a anonimitzar. Es fa com a millora fer donar més fiabilitat.
https://somenergia.openproject.com/wp/812
No excloia els partner vinculats a sòcies que podien estar com a altre rol a les pòlisses o amb aportacions.
Ja els exclou
> ⚡️(som_stash) - Millores

- som_gurb/__terp__.py
- som_gurb/migrations/5.0.24.5.0/post-0001_ADD_all_gurb_cases_update_views_and_fields.py
- som_gurb/security/ir.model.access.csv
- som_gurb/tests/tests_gurb_switching.py
- som_gurb/wizard/__init__.py
- som_gurb/wizard/wizard_atr_gurb_model.py
- som_gurb/wizard/wizard_atr_gurb_model_view.xml
Afegir el llistat de tots els casos ATR de GURB
https://somenergia.openproject.com/wp/484
No existia
Existeix
> Add all gurb cases

- report_tester/__terp__.py
- report_tester/migrations/5.0.24.5.0/post-0001_NEW_add_more_actions_to_report_test_update_views_and_fields.py
- report_tester/models/report_test.py
- report_tester/security/ir.model.access.csv
- report_tester/views/report_test_view.xml
- report_tester/wizard/__init__.py
- report_tester/wizard/wizard_report_test_attach_to_invoice.py
- report_tester/wizard/wizard_report_test_attach_to_invoice.xml
- report_tester/wizard/wizard_report_test_group_view_tests.py
- report_tester/wizard/wizard_report_test_group_view_tests.xml
- report_tester/wizard/wizard_report_test_view_attached.py
- report_tester/wizard/wizard_report_test_view_attached.xml
Millorar la funcionalitat del report tester
Incidència, bugbuster, factures no imprimibles diàriament
> Afegir accions al report_tester

- report_tester/migrations/5.0.24.5.0/post-0001_NEW_add_more_actions_to_report_test_update_views_and_fields.py
- report_tester/security/ir.model.access.csv
Arreglar migració
Autoincidència
Error en passar la migració
Migració Ok
> 🐛 Arreglar la migració del report tester quan afegim nous wizards al mòdul

- scripts/informe_fue.py
- scripts/informe_fue_part1_pdf_factura_estimada.py
- scripts/informe_fue_part2_obtenir_dades_factures.py
Afegir scripts del informe FUE
https://somenergia.openproject.com/projects/som-energia/work_packages/349/activity
Estaven en un gist
Estan al repo
> ✨  Add informe fue script

- scripts/recretate_file.py
✨ Script to recreate a file passed by parameter
> ✨ Script to recreate a file passed by parameter

- .github/labeler.yml
- .github/workflows/schedule_tests_som_dashboard.yml
- som_dashboard/__terp__.py
- som_dashboard/som_dashboard_contractes.xml
- som_dashboard/som_dashboard_custom_search.xml
- som_indexada/data/custom_search_data.xml
> Add som dashboards again

- som_indexada/data/custom_search_data.xml
- som_indexada/migrations/5.0.2.108/post-0003_custom_search_data.py
> 🐛 fix script ids

- som_dashboard/__terp__.py
- som_dashboard/migrations/5.0.0-dev/post-0001_som_dashboard_fase_3_update_views_and_fields.py
- som_dashboard/som_dashboard_gc_fase_3.xml
Afegir el dashboard de Fase 3 de Gestió de contractes
Bé, m'he motivat amb una targeta del client web
No existia
Potser li és útil a la persona que està fent la fase 3
Té un script de migració. Mòdul som_dasboard
> 📈 Gestió de Contractes: Dashboard Fase 3

- .github/workflows/reusable_workflow.yml
Add DB in redis conn in config file, for Python 3 compatibility modules
> Add DB in redis conn in config file

- .github/workflows/all_modules_test_py3.yml
🔧 Add all modules tests for Py3
> 🔧 Add all modules tests for Py3

- giscedata_facturacio_comer_som/__terp__.py
- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
- giscedata_facturacio_comer_som/i18n/es_ES.po
- giscedata_facturacio_comer_som/i18n/giscedata_facturacio_comer_som.pot
- giscedata_facturacio_comer_som/migrations/5.0.25.6.0/post-0001_load_translations.py
- giscedata_facturacio_comer_som/report/components/contract_data_td/contract_data_td.mako
- giscedata_facturacio_comer_som/report/components/invoice_details_td/invoice_details_td.mako
- giscedata_facturacio_comer_som/report/components/invoice_details_td_auvi/invoice_details_td_auvi.mako
- giscedata_facturacio_comer_som/report/components/invoice_details_td_energy/invoice_details_td_energy.mako
- giscedata_facturacio_comer_som/report/components/invoice_details_td_energy_auvi/invoice_details_td_energy_auvi.mako
- giscedata_facturacio_comer_som/report/components/logo/logo.mako
- giscedata_facturacio_comer_som/tests/tests_FacturacioFacturaReport_some.py
Mostrar les dades relatives als AUVI al PDF de la factura
⚠️ NO ES POT FER MERGE FINS QUE NO ESTIGA INSTAL·LAT TOT AUVI A PRODUCTIU.
https://somenergia.openproject.com/wp/373
No mostra res all respecte
Ara mostra la info acordada
> [PDF factura] Adaptacions per AUVI

- som_polissa_condicions_generals/i18n/es_ES.po
- som_polissa_condicions_generals/i18n/som_polissa_condicions_generals.pot
- som_polissa_condicions_generals/migrations/5.0.25.6/post-0001_load_translations.py
Arreglar traduccions de les condicions generals
https://somenergia.openproject.com/projects/som-energia/work_packages/460/activity
Typos
correcte
> Arreglar traduccions de les condicions generals

- scripts/check_cchloader_version.py
🐛 Restart all services after reinstalling cchloader
> 🐛 Restart all services after reinstalling cchloader

- som_crawlers/data/som_crawlers_config_data.xml
- som_crawlers/data/som_crawlers_step_data.xml
- som_crawlers/data/som_crawlers_task_data.xml
- som_crawlers/migrations/5.0.24.5.0/post-0003_NEW_COELCA_crawler_update_views_and_fields.py
Afegir el crawler de la distri COELCA
https://freescout.somenergia.coop/conversation/8020504?folder_id=87
> ✨ New COELCA Crawler

- som_polissa_soci/migrations/5.0.24.5.0/post-0001_FIX_view_redirect_for_polissa_soci_update_views_and_fields.py
- som_polissa_soci/res_partner_view.xml
Arreglar redirecció de la vista de l'acció de "Com a Soci" des de partner
https://somenergia.openproject.com/projects/som-energia/work_packages/933/activity
Es mostrava un títol erroni a la visat de "Com a Soci"
Es mostra "Pòlissa"
> Arreglar redirecció de la vista de l'acció de "Com a Soci" des de partner

- som_polissa_condicions_generals/report/condicions_particulars_puppeteer.css
💄🐬 Canviar números per lletres a les CCGG
https://somenergia.openproject.com/projects/som-energia/work_packages/860/activity
Ara carreguem els estils CSS de la web de les CCGG
> 💄🐬 Canviar números per lletres a les CCGG

- giscedata_facturacio_comer_som/i18n/es_ES.po
- giscedata_facturacio_comer_som/i18n/giscedata_facturacio_comer_som.pot
- giscedata_facturacio_comer_som/migrations/5.0.24.5.0/post-0001_MOD_factura_auto_col_migrate_translations.py
- giscedata_facturacio_comer_som/report/components/energy_consumption_detail_td/energy_consumption_detail_td.mako
- giscedata_facturacio_comer_som/report/components/energy_consumption_detail_td_info/energy_consumption_detail_td_info.mako
- scripts/create_migration_script.py
Canviar el missatge en cas d'ajustos de lectures en autoconsum col·lectiu
https://somenergia.openproject.com/projects/som-energia/work_packages/914/activity
El missatge deia que l'ajust era per el balanç horari, i no era cert.
El missatge diu que és un ajust d'autoconsum.
> 🐬 Canviar el missatge en cas d'ajustos de lectures en autoconsum col·lectiu

- giscedata_facturacio_comer_som/report/components/energy_consumption_detail_td_info/energy_consumption_detail_td_info.mako
Eliminar un link duplicat
Report tester
El link es mostrava dues vegades
El link només es mostra dues vegades
> 🐛 fix duplicated link

- som_polissa_condicions_generals/report/components/auvi.mako
Arreglar decimals a percentatge auvi
https://freescout.somenergia.coop/conversation/8028504?folder_id=87
2 decimals
6 decimals
> 🐛 (auvi) Decimals a les Condicions Generals

- som_atc/models/giscedata_atc.py
Deixar traça de la pila d'execució quan es tanca un cas ATC per detectar quins mecanismes automàtics estan entrant en joc
https://somenergia.openproject.com/projects/som-energia/work_packages/864/activity
res
Guarda les dades al cas aTC
> Capturar el tancament de cas per detectar automatisme

- som_leads_polissa/giscedata_crm_lead.py
- som_leads_polissa/migrations/5.0.24.5.0/post-0003_new_field_comercial_info_accepted.py
- som_leads_polissa/tests/tests_som_lead_www.py
- som_leads_polissa/views/giscedata_crm_lead_view.xml
- som_leads_polissa/www/som_lead_www.py
Afegeix check de som serveis al lead
-
No ho teníem implementat i era "important"
Ara apareix al lead, a l'apartat de la sòcia
> ✨ (lead) Afegeix comercial_info_accepted

- som_atc/models/giscedata_atc.py
- som_autoreclama/migrations/5.0.24.5.0/post-0003_FIX_aom_autoreclama_f1c_automation_crontab_miss_migrate_data.py
- som_autoreclama/som_autoreclama_state_data.xml
Afegir ir_cron que falta
https://somenergia.openproject.com/projects/som-energia/work_packages/690/activity
no funciona el cron
Si funciona el cron
> 🐛 Afegir ir_cron que falta

- som_leads_polissa/giscedata_crm_lead.py
- som_leads_polissa/tests/tests_som_lead_www.py
Aquest PR arregla la chapucilla del context pel bank i guarda el numero de socia com a referencia de la remesa
https://freescout.somenergia.coop/conversation/8034310?folder_id=103
> Fix remesas bank and name

- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
Imprimir el pdf de la factura
https://freescout.somenergia.coop/conversation/8035776?folder_id=87
error
imprimeix
> 🐛 Error la imprimir el pdf per autocnsum colectiu amb dadesde p4 p5 i p6  presents en 2.0TD

- som_leads_polissa/giscedata_crm_lead.py
- som_leads_polissa/tests/tests_som_lead_www.py
- som_leads_polissa/www/som_lead_www.py
Arreglar cosetes (mirar incidencies)
https://freescout.somenergia.coop/conversation/8035227?folder_id=103
https://freescout.somenergia.coop/conversation/8035075?folder_id=103
https://freescout.somenergia.coop/conversation/8035072?folder_id=103
> Fix various leads bugs

- giscedata_facturacio_comer_som/report/components/energy_consumption_detail_td_surplus/energy_consumption_detail_td_surplus.mako
Arreglar una línia que apareix en el component de excedents
https://freescout.somenergia.coop/conversation/8032814?folder_id=87
línia on no toca
línia quan i on toca
> 🐛 Arreglar linia que apareix a component excedents de la factura en pdf

- som_gurb/__terp__.py
- som_gurb/migrations/5.0.24.5.0/post-0002_NEW_GURB_savings_script_update_views_and_fields.py
- som_gurb/security/ir.model.access.csv
- som_gurb/wizard/__init__.py
- som_gurb/wizard/wizard_calculate_gurb_savings.py
- som_gurb/wizard/wizard_calculate_gurb_savings_view.xml
Fer un wizard per calcular l'estalvi de GURB
https://somenergia.openproject.com/wp/536
> ✨ new wizard to calculate gurb savings

- som_gurb/models/giscedata_switching.py
Es feia browse de llista però només es passava un id
Errpr
No funcionava, bug no detectat amb testos
Funciona
> 🐛 (gurb) Es feia browse de llista però només es passava un id

- som_gurb/models/giscedata_switching.py
arreglar bug
https://freescout.somenergia.coop/conversation/8037737?folder_id=87
falla
no falla
> 🐛 Arreglar export xml som_gurb

- som_gurb/models/som_gurb.py
Permetre entrar al gurb encara que no hi hagi gen_power
Xat
No es pot entrar al gurb
> 🚑️ fix ff when gurb is new

- som_leads_polissa/tests/tests_som_lead_www.py
- som_leads_polissa/www/som_lead_www.py
Fins ara sempre es posava 230 (monofàsica), ara permet també posar la trifàsica.
https://somenergia.openproject.com/wp/1072
> ✨ Leads now can recieve monofasic or trifasic phase

- som_facturacio_flux_solar/__init__.py
Arreglar els tests de **som_facturacio_flux_solar**, ja que han fallat en l'execució setmanal.
[https://github.com/Som-Energia/openerp_som_addons/actions/runs/17196160503](https://github.com/Som-Energia/openerp_som_addons/actions/runs/17196160503)
```sql
UndefinedColumn: column "data_inici_descomptes" does not exist
LINE 106:                 SELECT MIN(data_inici_descomptes)
```
Es canvia l'ordre dels models perquè el model relacionat ja estigui creat
> Arreglar els tests de som_facturacio_flux_solar

- .github/workflows/keep-prs-gisce-alive.yml
Contrabot d'arxivament de PRs https://github.com/gisce/erp/blob/developer/.github/workflows/stale_issues.yml
Havíem d'anar a mà una a una a fer comentari per evitar que es quedin en "stale" les PRs de GISCE que tenim aplicades i que encara no ens han mergejat.
Un bot s'executa cada 90 dies per fer de contrabot al de GISCE
> Contrabot d'arxivament de PRs de GISCE

- som_sortida/models/giscedata_polissa.py
🐛 (ctss) Hot fix temporal per la creació de la polissa en el CTSS
https://freescout.somenergia.coop/conversation/8052987?folder_id=90
No ens funcionaven els formularis pq la funció de create fallava
No és tant xuli però funciona. Es queda el codi així a l'espera d'un test.
Si estàs mirant això i és no sé... El 2026, vol dir que ningú va arreglar aquest codi... I és un hot fix temporal!!!!!
> 🐛 (ctss) Hot fix temporal per la creació de la polissa en el CTSS

- som_gurb/models/som_gurb_group.py
Arreglar comptador de betes en Gurb Grup
Incidència
No sortia bé el percentatge pq no llegia l'objecte que tocava
Ara ja sortirà bé
> 🐛 (gurb) Arreglar comptador de betes en Gurb Grup

- som_poweremail_common_templates/commontemplates_data.xml
- som_poweremail_common_templates/migrations/5.0.23.9/pre-0003_add_common_social_links_templates.py
Que sigui facil afegir la botonera a qualsevol mail
https://somenergia.openproject.com/wp/1119
> ✨ Add common social link templates

- som_gurb/__init__.py
- som_gurb/demo/som_gurb_service_demo.xml
- som_gurb/migrations/5.0.24.5.0/post-0004_ADD_helper_info_gurb_migrate_fields_security_translations.py
- som_gurb/security/ir.model.access.csv
- som_gurb/tests/__init__.py
- som_gurb/tests/tests_gurb_www.py
- som_gurb/www/__init__.py
- som_gurb/www/som_gurb_www.py
Afegir crida a helper i endpont per gurb
https://somenergia.openproject.com/projects/som-energia/work_packages/1050/activity
no
> Afegir helper per www

- som_auvidi/giscedata_serveis_generacio.py
- som_leads_polissa/giscedata_crm_lead.py
- som_leads_polissa/migrations/5.0.24.5.0/post-0005_NEW_crm_lead_id_migrate_fields_data.py
- som_leads_polissa/views/giscedata_crm_lead_view.xml
> New crm lead

- giscedata_facturacio_comer_som/giscedata_facturacio_report.py
titol
https://freescout.somenergia.coop/conversation/8058280?folder_id=90
Peta
No peta
> 🐛 Pdf de la factura dona error si el idioma es en_us

- som_gurb/demo/som_gurb_cau_demo.xml
- som_gurb/migrations/5.0.24.5.0/post-0006_add_gurb_cups_coordinates_migrate_fields_data.py
- som_gurb/models/som_gurb_cau.py
- som_gurb/tests/tests_gurb_www.py
- som_gurb/views/som_gurb_cau_view.xml
- som_gurb/www/som_gurb_www.py
Refer "helper" de les coordenades de GURB
https://somenergia.openproject.com/projects/som-energia/work_packages/1113/activity
Estava en una PR difícil de mergejar pq estava bastant antiga
S'ha portat el codi a "l'actualitat"
> ♻️  (gurb) Refer "helper" de les coordenades de GURB

- som_leads_polissa/giscedata_crm_lead.py
- som_leads_polissa/migrations/5.0.24.5.0/post-0006_add_default_crm_lead_id.py
Afegir valor per defecte a giscedata_crm_lead.crm_lead_id ja que sinó el camp enter queda a booleà fals
Projecte comercial
> Afegir valor per defecte a giscedata_crm_lead.crm_lead_id

- som_leads_polissa/giscedata_crm_lead.py
- som_leads_polissa/tests/tests_som_lead_www.py
- som_leads_polissa/www/som_lead_www.py
Afegir si la persona és jurídica al lead per l'equip de Dades
Pol
Es podia deduir però era problemàtic
Ho poden llegir "straightforward"
> 🏗️ (leads) Afegir si la persona és jurídica al lead per l'equip de Dades

- som_crawlers/models/som_crawlers_config.py
Eliminar les cometes als tests de configuració dels crawlers
https://freescout.somenergia.coop/conversation/8060871?folder_id=87
Surt amb cometes dificulta el selecciona, copia i pega
Sense cometes, selecciona copia i pega mes fàcil
> 🐛 Eliminar cometes en les text de configuració dels crawlers

- som_switching/wizard/wizard_create_r1.py
Generar un comentari buit en la creació de les R1 048 per evitar cam obligatori de comentaris
https://freescout.somenergia.coop/conversation/8060045?folder_id=87
havien de posar quelcom
Hi ha un espai en blanc per defecte i poden continuar
> ✨ Comentari buit en la creació de R1 048
