Som-Energia/openerp_som_addons

som_webforms_helpers/giscedata_polissa_tarifa.py
- Fix the incorrect periods returned in the `get_tariff_prices` function in `som_webforms_helpers` module.
- The function used the tariff periods list, without using the `get_periodes` function.
- The `get_periodes` function is used with `sense_agrupar=True` in context to get the correct number of periods.
=> FIX: Get the correct periods to compute tariff prices for webforms

powersms/powersms_smsbox_view.xml, powersms/tests/powersms_tests.py, powersms/wizard/wizard_send_sms.py
New `create_empty_number` boolean in `save_to_sms_box` context (False by default) to control whether sms with empty "to" should be created or not. 
It also adds field `reference` in `powersms_smsbox` view.
=> `create_empty_number` in `save_to_sms_box` context to control sms creation when empty "to"

account_invoice_som/account_invoice_som_report.xml
Remove noupdate=1 for `account.invoice` entry in `ir.actions.report.xml` model, to force the record created in `account_invoice_base` to be overridden with the custom report.
=> Remove noupdate=1 for som account.invoice report

som_infoenergia/README.md, som_infoenergia/som_infoenergia_enviament.py, som_infoenergia/som_infoenergia_lot.py, som_infoenergia/som_infoenergia_view.xml, som_infoenergia/tests/som_infoenergia_demo.xml, som_infoenergia/tests/test_enviament.py, som_infoenergia/tests/test_lot_enviament.py
- New state `baixa` for non-active contracts
- New fields for couting contracts found in searches
- Using `cancelat` state for refering to non-active contracts.
- Nonexistent found in search field
- New state `baixa` for non-active contracts
- Added `found_in_search` fields
=> Added `baixa` state and  `found_in_search` field

som_account_invoice_pending/__init__.py, som_account_invoice_pending/account_invoice_pending_history.py, som_account_invoice_pending/account_invoice_pending_view.xml, som_account_invoice_pending/som_account_invoice_pending_exceptions.py, som_account_invoice_pending/tests/update_pending_states_tests.py, som_account_invoice_pending/tests/wizard_unlink_sms_pending_history_tests.py, som_account_invoice_pending/update_pending_states.py
* Added exception handling for 48h and annexIV functions.
* Added "Observations" field into `account.invoice.pending.history`.
=> Single 48h sms per contract

account_invoice_som/__terp__.py, account_invoice_som/account_invoice_view.xml
- Set `payment_type`, `origin` and `origin_date_invoice` as required fields in supplier account invoices form.
- `account_invoice_som`
- especificar que módulos y versión
=> Added required fields in supplier invoices form

som_factures_paper/__init__.py, som_factures_paper/__terp__.py, som_factures_paper/security/ir.model.access.csv, som_factures_paper/som_factures_paper.xml, som_factures_paper/wizard/__init__.py, som_factures_paper/wizard/wizard_paper_invoice_som.py, som_factures_paper/wizard/wizard_paper_invoice_som.xml
- Es necessita gestionar el volum creixent de factures en paper. Cal crear un wizard que en faciliti la tasca de cercar i generar els pdf implicats en la facturació per contractes que han de notificar la factura físicament en paper i no només per e-mail.
- Treball manual minuciós i amb força propens a l'error
- wizard
- som_factures_paper
=> Assistent per la impressió de factures en paper

account_invoice_som/__init__.py, account_invoice_som/__terp__.py, account_invoice_som/account_invoice.py, account_invoice_som/account_invoice_data.xml, account_invoice_som/tests/__init__.py, account_invoice_som/tests/account_invoice_demo.xml, giscedata_facturacio_som/__init__.py, giscedata_facturacio_som/__terp__.py, giscedata_facturacio_som/giscedata_facturacio.py, giscedata_facturacio_som/tests/__init__.py
- Fer les cerques de factura per número de factura més ràpides.
- Les cerques per número de factura es consultaven a la base de dades amb `ilike`
-  El camp de cerca de "número de factura" del llistat de factures, fa cerques exactes. Per fer cerques per `ilike` cal posar un %.
- som_polissa
- `account_invoice_number_cerca_exacte`: Si esta activada, les cerques per factura són exactes. Sinó són sempre per `ilike`.
=> Modificar camp de número de factura perquè facis cerques exactes

som_infoenergia/som_infoenergia_lot.py, som_infoenergia/tests/test_lot_enviament.py
Fer que el csv que baixem de Beedata es llegeixi des de la carpeta temporal del servidor, i no des del clúster de Mongo on l'hem penjat. Ens hem trobat que a vegades no s'havia replicat el fitxer als nodes de lectura quan l'anàvem a llegir.
https://secure.helpscout.net/conversation/1730313942/10482085?folderId=3063409
Primer penjava el fitxer i després el llegia per crear els "Enviaments"
Baixa el fitxer, el penja a Mongo, però per crear els enviaments, llegeix el fitxer baixat prèviament.
=> Genera Enviaments del CSV de Beedata amb el fitxer temporal

account_invoice_som/account_invoice.py, account_invoice_som/account_invoice_data.xml, account_invoice_som/tests/__init__.py, giscedata_facturacio_som/giscedata_facturacio.py, giscedata_facturacio_som/tests/__init__.py
(D'igual forma que a https://github.com/Som-Energia/openerp_som_addons/pull/71)
- Fer les cerques de factura per origen més ràpides.
- https://trello.com/c/lJS1YwGD/4704-add-cerca-exacta-per-origen-de-factures-i-f1ns
- Les cerques per origen es consultaven a la base de dades amb `ilike`
- El camp de cerca de "origen" del llistat de factures, fa cerques exactes. Per fer cerques per ilike cal posar un %.
- `account_invoice_som`
=> Afegida cerca exacta per origen

account_account_som/account_view.xml
- Des del wizard de balanç de sumes i saldos, s'utilitza la vista de acount.account.tree` llegint tots els camps del llistats entre els quals es troba `balance`. Això alenteix molt el llistat.
- Posant prioritat alta, fem que la vista rapida sigui la que utilitzi el wizard.
[X] Reiniciar serveis
[X] Actualitzar mòdul
- `account_account_som`
=> Afegida prioritat 1 a `account.account.fast.tree`

som_webforms_helpers/giscedata_polissa_tarifa.py
Adaptar els impostos del RD 17/2021 als preus de les tarifes.
és Incidència
Es mostrava el preu amb impost aplicant l'IESE del 5.11%.
Si no s'indica la posició fiscal, es calculen els preus amb impostos segons la posició fiscal per defecte definida a la `ir.property` de nom `property_account_position`
=> FIX prices with taxes

som_infoenergia/som_infoenergia_enviament.py, som_infoenergia/som_infoenergia_lot.py, som_infoenergia/tests/EiE_extra_info.csv, som_infoenergia/tests/test_lot_enviament.py, som_infoenergia/tests/test_wizards.py, som_infoenergia/wizard/wizard_create_enviaments_from_csv.py, som_infoenergia/wizard/wizard_create_enviaments_from_csv_view.xml
Poder carregar un CSV que et crei n enviaments per número de pólissa (a la primera columna del CSV) i que la resta de columnes les posi en un diccionari al camp "Informació adicional" per a que puguin fer-se servir des dels correus electrònics.
[Targeta](https://trello.com/c/q4IcHjkx/4791-0-8-p3-ep213-carregar-csv-a-enviament-infoenergia-i-enviament-massiu-i-guardi-diccionari-de-dades)
Només es creaven els n enviaments a partir del número de pòlissa.
S'afegeix aquest diccionari de dades
=> Add extra_info when CSV is loaded in Lot Enviament

giscedata_facturacio_som/wizard/wizard_fraccionar_via_extralines.py
- Permetre el fraccionament sobre una factura amb un pagament parcial existent
- https://trello.com/c/aR5vk8rQ/3621-0-1-p16-millores-fraccionament-extralines
- L'assistent funciona pel fraccionament del `total_amount` de la factura
- L'assistent funciona pel fraccionament del `residual` de la factura
=> Wizard de fraccionament via extralines agafant el  `residual` en lloc del `amount_total`

som_infoenergia/wizard/wizard_create_enviaments_from_object.py, som_infoenergia/wizard/wizard_download_pdf.py
Evitar propagació de totes les active_ids en cada un dels jobs
Cada un dels jobs rebia el llistat de totes les active_ids que tenia el wizard
No es propaguen totes les active_ids
=> FIX: Evitar propagació de totes les active_ids en cada un dels jobs

giscedata_facturacio_comer_som/giscedata_facturacio_report.py, giscedata_facturacio_comer_som/i18n/es_ES.po, giscedata_facturacio_comer_som/i18n/giscedata_facturacio_comer_som.pot, giscedata_facturacio_comer_som/report/components/energy_consumption_detail_td_base/energy_consumption_detail_td_base.mako
Afegir a la factura l'origen de lectures calculada per cch a la factura en pdf
https://trello.com/c/vpCyz1Aa/4924-0-8-p3-prova-pilot-facturaci%C3%B3-setmanal
Es mostraba com a real
Es mostra com a "Calculada per CCH"
giscedata_facturacio_comer_som
=> Afegir l'origen calculada per CCH a la factura en pdf

som_facturacio_calculada/giscedata_polissa.py, som_facturacio_calculada/tests/__init__.py, som_facturacio_calculada/tests/test_polissa_lectures_calculades.py
Controlar el cas en que no hi ha prou lectures cch per a generar lectures calculades a 7 dies per que continui funcionant correctament.
https://trello.com/c/vpCyz1Aa/4924-0-8-p3-prova-pilot-facturaci%C3%B3-setmanal
Saltava excepció no controlada i finalitzava l'execució del assistent.
Es controla l'excepció
=> Controlar cas quan no hi ha prou lectures cch en genear lectures a 7 dies

som_facturacio_comer/__terp__.py, som_facturacio_comer/wizard/__init__.py, som_facturacio_comer/wizard/wizard_refund_rectify_from_origin.py, som_facturacio_comer/wizard/wizard_refund_rectify_from_origin_view.xml
Tenir una acció per abonar i rectificar un període de facturació a partir d'una factura de proveïdor d'aquest període. 
https://trello.com/c/N2laT6WZ/4997-add-refacturacions-factures-g-dauto-endesa
No existia
L'acció esborra i carrega lectures pel període, genera les factures abonadores i rectificadores. També té la opció d'obrir, agrupar i remesar (només les agrupacions a pagar), i d'enviar un mail de pòlissa.
=> Add refund rectify origin

som_account_invoice_pending/requirements.txt, som_account_invoice_pending/wizard/wizard_tugesto_invoices_export.py
Poder obtenir el ID especific de Tugesto per a cada municipi cridant a un paquet de PyPy que hem creat que implementa una funcióper retornar aquest ID passant-li nom_ciutat (obligat), codi_provincia (opcional)i codi INE de la població (opcional).
Aquest ID és requerit per Tugesto en una de les columnes del llistat Excel que s'exporta.
https://trello.com/c/H35Yx6Ju/4930-0-3-p16-acci%C3%B3-extreure-excel-txt-per-carregar-expedients-a-tugesto
Usavem el codi INE però Tugesto ho va rebutjar
Usem el ID específic de Tugesto per als municipis
=> ADD mapping from address city and Tugesto specific ID for each city

som_facturacio_comer/giscedata_facturacio_contracte_lot.py
En [aquesta issue](https://github.com/gisce/erp/issues/14301) estem analitzant el nombre d'"updates" que es fan al crear una factura i intentant optimitzar-ho.
[[EP251] Anàlisi que passa amb l'account_invoice](https://trello.com/c/2QNTwnOD/4960-ep251-an%C3%A0lisi-que-passa-amb-laccountinvoice)
Els camps següents s'updataven un a un:
- total_incidencies
- date_invoice
- consum_facturat
- te_generation
- data_final
S'updaten tots de cop
=> Unificar l'actualització dels camps funció de la polissa lot

giscedata_facturacio_som/__terp__.py, giscedata_facturacio_som/giscedata_facturacio_data.xml
- Ometre comprovació de factures en esborrany mitjançant una variable de configuració
- Requereix de https://github.com/gisce/erp/pull/14648
- https://secure.helpscout.net/conversation/1921269908/12579214?folderId=3101096
- Des la versió 107.5 s'impedeix el pagament de la remesa si existeix alguna factura en esborrany
- Amb la variable a 1, s'omet la comprovació
- `giscedata_facturacio_som`
=> Afegida variable `res.config` per ometre comprovació de factures en esborrany

som_account_invoice_pending/__terp__.py, som_account_invoice_pending/demo/som_account_invoice_pending_demo_data.xml, som_account_invoice_pending/requirements.txt, som_account_invoice_pending/som_account_invoice_pending_data.xml, som_account_invoice_pending/tests/__init__.py, som_account_invoice_pending/tests/update_pending_states_tests.py, som_account_invoice_pending/tests/wizard_pay_invoice_tests.py, som_account_invoice_pending/wizard/__init__.py, som_account_invoice_pending/wizard/wizard_pay_invoice.py
- Fer les modificacions addients al l'ERP per enllaçar el desenvolupament fer a la OV per pagar factures pendents.
-  https://trello.com/c/GSVDDFRZ/5018-0-0-p37-ep212-pagar-factures-ov-requereix-atenci%C3%B3-posada-en-producci%C3%B3
Inexistent
- S'exten el comportament de l'assistent `facturacio.pay.invoice` per tal d'enviar un correu a la bústia de cobraments si es compleix que:
-  La factura prové d'un estat pendent que aparegui a la llista definida a la variable de config `pay_alert_pending_states_som`.
-  El diari pel qual s'està intentant pagar la factura és el de pagament TPV  `'som_account_invoice_pending', 'tpv_journal'`
-  A més afegim un comentari a la factura on queda reflexat que ha estat pagat a través de la OV.
- `som_account_invoice_pending`
=> Pagar factures des de la OV: adaptació del `facturacio.pay.invoice` per generar avísos

giscedata_facturacio_comer_som/giscedata_facturacio_report.py
Detectar com a indexades les indexades de Canàries i Balears
https://secure.helpscout.net/conversation/1933708774/12648381?folderId=3904968
Només es detectava com a indexades les factures de les indexades de península.
Es detecten les indexades de canàries i balears
=> Noves llistes de preus indexades

som_switching/__init__.py, som_switching/__terp__.py, som_switching/giscedata_switching_b1.py, som_switching/tests/__init__.py, som_switching/tests/tests_wizard_switching_b1.py, som_switching/wizard/__init__.py, som_switching/wizard/giscedata_switching_wizard_b1.py, som_switching/wizard/giscedata_switching_wizard_b1.xml
Afegir al wizard el telefon de contacte pel cas B101
https://trello.com/c/7p9NI4eH/4985-0-0-p6-0-4-ep214-afegir-camp-tel%C3%A8fon-de-contacte-al-formulari-de-b1-igual-que-el-m1
El wizard no permetia afegir un telefon de contacte
El wizard permet afegir un telefon de contacte
- [X ] Actualitzar mòdul
som_switching
=> Agregar el telefon al cas B101

som_facturacio_comer/giscedata_facturacio_validation.py, som_facturacio_comer/giscedata_polissa.py, som_facturacio_comer/giscedata_polissa_view.xml, som_facturacio_comer/tests/tests_facturacio_warnings.py
- Canviar el camp teoric_maximum_consume_GC a la pestanya Facturació
- Evitar el scroll de un camp númeric mostrant-lo com a char
https://trello.com/c/01PrRZI2/4910-0-4-p44-modif-camp-teoric-maximum-consume-per-categoria-gran-contracte
El camp es trobava en la part del formulari comuna a pòlissa i es mostrava amb un scroll.
El camp s'ha canviat de lloc i es mostra com a un char evitant el scroll del númeric
- som_facturacio_comer
=> Canviar el camp teoric_maximum_consume_GC a la pestanya Facturació

som_infoenergia/wizard/wizard_add_contracts_lot.py, som_infoenergia/wizard/wizard_add_contracts_lot_view.xml
Canviar el camp `agree_tipus` (deprecated) per `tipo_medida` al wizard add_contracts_lot
S'utilitzava el camp `agree_tipus`, que està deprecated.
Ja s'utilitza el `tipo_medida` 
- `som_infoenergia`
=> Canviar el camp `agree_tipus` (deprecated) per `tipo_medida` al wizard add_contracts_lot

som_switching/tests/__init__.py, som_switching/tests/tests_wizard_import_atr_and_f1.py, som_switching/wizard/__init__.py, som_switching/wizard/wizard_import_atr_and_f1.py
Que es mantingui el nom del fitxer original quan s'importan F1s amb el wizard_import_atr_and_f1
https://trello.com/c/DqBwJiEj/5183-0-0-p26-ep259conservar-el-nom-dels-paquets-df1ns-quan-importem-per-la-porta-atr
Quan s'importavan els fitxers F1 i ATR amb el wizard_import_atr_and_f1 el nom del fitxer original es canviava
Es mante el nom del fitxer original només en el cas del F1s.
=> Overwrite _create_tmp_zip and _get_b64_zip_files methods

som_switching/tests/tests_wizard_import_atr_and_f1.py, som_switching/wizard/wizard_import_atr_and_f1.py
Treure el la referencia a la subcarpeta del nom del fitxer perque el wizard pugui trobar el fitxer temporal.
https://secure.helpscout.net/conversation/1955459970/12893351?folderId=3063374
Quan el wizard es cridat des del massive-importer el nom del fitxer conté la subcarpeta on s'ha guardat el fitxer (dia de baixada). El wizard guarda els fitxers xmls a pujar a l'erp en una carpeta temporal utilitzant el contingut del minio, no el nom del fitxer que té la subcarpeta com a part del nom. En un següent pass el wizard agafa els fitxers temporals per crear un zip i en aquesta funció si es té en compta el nom del fitxer per poder crear el zip amb el nom original, però la búsqueda del fitxer falla perquè busca una subcarpeta.
Quan es va crear el zip amb el nom original es treu el nom de la …
=> Remove subfolder from file_name and unit tests added

som_infoenergia/som_enviament_massiu.py, som_infoenergia/som_infoenergia_data.xml, som_infoenergia/som_infoenergia_enviament.py, som_infoenergia/tests/test_wizards.py, som_infoenergia/wizard/wizard_send_reports.py, som_infoenergia/wizard/wizard_send_reports_view.xml
- Poder assignar un màxim de correus que s'enviaran
- Canviar nom del wizard
- Afegir una plantilla per mort al pagador
- Setejar ondelete='set null' per poder eliminar correus associats als enviaments.
- Implementar el poweremail_unlink_callback per marcar com a Obert els enviaments si s'esborra el correu.
https://trello.com/c/y4eKLFSs/5228-0-0-p16-deadline-script-i-enviament-de-correus-mort-al-pagador-3464-contractes
- S'enviaven sempre tots els correus
- El wizard tenia un nom que generava confusió
- No es podien eliminar els correus.
- Es pot assignar un màxim de correus que s'enviaran.
- Es poden eliminar els correus de la bústia del poweremail.
=> Afegir límit correus lot per enviar i poder eliminar els correus de la bústia

.github/workflows/integration_config.yml, som_facturacio_comer/tests/tests_wizard_refund_rectify_from_origin.py
Afegir el repositori plantmeter a github actions. També instaŀlar-lo i instaŀlar el mòdul de gkwh
=> Afegir plantmeter a githubactions

som_switching/tests/tests_wizard_import_atr_and_f1.py, som_switching/wizard/wizard_import_atr_and_f1.py
Afegir F1 al nom del fitxer
https://secure.helpscout.net/conversation/1955459970/12893351?folderId=3063374
El nom del fitxer no contenia F1 i a l'hora de buscar el fitxer en el directory per pujar-lo a l'erp agafava el primer que trobés.
El fitxer es cercat considerant el tipus F1 o ATR (el zip comença amb F1 o ATR)
=> Add f1 to original file name

som_infoenergia/wizard/wizard_create_enviaments_from_object_view.xml, som_infoenergia/wizard/wizard_send_reports_view.xml
Arreglar l'error que feia que desaparegués l'acció "Afegir pòlisses a lot infoenergia/enviament"
=> FIX: ids repetits feien que desaparegués l'acció des de pòlissa

www_som/giscedata_facturacio.py
- Donar resposta a la incidència per la qual s'estaven poguent pagar des la OV factures amb residuals parcials pendents i amb estat pendent diferent a fraccionament o a Correcte.
- https://secure.helpscout.net/conversation/1974245209/13001412?folderId=3063374
- Aquestes factures es visualitzaven com "no pagada" i per tant es podía fer el pagament
- Aquestes factures es visualitzen com "en procés" i per tant no es poden donar per pagades des de la OV
=> FIX: Partial payments at OV

giscedata_facturacio_comer_som/giscedata_facturacio_report.py
Mostrar correctament el detall de Generation quan hi ha dos préstecs que aporten kwh en una factura.
https://secure.helpscout.net/conversation/1982239566/13041507/
Quan hi havia dos préstecs aportant kwh al Generationkwh, no es mostraven correctament al PDF. Sortia el total correcte però el detall només del darrer préstec.
Tant el parcial com el total surt correctament.
=> Mostrar correctament el detall de Generation quan hi ha dos préstecs.

giscedata_facturacio_comer_som/giscedata_facturacio_report.py
Que es pugui imprimir factura quan hi ha problemes per trobar el telèfon d'incidències de la distri
https://secure.helpscout.net/conversation/1993917151/13101852?folderId=3063411
Si no es trobava telèfon, no s'imprimia la factura.
Ara s'imprimeix sempre.
=> Arreglar factura quan no es troba telèfon de la distri

som_infoenergia/som_infoenergia_lot.py, som_infoenergia/tests/test_lot_enviament.py, som_infoenergia/tests/test_wizards.py, som_infoenergia/wizard/wizard_cancel_from_csv.py, som_infoenergia/wizard/wizard_cancel_from_csv_view.xml
poder cancel·lar pòlisses de baixa i emplenar amb 0 a l'esquerra el nom de les pòlisses
Incidència trobada mentre es feia la targeta: https://trello.com/c/t1ehaJPk/5277-0-0-p16-deadline-partida-enviament-de-correus-mort-al-pagador-3464-contractes
- Si la pòlissa està `active=False` no la trobava per canceŀlar-la.
- Si les pòlisses no tenen els 0 a l'esquerra no les troba. Freqüent quan l'usuària obre el CSV amb un editor per poder manipular-lo.
Es canceŀlen els enviaments de pòlisses de baixa.
No és imprescindible que els núm de pòlissa tinguin tots els 0 davant.
=> FIX: poder cancel·lar pòlisses de baixa i emplenar amb 0 a l'esquerra el nom de les pòlisses

powersms/powersms_smsbox.py, powersms/powersms_smsbox_view.xml
- Evitar que SMS amb error es quedin a la bústia de sortida
https://trello.com/c/zW7qRg1p/20-b%C3%BAstia-error-a-powersms
- Els SMS que no es podien enviar es quedaven a la bústia de sortida
- Es mouen a la nova carpeta d'error
=> Afegir carpeta on es mouen els SMS amb error

som_facturacio_comer/__terp__.py, som_facturacio_comer/giscedata_polissa_view.xml
Depèn de que el mecanisme de facturació per repercutir el preu de l'ajust del gas en tarifa fixa estigui instal·lat
Fer readonly el camp de pòlissa de `coef_repercusio_gas`, ja que nosaltres utilitzarem la llista de preus per configurar aquest nou preu. 
https://trello.com/c/hEyJMXcl/5222-0-2-p23-ep286-configurar-m%C3%B2dul-mecanismo-ajuste-gas-indexat
El camp era editable i fent scroll per sobre la fitxa era fàcil canviar-ne el valor.
El camp és readonly
=> [MAJ] Fer readonly el camp de pòlissa de `coef_repercusio_gas`

som_polissa_soci/res_partner_address.py, som_polissa_soci/tests/__init__.py, som_polissa_soci/tests/tests_partner_address.py
Es detecta un error en una situació no controlada al mòdul som_polissa_soci al realitzar un write al model ResPartnerAddress que deriva la crida a update_client_email_in_all_lists. Mentre que el paràmetre old_email ve controlat pel mètode anterior, el paràmetre email (el nou email) no. Això genera problemes ja que update_client_email_in_all_lists no esta pensada per que sigui email buit.
update_client_email_in_all_lists realitza una cerca per totes les llistes on esta subscrit el correu realitzant-ne una substitució ple correu nou. El funcionament del write llavors es:
a) buit --> nou@correu.xyz --> no fa res a mailchimp
b) antic@correu.xyz --> nou@correu.ijk --> crida a update_client_email_in_all_lists que actualitza a totes les llistes de mailchimp on apareix el correu antic …
=> Arreglar error d'adreces al mailchimp

som_crawlers/models/som_crawlers_task_step.py
- Que es guardi al `result` la informació final que dona el `wizard` d'importació. Abans es guardava un missatge intermedi que no aportava informació.
https://trello.com/c/5wTzFoGH/5369-0-0-p20-ep259-crawlers-altres-distris-de-lexcel
Exemple del missatge que es guardava abans:
Exemple del missatge que es guarda ara:
=> Guardar al resultat la informació final del wizard d'importació

som_switching/__terp__.py, som_switching/wizard/__init__.py, som_switching/wizard/wizard_close_obsolete_cases.py, som_switching/wizard/wizard_close_obsolete_cases.xml
Afegir un assistent per tancar massivament, totes les D1 01 d'autoconsum que ja no cal que s'activin (perquè la pòlissa ja té activat l'autoconsum o perquè la pòlissa està de baixa)
https://trello.com/c/aCadIruY/5425-add-versi%C3%B3-25-retard-activaci%C3%B3-auto
No hi havia aquest assitent
Hi ha aquest assistent
=> Add wizard to close obsolete ATR cases 

som_energetica/__terp__.py, som_energetica/giscedata_polissa.py, som_energetica/tests/test_som_energetica_contract.py
Quan creem una políssa amb soci d'Energètica, als partners s'els ha d'afergir la categoria Energètica. Els partners han de ser: titular, pagador, altre_p, i propietari_bank.
https://trello.com/c/NUAiUJbg/5363-0-0-p33-posar-categoria-als-clients-denerg%C3%A9tica-al-fer-una-alta-nova
No s'afegia la categoria Energètica als partners quan es creava un contracte.
S'afegeix la categoria Energètica quan es crea el contracte
=> Add category energetica when contract creation

som_switching/__terp__.py, som_switching/demo/som_switching_demo_data.xml, som_switching/giscedata_atc.py, som_switching/tests/tests_unlink_atc.py
Afegir control d'errors a l'acció de esborrar o cancel·lar casos ATC
https://trello.com/c/jFeFA0Iv/5315-0-4-p29-ep271-pollir-lassistent-de-change-state-del-m%C3%B2dul-cac-per-introduir-restriccions-al-cas-cancellareclama33
Cancel·lava casos ATC que no es podien cancel·lar 
No permet cancel·lar casos ATC
=> Afegir control d'errors a casos ATC

som_crawlers/models/som_crawlers_task_step.py, som_crawlers/tests/wizard_executar_tasca_tests.py
Support having som_crawlers workers in servers different from erp01
https://trello.com/c/p7YTCg38/5507-0-0-p27-ep259-moure-els-workers-fora-derp01
Processes downloaded files inside som_crawlers path
Processes now write everything on /tmp/outputFiles
Needs: https://gitlab.somenergia.coop/IT/massive_importer_crawlers/-/merge_requests/64
=> Support different servers

som_webforms_helpers/giscedata_polissa_tarifa.py, som_webforms_helpers/tests/test_tarifes.py
Fer un wrapper de la funció get_tariff_period per poder-la cridar amb l'erppeek
La funció no rep els paràmetres habituals de openerp, i fa que no es pugui cridar amb l'erppeek. 
S'ha creat la funció `get_period_from_date` per poder cridar la funció `get_tariff_period`
=> Wrapper per la funció get_tariff_period 

scripts/requeue_failed.py
Refer l'script de reencuat automàtic (he tornat a activar el cron). També es pot executar a mà. La idea és anar afegint/treient les cues i/o errors d'execució que volem que s'automatitzi el rencuat o l'eliminació.
Bugbuster
S'havien deixat de reencuar tots
Aquest nou escrip permet reencuar i eliminar alguns jobs, segons les constants:
- QUEUES_TO_REQUEUE: Cues que es reencuaran tots els jobs failed
- QUEUES_TO_DELETE: Cues que s'eliminaran tots els jobs failed
- EXECINFO_TO_DELETE: Resultats d'execució faileds que s'eliminaran
=> Script renquar faileds del RQ

som_infoenergia/i18n/es_ES.po, som_infoenergia/i18n/som_infoenergia.pot, som_infoenergia/som_enviament_massiu.py, som_infoenergia/som_infoenergia_enviament.py
Deute tècnic del mòdul d'infoenergia, en cas de tenir un lot d'enviament amb accent no es podien crear els fitxers i es marcaven com a enviats els correus de test
https://trello.com/c/N1QtX29b/52-enviaments-de-test-que-no-quedin-marcats-com-a-enviats
https://trello.com/c/rEA8Gayx/57-permetre-noms-de-lot-denviament-amb-accents-a-enviament-dinfoenergia
En cas de tenir un lot d'enviament amb accent no es podien crear els fitxers i es marcaven com a enviats els correus de test
Els enviaments de test no es marquen com a enviats i els noms del lot poden tenir accents
=> Fix infoenergia test emails and names with accents

.gitignore, som_crawlers/models/exceptions.py, som_crawlers/models/som_crawlers_task.py, som_crawlers/models/som_crawlers_task_step.py, som_crawlers/views/som_crawlers_config_view.xml, som_crawlers/views/som_crawlers_holiday_view.xml, som_crawlers/views/som_crawlers_result_view.xml, som_crawlers/views/som_crawlers_task_view.xml
Afegir llistat de tasques fallides sense els "SENSE RESULTATS"
https://trello.com/c/16qWOaCz/5544-0-0-p18-ep259-traca-final-somcrawlers
Només hi havia un llistat de tasques fallides, tenint en compte també els que no tenien nous resultats.
S'afegeix un llistat nou "Tasques amb resultat incorrecte"
També es refà l'estructura del menú per fer-la més similar a la resta del menús de l'ERP
> ```python                                                                      
> for result_id in O.SomCrawlersResult.search([('resultat_curt','like','SENSE RESULTATS: ')]):
>     result = O.SomCrawlersResult.browse(result_id)                                          
>     result.resultat_bool = True                                                             
> ```
=> Afegir llistat de tasques fallides sense els "SENSE RESULTATS"

som_crawlers/__terp__.py, som_crawlers/data/som_crawlers_step_data.xml, som_crawlers/data/som_crawlers_task_data.xml, som_crawlers/models/som_crawlers_task_step.py
- Afegir `data` pel nou _crawler_ d'Iberdrola T1 
- Gestionar correctament les excepcions que salten quan es crida el _wizard_ d'importació
https://trello.com/c/16qWOaCz/5544-0-0-p18-ep259-traca-final-somcrawlers
- No hi havia el nou _crawler_
- No es marcava com error quan fallava la importació
- Afegida la `data` del nou _crawler_
- Es marca com error quan salta una excepció durant la importació
- S'han substituït alguns `has_key()` (_deprecated_) per `in`
=> Afegir Iberdrola T1 crawler i gestionar excepcions durant la importació

som_crawlers/models/som_crawlers_task_step.py
- Arreglar les _screenshots_, no s'estaven guardant.
https://secure.helpscout.net/conversation/2090253310/13855099?folderId=3063374
- Al repositori `massive_importer_crawlers` s'ha canviat el _path_ de la _screenshot_ i a `som_crawlers` no s'estava construint correctament.
- Busquem les _screenshots_ al _path_ correcte.
=> Fix path to screenshots

account_account_som/__init__.py, account_account_som/account_payment_term.py
Forçar dia de pagament al model terminis de pagament ja que és necessari en el moment de crear una factura i definir la data de venciment.
https://secure.helpscout.net/conversation/1347799277/7100531/
https://sentry.somenergia.coop/organizations/som-energia/issues/127319/?project=11&query=is%3Aunresolved+%21logger%3Aopenerp.web-services
Es bloquejava la facturació si tenien un termini de pagament sense dia definit
No es poden crear nous terminis de pagament (o modificar els actuals) sense tenir-los definits
=> Forçar dia de pagament al model terminis de pagament

account_account_som/account_payment_term.py
Arrreglar el bug introduit en la PR https://github.com/Som-Energia/openerp_som_addons/pull/267 que evitava que es pogués eliminar un termini de pagament. També facilitar la creació de terminis de pagament amb el default de dia de pagament.
https://secure.helpscout.net/conversation/1347799277/7100531/
https://sentry.somenergia.coop/organizations/som-energia/issues/127319/?project=11&query=is%3Aunresolved+%21logger%3Aopenerp.web-services
=> Bug no poder eliminar un termini de pagament

som_switching/wizard/wizard_create_r1.py
selecció automàtica de tipus de reclamant al wizard de creació de R1 segons canal seleccionat al wizard de creació de cas ATC previ
https://trello.com/c/DSEDeSON/5537-0-4-p0-automatitzar-que-la-pestanya-de-reclamant-client-agafi-les-dades-de-client-ruta-1
no es selecciona automàticament el tipus de reclamant
es selecciona automàticament el tipus de reclamant segons el tipus de canal seleccionat previament
=> selecció automàtica de tipus de reclamant al wizard de creació de R1 segons canal al wizard de creació de cas ATC

giscedata_facturacio_comer_som/giscedata_facturacio_report.py, giscedata_facturacio_comer_som/i18n/es_ES.po, giscedata_facturacio_comer_som/i18n/giscedata_facturacio_comer_som.pot, giscedata_facturacio_comer_som/report/components/energy_consumption_graphic_td/energy_consumption_graphic_td.mako
Afegir el consum mitjà per codi postal a la factura en pdf segons RDL 18/2022
https://trello.com/c/VMD1un0k/5541-0-2-p16-testeig-i-posar-a-productiu-modificar-pdf-per-aplicaci%C3%B3-real-decreto-ley-18-2022-de-18-de-octubre-part-2-3
No es mostrava la informació
Es mostra el consum mitja si n'hi ha
=> Afegir consum mitjà per codi postal a la factura en pdf

som_polissa/giscedata_polissa.py, som_switching/giscedata_switching_helpers.py
Asignar por defecto el grupo de pago ENGINYERS al copiar una póliza o al cambiar de titular por subrogación.
https://trello.com/c/IspdKAn6/5594-0-0-p12-no-copiar-grup-de-pagament-en-canvis-de-titular
En copiar-se una pòlissa per traspàs o fer una modcon per subrogació es posa per defecte el grup de pagament a ENGINYERS
=> Asignar grupo de pago por defecto cuando se modifica el titular de la póliza.

giscedata_facturacio_comer_som/giscedata_facturacio_report.py, giscedata_facturacio_comer_som/tests/tests_FacturacioFacturaReport_some.py
El càlcul de l'energia total consumida a l'any surt malament a la factura en pdf
https://secure.helpscout.net/conversation/2134756504/14119771?folderId=3063409
https://secure.helpscout.net/conversation/2129795517/14097235?folderId=3063409
Barreja els consums de P1, P2, P3, P4, P5 i P6 amb els procedents de les línies d'ajust del Mag
Filtra les línies del mag deixant només P1, P2, P3, P4, P5 i P6
=> Fix Error de càlcul al pdf de factura a l'energia total consumida les últims 12 mesos

scripts/reimport_som_crawlers_zips.py, scripts/run_all_som_crawlers_tasks.py, som_crawlers/models/som_crawlers_task_step.py, som_crawlers/tests/wizard_executar_tasca_tests.py
Script per reimportar resultats incorrectes dels crawlers que tinguin adjunts baixats
https://trello.com/c/lsDWiIaG/5573-0-8-p15-ep259-get-somcrawlers-escombrada-df1s
S'havien de reimportar a mà
Es reimporten automàticament després de passar els crawlers
=> Script per reimportar resultats incorrectes dels crawlers que tinguin adjunts baixats

som_account_invoice_pending/update_pending_states.py
Que es pugui executar el canvi d'estats pendents
https://sentry.somenergia.coop/organizations/som-energia/issues/127504/events/fb5a01201ec34c55808e17618de97b67/?project=11&query=is%3Aunresolved
Petava current_state_id = fact_obj.read(cursor, uid, factura_id, ['pending_state'])['pending_state'][0] perquè factura_id era una llista
No peta
=> Fix waiting for annex cancelled contracts

som_facturacio_comer/wizard/wizard_informe_factures_dades_desagregades.py
Mostrar les columnes per excedents totals i compensats a l'informe de factures desagregades
https://secure.helpscout.net/conversation/2098625739/13901223?folderId=3063374
No teniem les dades
tenim les dades
=> Afegir les columnes d'excedents de generació per tipus al informe de factures desagregades

som_crawlers/models/som_crawlers_task.py
No assignar data de pròxima execució quan un `crawlers` ha fallat i no s'ha apretat a descarregar. Això farà que el següent `cron` el torni a executar.
https://trello.com/c/6NrjZLRm/5623-0-6-import-massiva-avan%C3%A7ar-la-data-dexecuci%C3%B3-quan-sha-fet-click-a-desc%C3%A0rregar-ep259-m
Sempre s'assignava data de pròxima exeució.
No s'assigna data de pròxima execució quan un `crawlers` ha fallat i no s'ha apretat a descarregar.
=> Add conditional to not schedule next execution in some cases

som_account_invoice_pending/tests/update_pending_states_tests.py, som_account_invoice_pending/update_pending_states.py
Afegir una línia a la informació addicional de la factura quan s'enviï el correu i l'SMS "previ advocats". Facilita saber que s'ha fet aquest enviament.
https://trello.com/c/MPvKgaDX/5577-0-1-p16-nota-other-info-correu-i-sms-previ-advocats
No hi havia una manera ràpida de saber si s'havia enviat l'SMS i el correu.
S'afegeix una línia a "Informació addicional" que ens permet veure-ho fàcilment.
=> Add comment to invoice when email and SMS are sent

som_infoenergia/wizard/wizard_cancel_from_csv.py
Protegir el wizard de cancel·lar des de csv per evitar que puguin cancel·lar sense raó i evitar que el codi (que dona per fet que raó te valor) doni error.
https://secure.helpscout.net/conversation/2151086551/14202714?folderId=3063374
Al intentar cancel·lar sense posar una raó donava error
No permet continuar sense una raó
=> Enviaments massius, fer requrit el camp raó al wizard de cancelar des de csv

giscedata_facturacio_comer_som/giscedata_facturacio_report.py
Mostrar la dada correcta de € per la part d'energia al resum de la factura al pdf de la factura quan es tracta de factures amb generation kwh i mag per l'error del camp calculat total_energia (stored) de la factura mentre no s'arregla via la pr https://github.com/gisce/erp/pull/15723
https://secure.helpscout.net/conversation/2113034573/13992164?folderId=3063374
Es mostra una dada de total_energia incorrecta
Es calcula la dada en comptes de utilitzar el camp calculat stored
=> arreglar el total d'energia de la factura en pdf al resum

som_facturacio_switching/giscedata_facturacio_importacio_linia_view.xml
Mostrar les camps de cerca de la vista de llista, nota, les select a la definició del tree sonignorats per l'erp, s'han de posar a la definició del form.
https://secure.helpscout.net/conversation/2136758466/14136618?folderId=3063374
no es mostren els camps de cerca
es mostren els camps de cerca
-som_facturacio_switching o carregar el xml de de l'assistent
=> mostrar els camps de cerca per autoconsum pòlissa i tarifa al al vista de llista de "fitxers F1 importats"

som_facturacio_comer/giscedata_lectures_view.xml
Afegir la pòlissa a la vista de comptadors de la pòlissa (redundant?) permet accedir a una sèrie de menus d'un sol click.
https://secure.helpscout.net/conversation/2098591988/13901202?folderId=3063374
no es mostrava
es mostra
som_facturacio_comer
=> Afegir la columna de polissa a la vista de comptadors

som_switching/__terp__.py, som_switching/security/ir.model.access.csv, som_switching/tests/__init__.py, som_switching/tests/tests_wizard_validate_d101.py, som_switching/wizard/__init__.py, som_switching/wizard/wizard_validate_d101.py, som_switching/wizard/wizard_validate_d101_view.xml
Moure wizard_validate_d101 a som_switching.
Afegir funcionalitat necessaria per a tractar D1 01 amb motiu 06 (ATR 3.0)
Amb el canvi de formats V.3.0 la distribuïdora ens pot enviar un D1 01 motiu 06. En aquest cas s'ha de crear:
D1 02 Acceptat/Tancat (si no ha estat rebutjat)
Si el contracte ja té auto col·lectiu (42 i 43): li demanem al titular que hi ha un canvi en l'acord de repartiment i cal fer una M (s)(R)
https://trello.com/c/QK6qXM8F/5543-p3-ep287-wizard-generaci%C3%B3-m-tipus-s-acord-repartiment-i-pantalles-ov-per-la-d1-01-motiu-06
El wizard estava al repositori de GISCE.
No tractava el motiu 06
Wizard mogut a som_switching
Tracta el motiu 06
som_switching
=> Update distribution agreement som

som_polissa_condicions_generals/i18n/es_ES.po, som_polissa_condicions_generals/i18n/som_polissa_condicions_generals.pot, som_polissa_condicions_generals/report/condicions_particulars.mako
Canviar la formula que apareix a les condicions particulars dels contractes amb indexada de PA a PTD ja que a la documentació ja s'ha canviat.
https://secure.helpscout.net/conversation/2156660271/14249074?folderId=3063374
surt PA
surt PTD
- som_polissa_condicions_particulars
=> Canviar la formula de les condicions particulars de PA a PTD

som_crawlers/models/som_crawlers_task_step.py, som_crawlers/tests/wizard_executar_tasca_tests.py
- Evitar que s'adjuntin fitxers antics que no s'hagin eliminat per algun motiu
- Evitar que quedin _screenshots_ sense esborrar quan no s'han trobat resultats
https://trello.com/c/bTRtHbQO/5655-0-6-import-massiva-arreglar-2-zips-adjunts-ep259-m
- Si hi havia fitxers antics al directori d'un `crawler` es penjaven tots provocant importacions duplicades
- Quan no es trobaven resultats es feia una captura, però no s'ajuntava ni s'eliminava
- No adjuntem fitxers antics i donem informació sobre ells a la sortida
- S'esborren les captures generades per una excepció de sense resultats
=> Fix screenshots not being deleted and do not attach old files

som_switching/giscedata_switching_helpers.py
Que quan s'importa un R102 de rebuig o finalitzador, que es tanqui el CAC si està marcat "Tancar CAC al finalitzar R1"
https://trello.com/c/8XDB2q0k
No es tancava
Ara es tanca
=> Tanca CAC al rebre R102 finalitzador o de rebuig

som_switching/wizard/wizard_create_r1.py
Evitar detalls de reclamacions buides (sense factura associada) en un R101.
https://secure.helpscout.net/conversation/2177022947/14332289?folderId=3063374
Al crear CAC a partir de factures tipus R, es creaven detalls de reclamació buits, o sense factura, vinculats al pas de l'ATC resultant. Això provocava molta pèrdua de temps corregint-ho per poder comunicar-ho a la distribuïdora.
Evitem la creació de detalls de reclamació buits, o sense factura, vinculats al pas de l'ATC.
=> Unlink R101 claim when no invoice related

som_polissa_condicions_generals/report/condicions_particulars.mako
modificar SobrecostesREE per SC i Interrump per I a la formula d'indexada de les dades de contracte
https://secure.helpscout.net/conversation/2156660271/14249074
es mostra la formula així:
la formula es mostra així:
=> modificar SobrecostesREE per SC i Interrump per I a la formula d'indexada

som_polissa_condicions_generals/report/condicions_particulars.mako
Amb l'entrada de la tarifa indexada a contractes en general, cal mostrar la k al document de condicions particulars quan aquesta ve definida per tarifa i no directament a polissa.
https://secure.helpscout.net/conversation/2193623551/14450458
es mostrava la k de la pòlissa que sol ser 0
es mostra la k de tarifa associada si a la pòlissa no esta definida o es 0
=> Mostrar la k correcta a condicions particulars per polisses amb k definida per tarifa

som_extend_facturacio_comer/giscedata_facturacio_view.xml
Que la columna 'additional information' aparega al final del tree, ja que al poder contindre molta info, obliga a fer scroll horitzontal per veure altres columnes més importants.
https://secure.helpscout.net/conversation/2212267401/14649801?folderId=3063379
Apareixia abans a meitat del tree.
Apareix al final del tree.
=> Ficar la columna 'additional information' al final del tree de facturas de cliente

giscedata_facturacio_comer_som/giscedata_facturacio_report.py, giscedata_facturacio_comer_som/i18n/es_ES.po, giscedata_facturacio_comer_som/i18n/giscedata_facturacio_comer_som.pot, giscedata_facturacio_comer_som/report/components/invoice_details_td/invoice_details_td.mako, giscedata_facturacio_comer_som/report/components/invoice_details_td_bo_social_2023/invoice_details_td_bo_social_2023.mako, giscedata_facturacio_comer_som/report/components/invoice_summary_td/invoice_summary_td.mako
Afegir el bo social de 2023 a la factura en pdf mitjançant una entrada nova al bloc de línies de factura i al resum
https://trello.com/c/SyB5AVYW/4326-pintar-fila-bo-social-al-pdf-factura
No es mostrava i apareixia en secció altres conceptes
No es mostra en secció d'altres conceptes
Es mostra en un bloc específic
Es mostra al resum de la factura inicial separadament
- giscedata_facturacio_comer_som
=> Afegir bo social 2023 a la factura en pdf

som_account_invoice_pending/account_invoice_pending_view.xml
Menejar camps  'pending_state' i 'pending_state_date' a la part de filtres que apareixen a la part sense desplegar.
https://secure.helpscout.net/conversation/2215432371/14666504?folderId=7422776
Calia donar-li al '+' per a poder filtrar per eixos camps.
Apareix a la part sense desplegar.
=> Prioritzar camps filtre en trees de factures

som_switching/demo/som_switching_demo_data.xml, som_switching/wizard/wizard_validate_d101_view.xml
Permetre que els tests de `som_switching` s'executin.
Es feia servir un menú que ja no existeix a `developer` de GISCE. També hi havia errors en la _demo data_.
Es fa servir el menú `giscedata_cups.menu_autoconsum` i s'arreglen errors en la _demo data_.
=> Fix menu_autoconsum parent id model

som_infoenergia/wizard/wizard_create_enviaments_from_csv.py, som_infoenergia/wizard/wizard_create_enviaments_from_csv_view.xml, som_inversions/report/__init__.py, som_inversions/report/report_retencions_interessos_apo.mako, som_inversions/report/report_retencions_interessos_apo.py, som_inversions/report/report_retencions_interessos_titols.mako, som_inversions/report/report_retencions_interessos_titols.py, som_inversions/som_inversions_data.xml, som_inversions/som_inversions_report.xml
Enviar els certificats de l'IRPF 2022 per a les aportacions al capital social i els títols.
https://trello.com/c/OY6FCnMU/5720-enviament-certificats-irpf-aportacions
No es podien enviar.
- Creades dues noves plantilles, una per les aportacions al capital social i una altra pels títols.
- Creats dos nous reports, un per les aportacions al capital social i un altre pels títols.
- Afegida l'opció de crear enviaments a un lot d'enviaments massiu per CSV amb números de partner.
=> Afegir adjunt pel certificat de l'IRPF de les aportacions i títols

som_facturacio_switching/giscedata_facturacio_importacio_linia.py, som_facturacio_switching/giscedata_facturacio_switching_cron.xml
- Millorar la reimportació dels fitxers F1 amb error
https://trello.com/c/wx1666Mk/5746-0-6-get-analitzar-cron-per-reimportar-f1s-a-la-nit
- Es reimportaven els fitxers F1 en estat erroni amb uns codis d'error concrets
- S'han afegit més codis d'error que han de ser reimportats
- Es reimporten també els fitxers F1 en fase 1 que no tinguin estat erroni o incident
=> Add more error codes and reimport phase 1 f1s

som_indexada/data/email_template_data.xml, som_infoenergia/__terp__.py, som_infoenergia/security/ir.model.access.csv, som_infoenergia/som_enviament_massiu.py, som_infoenergia/wizard/__init__.py, som_infoenergia/wizard/wizard_create_attachments_from_zip.py, som_infoenergia/wizard/wizard_create_attachments_from_zip_view.xml
- Poder adjuntar fitxers externs a l'ERP a enviaments massius d'un lot
- Es necessita per les comunicacions del canvi massiu de K's en pòlisses amb indexada
https://trello.com/c/pzhhI7Mo/5749-ep288-canviar-les-k-personalitzades-de-manera-massiva
- No es podien afegir adjunts de fora l'ERP en els enviaments massius d'un lot
- Hi ha un _wizard_ en els lots que permeten afegir adjunts als enviaments massius a partir d'un ZIP
- S'afegeix l'adjunt als enviaments que tenen pòlissa si hi ha un fitxer amb el nom: `contracte_<numero_polissa>.pdf`
- Al fer l'enviament, si l'enviament massiu té un adjunt s'afegeix al correu
=> Permetre adjunts en els enviaments massius d'un lot

giscedata_facturacio_comer_som/giscedata_facturacio_report.py, giscedata_facturacio_comer_som/i18n/es_ES.po, giscedata_facturacio_comer_som/i18n/giscedata_facturacio_comer_som.pot, giscedata_facturacio_comer_som/report/components/contract_data_td/contract_data_td.mako, giscedata_facturacio_comer_som/report/components/invoice_details_td_energy/invoice_details_td_energy.mako
modificar texts a les factures en pdf quan es tracta de factures amb tarifa indexada
https://trello.com/c/5sDMtoF6/5765-gegc-ep288-canviar-dues-frases-del-pdf-factura-amb-tarifa-indexada
No es mostrava correctament
Es mostra el text de preu mitjà quan es una tarifa indexada i s'escurça de "tarifa comercialitzadora" a "tarifa"
- giscedata_facturacio_comer_som
=> Canvis al pdf de la factura per tarifes indexades

som_crawlers/data/som_crawlers_config_data.xml, som_crawlers/models/som_crawlers_task.py
- Evitar que hi hagi errors no detectats
- Evitar errors en el `crawler` SCQ
https://secure.helpscout.net/conversation/2279801144/15097598/
- Només es marcava el resultat com erroni si la excepció era en el primer pas
- El nom de la configuració de la tasca SCQ no concordava amb el del `crawler`
- Es marca el resultat com a erroni també si falla en un pas que no sigui el primer
- Els noms del `crawler` SCQ concorden
=> Fix som_crawlers errors not being detected

som_polissa/__init__.py, som_polissa/__terp__.py, som_polissa/som_polissa_webforms_helpers.py, som_polissa/tests/__init__.py, som_polissa/tests/som_polissa_demo.xml, som_polissa/tests/som_polissa_webforms_helpers_tests.py
S'estaven cridant unes funcions molt antigues pel canvi de compte que no estaven mantingudes.
Amb aquest codi es crida l'assistent estàndard el qual sí que està mantingut.
També fa que hi hagi coherència amb el canvi de compte ja que des de la OV sempre es modificava la última modificació contractual i des de l'ERP es feia una nova modificació contractual
https://trello.com/c/hbNjo0oy/5772-refactor-endpoint-de-canvi-compte-bancari-des-de-lov
Mateix comportament però modificava la modcon vigent del contracte
Es crea una nova modcon al contracte
=> Refactor del codi de canvi de compte

www_som/__terp__.py, www_som/giscedata_polissa.py, www_som/tests/tests_polissa.py
Afegir "helper" per comprovar si es pot modificar el contracte
https://trello.com/c/pLkgUKbJ/5769-ep288-implementar-validador-de-modcon-pendents-per-a-lov
La OV no comprobaba si hi havia alguna modificació pendent abans de fer una modificació
Ara ho comprova
=> Afegir "helper" per comprovar si es pot modificar el contracte

som_facturacio_switching/__init__.py, som_facturacio_switching/__terp__.py, som_facturacio_switching/giscedata_facturacio_importacio_linia.py, som_facturacio_switching/giscedata_facturacio_switching_cron.xml, som_facturacio_switching/security/ir.model.access.csv, som_facturacio_switching/som_error_cron_f1_reimport.py, som_facturacio_switching/som_error_cron_f1_reimport_data.xml, som_facturacio_switching/som_error_cron_f1_reimport_view.xml, som_facturacio_switching/wizard/__init__.py, som_facturacio_switching/wizard/wizard_change_cron_reimport_days.py, som_facturacio_switching/wizard/wizard_change_cron_reimport_days_view.xml
Dotar al ET de l'eina per poder controlar que reimporta el cron de reimportació de f1's nocturn
https://trello.com/c/wx1666Mk/5746-0-4-get-permetre-gestionar-els-errors-que-es-reimporten-amb-el-cron-per-reimportar-f1s-a-la-nit
Edició de variable complexa i requereix permisos d'administració
Model amb vistes que permet la seva modificació per part de les persones del ET
-  som_facturacio_switching
=> Nou model per gestionar el comportament del cron de reimportació de F1's

som_indexada/data/product_pricelist_data.xml, som_indexada/exceptions/indexada_exceptions.py, som_indexada/migrations/5.0.2.108/pre-0001_pricelist_indexada_peninsula_semantic_id_creation.py, som_indexada/som_indexada_webforms_helpers.py, som_indexada/wizard/wizard_change_to_indexada.py
If a contract has a non-standard tariff, changing it from webforms should not be allowed. It must be done by our staff on the erp client.
https://secure.helpscout.net/conversation/2299177058/15197723?folderId=3063450
El bloqueig es feia des de formulari d'una forma molt fragil: fent servir el fet que les tarifes standards tenen el numero del peatge al nom. Es un mecanisme feble davant de canvis de noms de tarifes. A més hi ha molts punts d'entrada (4) a la interficie d'usuari on fer aquest control.
- Fem servir la funció de l'erp que determina si el canvi de tarifa es factible
- Cridem a una nova funció que determina si la tarifa es standard o no. Es standard si es una de les tarifes de desti.
- Afegim un parametre opcional per dir que faci aquesta restricció i el setejem nomes quan es …
=> Add only standard prices from indexed form without exceptions

powersms/__init__.py, powersms/__terp__.py, powersms/migrations/5.0.23.1.0/post-0001-set_lleidanet_provider_for_existing_acc.py, powersms/powersms_core.py, powersms/powersms_core_view.xml, powersms/powersms_provider.py, powersms/powersms_provider_data.xml, powersms/powersms_provider_lleidanet.py, powersms/powersms_smsbox.py, powersms/powersms_smsbox_view.xml, powersms/powersms_template_view.xml, powersms/powersms_templates.py, powersms/security/ir.model.access.csv, powersms/tests/__init__.py, powersms/tests/test_powersms_coding_validation.py, powersms/wizard/wizard_send_sms.py
Afegir el camp proveïdor als comptes de powersms
Delegar la logica d'enviar sms al proveïdor per fer el codi més generic
Afegir suport per reports y adjunts
=> (IMP) powersms

som_facturacio_comer/giscedata_facturacio_validation.py
En el marc de la targeta https://trello.com/c/1IuYsmUo/113-gea-validaci%C3%B3-retroactiva-excedent-vs-pot%C3%A8ncia-generaci%C3%B3-en-contractes-dauto , cal afegir la capacitat d'executar una validació de factura en esborrany aïllada sobre una factura qualsevol.
https://trello.com/c/1IuYsmUo/113-gea-validaci%C3%B3-retroactiva-excedent-vs-pot%C3%A8ncia-generaci%C3%B3-en-contractes-dauto
No es poden executar validacions de factures en esborrany aïllades des de script
Es permet executar una validació qualsevol sobre una factura qualsevol obtenint-ne el resultat.
=> Afegir la capacitat d'executar una validació de factura en esborrany isolada sobre una factura qualsevol

som_polissa/giscedata_polissa_view.xml
Baixar prioritat de la nova vista "Polisses per CAU" perquè no sobrescrigui el llistat de Pòlisses general quan es fa CTRL+F al llistat de pòlisses.
https://github.com/Som-Energia/openerp_som_addons/pull/367
https://secure.helpscout.net/conversation/2325928928/15351338?folderId=3063374
Quan es feia CTRL+F al llistat de pòlisses, sortia el llistat per CAU.
Quan es fa CTRL+F al llistat de pòlisses, sort el llistat de pòlisses general.
=> Canvi prioritzat llistat polissa cau per no sobrescriure cerca polissa general

giscedata_facturacio_comer_som/giscedata_facturacio_report.py, giscedata_facturacio_comer_som/i18n/es_ES.po, giscedata_facturacio_comer_som/i18n/giscedata_facturacio_comer_som.pot, giscedata_facturacio_comer_som/report/components/invoice_details_td/invoice_details_td.mako, giscedata_facturacio_comer_som/report/components/invoice_details_td_flux_solar/invoice_details_td_flux_solar.mako, giscedata_facturacio_comer_som/report/components/invoice_details_td_other_concepts/invoice_details_td_other_concepts.mako, giscedata_facturacio_comer_som/report/components/invoice_summary_td/invoice_summary_td.mako
✨ Afegir Flux Solar parametres a factura PDF
https://trello.com/c/TXrO8szp/124-bateria-canviar-text-pdf-per-l%C3%ADnia-descompte-flux-i-del-resum-de-la-factura
No hi era
Hi és
=> ✨ Afegir Flux Solar parametres a factura PDF

som_switching/__init__.py, som_switching/giscedata_switching_m1.py
Evitar copiar la categoria "Pobresa energètica" i aquelles que estiguin vinculades al titular en concret a la nova pòlissa en fer un canvi de titular.
https://trello.com/c/mQ5avx60/139-canvi-de-titular-contractes-categoria-pobresa-energ%C3%A8tica-que-el-nou-contracte-no-agafi-la-categoria
Es copiaven totes les categories.
No es copia cap categoria i llavors s'assignen les d'EiE.
=> 👔 Remove contract categories on owner change

som_account_invoice_pending/__terp__.py, som_account_invoice_pending/data/custom_search_data.xml, som_account_invoice_pending/tests/update_pending_states_tests.py, som_account_invoice_pending/update_pending_states.py
Automatizar l'avançament d'estat a avís impagament confirmat de les factures en estat consulta pobresa que no compleixen els requisits
https://trello.com/c/GpYXKCTM/138-automatitzar-procediments-i-c%C3%A0rrega-de-dades-a-factures-client-amb-deute-per-facilitar-gestions-de-pobresa-energ%C3%A8tica
S'havien d'avançar manualment les factures que estaven en estat pendent consulta pobresa
Es passen les factures que no compleixen els requisits de consulta pobresa al següent estat
=> Pobresa state into impagament confirmat automatized

som_facturacio_comer/giscedata_facturacio.py, som_facturacio_flux_solar/__init__.py, som_facturacio_flux_solar/__terp__.py, som_facturacio_flux_solar/giscedata_bateria_virtual.py, som_facturacio_flux_solar/giscedata_bateria_virtual.xml, som_facturacio_flux_solar/giscedata_bateria_virtual_origen.py, som_facturacio_flux_solar/giscedata_bateria_virtual_origen.xml, som_facturacio_flux_solar/giscedata_bateria_virtual_percentatges_acumulacio.py, som_facturacio_flux_solar/giscedata_bateria_virtual_percentatges_acumulacio_data.xml, som_facturacio_flux_solar/giscedata_bateria_virtual_polissa.py, som_facturacio_flux_solar/migrations/5.0.23.9.0/post-0001_flux_solar_inici.py, som_facturacio_flux_solar/security/ir.model.access.csv
Varies millores sobre la bateria virtual
Afegir accions des del llistat de bateries virtuals
- Comprovar nous descomptes
- Poder activar descomptes per tots els contractes
- Anar a la vista “Contractes”
- Anar a la vista “Descomptes de la Bateria Virtual”
- Poder anar a la vista “Origens”
Afegir noves columens en el llistat de bateries virtuals
- origen
- receptor + pes
- data creacio bateria (es fa generic)
- data inici descomptes
El desplegable “gestió de l’acumulació” només ha de permetre l’opció de “Acumular saldo excedents”, treure les altres opcions.
A "Gestió de l'acumulació", si marquem l'opció "Acumular saldo d'excedents (percentatge)", veurem com es mostra una nova taula amb els percentatges d'acumulació.
Aquests tenen una data inici, una data fi i un perentatge (numero del 0 al …
=> [Bateria Virtual] - Accions i columnes llistat + Modificacions Origen + Percentatges Acumulacio

som_facturacio_comer/wizard/__init__.py, som_facturacio_comer/wizard/wizard_afegir_contracte_bateria_virtual.py
Impedir que una bateria virtual tingui més d'un origen.
https://trello.com/c/2TL95Ww6/5732-bateria-t02-millores-en-lassistent-afegir-p%C3%B2lissa-a-la-bateria-des-de-la-p%C3%B2lissa
Una abteria virtual podia tenir més d'un origen.
Des de l'assitent d'afegir polissa a bateria virtual es controla que una polissa no pugui tenir més d'un origen.
https://github.com/gisce/erp/pull/17179
=> Validacions custom assistent bateria virtual

som_polissa/migrations/5.0.23.9.0/post-0001_rename_category_desestiment.py
Corretgir un script de migració de som_polissa que carregava un data del mòdul que no tocava. Introduït a la pr #421 
N/A
No passava el script
Ara passa el script
- som_polissa
=> FIX d'script de migració per a som_polissa

som_polissa/migrations/5.0.2.108/pre-0002_put_hidden_flux_solar_polissa_category_as_semantic_id.py, som_polissa/som_polissa_data.xml
Co-authored-by: Daniel Estanyol i Torres <daniel.estanyol@somenergia.coop>
Co-authored-by: Pau Boix <pau.boix@somenergia.coop>
Crear una categoria de pòlissa per marcar les polisses amb incidència de lectures de generació per que a la OV no surtin els sols del flux solar fins que no s'arregli la cagada de distri.
https://trello.com/c/05gWxB1o/165-bateria-crear-categoria-flux-solar-ocult-ov
No existia
Existeix
som_polissa - pre-0002_put_hidden_flux_solar_polissa_category_as_semantic_id
=> create the semantic id for the hidden flux solar category

som_polissa_condicions_generals/report/condicions_particulars.mako
Arreglar error que no permetia imprimir el contracte en alguns casos on el mètode de pagament no és per domiciliació bancària.
Incidència detectada en l'enviament massiu de les noves condicions pel Flux Solar.
- Hi havia codi que provocava errors que no es fa servir des de la següent PR:  #411 
- S'intenta obtenir l'IBAN en casos on no existeix
- S'elimina codi antic
- S'afegeix condicional per evitar mostrar el bloc de pagament quan no hi ha les dades
=> Fix bank details error in contract report

som_facturacio_flux_solar/giscedata_polissa.py
Modificació de mètode per a obtenir la data d'inici del flux solar de cares a calcular descomptes
https://trello.com/c/OZ4LLGAe/5864-bateria-activaci%C3%B3-a-test-del-flux-solar-a-les-p%C3%B2lisses?filter=label:GISCE
Comportament estàndard
S'agafa la data d'inici del càlcul de descomptes ja que es una data més adient pel comportament dessitjat.
=> Modificació de mètode per a obtenir la data d'inici del flux solar de cares a calcular descomptes

som_crawlers/data/som_crawlers_config_data.xml
Fer servir `chrome` a tots els crawlers tal com es fa a producció.
Els fitxers `data` definien les configuracions dels crawlers amb el navegador `firefox`.
Els fitxers `data` defineixen les configuracions dels crawlers amb el navegador `chrome`.
=> Change crawlers browser to chrome

giscedata_facturacio_comer_som/giscedata_facturacio_report.py
Es detecta una casuística per la qual un QR de la factura no es mostrava tot i que que es podia generar
Iniciativa pròpia
S'amagava el QR si no hi havien lectures de maxìmetre tot i que no son obligatòries per generar-ho
Es mostra el QR sempre que es generi
=> Mostar el qr de la factura sempre que sigui possible

som_switching/wizard/wizard_create_atc_from_polissa.py, som_switching/wizard/wizard_create_atc_from_polissa.xml
Afegir l'opció d'etiquetes per contractes cobraments i reclama
https://trello.com/c/hc1UqZwv/267-fer-visible-camp-i-model-per-etiquetatge-de-cacs-per-contractes-cobraments-i-reclama
Només podia utilitzar factura les etiquetes
També contractes cobraments i reclama
=> allow tags for contracts cobraments and reclama

som_indexada/wizard/wizard_change_to_indexada.py
Que quan es faci un canvi a indexada amb una de les posicions fiscals noves de canaries (les del 2.5) es realitzi correctament al selecció de tarifa desitjada.
https://secure.helpscout.net/conversation/2506145314/16467991
Realitzava el canvi de tarifa malament, es genera una mod contractual apuntant a una tarifa incorrecta
Es realitza correctament
=> Afegir els identificadors per les noves posicions fiscals de canaries al wizard de canvi cap a indexada

som_crawlers/models/som_crawlers_task_step.py
Permetre importar zips encara que els distris ens posin fitxers zip erronis o mal-formats dins P.Ex: zips amb mida 0
Bugbusting diari, repàs de crawlers, distri pitarch
Fallava i no extreia els xml
Extreu els xml que pot
=> Permetre importar Zips de distris quan estan plen amb zips mal-formats

som_polissa_condicions_generals/report/condicions_particulars.mako
Ens hem adonat que la variable force_pricelist que es passa per context al get_atr_price  ha de ser un enter, i no un browse. https://github.com/gisce/erp/pull/16759
Fent la targeta del canvi de versió: https://trello.com/c/tUJH4zmT/5867-versi%C3%B3-nova-erp-previ?filter=member:oriolpiera
PR Origen: https://github.com/Som-Energia/openerp_som_addons/pull/391
No s'imprimien els contractes a pre-producció
S'imprimeixen els contractes
=> 🐛 Paràmetre per ctx de force_pricelist com a enter en comptes de browse

som_facturacio_comer/giscedata_facturacio_contracte_lot_view.xml, som_facturacio_comer/migrations/5.0.24.5.0/post-0001_load_views_contracte_lot_tree.py
Corretgir herència de vista tree de contracte lot per substitució del camp status a la v23.9
Requereix v23.9 o tenir aplicada la PR de Gisce https://github.com/gisce/erp/pull/16838
https://trello.com/c/tUJH4zmT/5867-versi%C3%B3-nova-erp-previ
Raise per mala herència de vistes
Correcció de camp referenciat
- som_facturacio_comer
- post-0001_load_views_contracte_lot_tree
=> FIX Vista heretada de contracte lot a v.23.9

som_polissa/giscedata_cups_view.xml, som_polissa/migrations/5.0.24.5.0/post-0001_makes_cups_autoconsum_not_read_only.py
Fer que l'històric d'autoconsum sigui modificable
https://trello.com/c/0LH8fgDE/6027-modificar-data-hist%C3%B2ric-autoconsum
Era readonly
Ja no és readonly
- som_polissa
- post-0001_makes_cups_autoconsum_not_read_only.py
=> Fer que l'històric d'autoconsum sigui modificable

som_facturacio_comer/giscedata_polissa_view.xml, som_facturacio_comer/migrations/5.0.23.6.0/post-0004_remove_coef_gas_readonly.py
Com que s'ha tret aquest camp de la vista, ja no cal sobreescriure'l per fer-lo readonly
[Incidència](https://secure.helpscout.net/conversation/2538384861/16747990?folderId=7850674)
Es sobrescrivia el camp coef_repercusio_gas de polissa per fer-lo de només lectura
No es sobrescriu perquè ja no existeix
=> Treure inherit coef gas

som_autoreclama/migrations/5.0.2.108.0/post-0001_set_inital_history_polissa_state.py
Desactivar l'script de migració per evitar problemes
Cap
La migració dona de alta totes les polisses en autoreclama i pot provocar un allau de reclamacions i l'equip de reclama no pugui fer-ne front
no es fa la migració, hi han scripts al scriptlauncher per tal de fer-ho en blocks.
=> desactivar script de migració que pot donar problemes

som_polissa/giscedata_polissa.py
Reduir el canvi d'una query per valor a només 2 queries
Canal ERP va lent
Cada vegada que es volia consultar el llistat de pòlisses es feia una query extra per pòlissa consultada. 
Trigava **70 segons**.
Ara només se'n fan 2 independentment de les pòlisses que hi hagi. 
Ara triga **4 segons**.
=> Millorar rendiment de camp funció a la pòlissa

giscedata_facturacio_comer_som/giscedata_facturacio_report.py, giscedata_facturacio_comer_som/i18n/es_ES.po, giscedata_facturacio_comer_som/i18n/giscedata_facturacio_comer_som.pot, giscedata_facturacio_comer_som/report/components/amount_destination_td/amount_destination_td.mako, giscedata_facturacio_comer_som/tests/tests_FacturacioFacturaReport_some.py
Actualitzar l'apartat destí de la factura al BOE 2024
https://trello.com/c/lX56NS0i/334-actualitzar-pdf-amb-el-de-c%C3%A0rrecs-a-cada-partida-segons-boe-2024
percentatges BOE 2023 
percentatges BOE 2024
=> Update destino to 2024 BOE and fix FS

www_som/som_indexada_webforms_helpers.py, www_som/tests/indexed_prices_demo.xml, www_som/tests/tests_indexada_helpers.py
Take into account repeated prices and gaps
https://trello.com/c/SmjvQ0KZ/6096-serrells-mostrar-preus-dindexada-%C3%ADndexes-de-preus-0-4
Repeated prices are returned and gaps are not taking into account
Return new prices in case of repeated ones
Return gaps fiiled by nulls
=> ✨ Taking into account repeated prices and gaps

som_polissa_soci/giscedata_facturacio.py
El càlcul del donatiu voluntari es veu afectat per extralines negatives que aporten energia a diverses factures
https://secure.helpscout.net/conversation/2549959038/16796689
comptava com a positius kWh negatius.
realitza el càlcul correctament
=> Arreglar el calcul dels kWh per al donatiu voluntari

www_som/som_indexada_webforms_helpers.py, www_som/tests/tests_indexada_helpers.py
Retrieve from database excedent compensation measure in `kWh`
https://trello.com/c/Xv0KIdg1/6104-6md-tancament-preus-indexada
`MWh` as unit measure
`kWh` as unit measure
=> Change unit measure for excedent compensation: MWh -> kWh

som_account_invoice_pending/__init__.py, som_account_invoice_pending/account_invoice.py, som_account_invoice_pending/som_account_invoice_pending_data.xml, som_account_invoice_pending/tests/__init__.py, som_account_invoice_pending/tests/account_invoice_tests.py
Crear el nou estat pendent per marcar "pèrdues fact" i aplicar els automatismes demanats quan s'assigna l'estat a factures.
https://trello.com/c/nHjKeOHG/295-get-etiqueta-factures-client-a-p%C3%A8rdues
No existia
L'estat pendent existeix
som_account_invoice_pending
=> Crear nou estat pendent per factures “Pèrdues FACT”.

giscedata_facturacio_comer_som/giscedata_facturacio_report.py, giscedata_facturacio_comer_som/tests/tests_FacturacioFacturaReport_some.py, som_infoenergia/giscedata_polissa.py, som_infoenergia/migrations/5.0.24.5.0/post-0001_reload_to_create_a_new_configuration_variable.py, som_infoenergia/som_infoenergia_data.xml, som_polissa/giscedata_cups.py, som_polissa/giscedata_polissa.py, som_polissa/tests/giscedata_polissa_tests.py
Cal extreure la data del consum anual de forma mes ràpida que l'actual per tal de que sigui utilitzada per scripts d'update. 
https://trello.com/c/QfkXlelQ/309-ajustos-i-prioritzaci%C3%B3-m%C3%A8todes-de-c%C3%A0lcul-del-consum-anual-%C3%A0lies-conany
molt lent del ordre de 5 segons per petició
molt ràpid del ordre de 0.01 segons per petició amb menys overhead de memória
=> Càlcul de la data del consum anual de la factura en pdf de forma mes ràpida

som_account_invoice_pending/migrations/5.0.23.9.0/post-0004_migrate_attachments_mongo_id.py
Corregir script de migració de adjunts de mongo pel comportament estrany de datas_ mongo
https://somenergia.openproject.com/projects/som-energia/boards/15/details/131/overview
Si intentes modificar el datas_mongo des del ORM, es fan coses estranyes. S'ha de fer per SQL.
Es fa des de SQL
=> OP#131 [#131] Corregir script de migració de adjunts de mongo pel comportament estrany de datas_ mongo

account_invoice_som/report/account_invoice_som.mako, som_gurb/__terp__.py, som_gurb/data/som_gurb_data.xml, som_gurb/models/som_gurb_cups.py, som_gurb/security/ir.model.access.csv, som_gurb/tests/tests_gurb_initial_quota.py, som_gurb/views/som_gurb_cups_view.xml, som_gurb/wizard/__init__.py, som_gurb/wizard/wizard_gurb_create_initial_invoice.py, som_gurb/wizard/wizard_gurb_create_initial_invoice_view.xml
Permetre a les usuàries la creació de factures d'inscripció de GURB. 
https://somenergia.openproject.com/work_packages/250
- La lògica de creació de les factures no estava acabada.
- No hi havia cap `wizard` per cridar aquesta lògica.
- En el _report_ de la factura de comptabilitat s'arrodonien les unitats de les línies.
- Nou `wizard` a `som.gurb.cups` per crear factures d'inscripció.
- La creació de les factures ja funciona segons els requisits demanats.
- Millora en la gestió d'errors.
- En el _report_ de la factura de comptabilitat es mostren dos decimals de les unitats de les línies.
=> Creació de factures d'inscripció de GURB

som_autoreclama/som_autoreclama_state_updater.py
El cercador de polisses de autoreclama per el procés automàtic no cerca polisses correctament.
https://hs.somenergia.coop/conversation/1989?folder_id=259
No troba les pòlisses de baixa molt antigues per desactivar-les
Troba les polisses i les desactiva
=> El cercador de polisses de autoreclama no cerca totes les polisses

.github/workflows/integration_config.yml, som_gurb/models/som_gurb.py
Permetre passar els tests amb una branca diferent de `rolling_erp01` posant una etiqueta amb el format `GHA_branch_{}` en la _pull request_.
- Sempre es passaven els tests amb la branca `rolling_erp01`.
- Si es vol es pot triar la branca amb la qual es volen passar els tests.
=> Allow to choose ERP branch with a tag

som_switching/giscedata_atc.py, som_switching/giscedata_switching.py, som_switching/migrations/5.0.24.5.1/post-0001-update-security.py, som_switching/security/ir.model.access.csv, som_switching/tests/__init__.py, som_switching/tests/tests_unlink_switching.py, som_switching/wizard/__init__.py, som_switching/wizard/wizard_switching_multi_change.py
Capar que es puguin esborrar ATR vinculats a cacs (i ben pensat, que mai es borrin ATRs simplement :P)
https://somenergia.openproject.com/projects/som-energia/work_packages/90/
Es poden esborrar ATRs i per falta de referencies es lia parda
Ara es cancel·len, a més sota certes condicions, i cancel·lant tb CACs realcionats
=> Cancel ATR instead of deleting, and refactor to avoid infinite loops

som_infoenergia/som_enviament_massiu.py, som_infoenergia/som_infoenergia_data.xml, som_infoenergia/som_infoenergia_enviament.py, som_infoenergia/som_infoenergia_lot.py
Treure max_proc dels workers
Xat
Podíem definir el màxim de workers que es creaven per enviar infoenergies en paralel.
Ja no el podem definir perquè GISCE ha limitat que el max_proc depengui del load average del servidor on es crida els autoworkers.
https://github.com/gisce/autoworker/pull/19/
=> Treure max_proc dels workers

som_facturacio_switching/tests/test_giscedata_facturacio_importacio_linia.py
Arreglar tests de som_facturacio_switching
Petava un test que necessita un camp que estava a la branca gisce/developer però no a som-energia/rolling_erp01
Saltem el test, amb referència a la PR https://github.com/gisce/erp/pull/19431 que s'haurà tornar a passar quan tinguem aquesta PR a som-energia/rolling_erp01
=> Arreglar tests de som_facturacio_switching

giscedata_facturacio_comer_som/report/components/invoice_details_td_generation/invoice_details_td_generation.mako
Mostrar correctament els preus a la factura en pdf
https://hs.somenergia.coop/conversation/1547?folder_id=259
=> El valor del preu de generació es mostra en notació científica quan preus negatius amb indexada a la factura en pdf

som_autoreclama/migrations/5.0.24.6.0/post-0001_reload_atc_states.py, som_autoreclama/som_autoreclama_state_data.xml
Crear una nova condició per tal que una pòlissa en estat d'autoreclama "Revisar" surti cap a l'estat "Correcte" si arriben F1's que permeten que la "Dates últimes lectures facturades De F1" estigui a menys de (60?) dies
https://hs.somenergia.coop/conversation/10945?folder_id=259
Les pòlisses en estat "Revisar" s'hi quedaven per sempre fins que manualment algú les revisés
Si entren F1's que permeten que la "Dates últimes lectures facturades De F1" estigui a menys de (60?) dies canvien l'estat a "Correcte"
=> Nova condició d'autoreclama per sortir del estat "Revisar"

som_atc/models/giscedata_switching_helpers.py
Automatitzar l'activació i tancament dels cac's generats pel D1 quan el titular de la instal·lació es diferent al titular del contracte
https://somenergia.openproject.com/projects/som-energia/work_packages/98/activity
treball manual per part de l'equip de gestió de contractes
automàtic
=> Obre i tanca automàticmanent els CAC's creats pel D1 si titular diferent

.github/workflows/reusable_workflow.yml
Afegim el repo openerp_som_addons al workflow reusable de GA per reusabilitat des de repos de mòduls del ERP que necessiten a la vegada mòduls de som_addons.
https://github.com/Som-Energia/somenergia-generationkwh/pull/152
https://github.com/Som-Energia/somenergia-generationkwh/pull/153
Quan es cridava el reusable_workflow des d'un altre repo, no es comprovaba que aquest repo estava clonat.
Es comprova sempre si aquest repo està clonat i sinó ho està, el clona.
=> Afegim som_addons al GA per reusabilitat

som_inversions/report/report_liquidacions.py
Fa més robust el codi fent que busqui les dates per expressió regular en comptes de per espais (fallava segons l'idioma)
=> Fix report liquidacions using regex

som_polissa/giscedata_polissa.py, som_polissa/giscedata_switching_helpers.py, som_polissa/tests/som_polissa_tests.py, som_switching/giscedata_switching_m1.py
Quan es fa un canvi de titular de la pòlissa, posar el camp "procés de tall" aka 'process_id' de la pòlissa a "Default process" si el nou titular es empresa de forma automàtica.
https://somenergia.openproject.com/projects/som-energia/work_packages/278/activity
Deixava el proces_id antic i generava problemes en el workflow de l'equip de cobraments
Es seteja correctament
=> Posar el camp procés de tall de la pòlissa a Default process si nou titular es empresa

som_polissa/giscedata_polissa_view.xml, som_polissa/migrations/5.0.24.9.0/post-0001_reload_polissa_cau_view_for_multicau.py
Corretgir la vista de tree de Contractes en CAU per adaptar-se al nou estat dels autoconsums (multiCAU)
https://somenergia.openproject.com/work_packages/156
Es disposava d'un camp ac_state per a veure l'estat de l'únic auto associat
Ara poden haver varis CAUs associats i cadascun pot tenir un estat diferent per tant no es pot mostrar tal qual en un camp.
=> Correcció de vista de Contractes en CAU per a multicaus.

som_polissa/giscedata_polissa.py, som_polissa/migrations/5.0.23.9.0/post-0002_create_dni_attachment_categ.py, som_polissa/som_polissa_data.xml, som_polissa/tests/giscedata_polissa_tests.py
Molaria tenir d'alguna manera identificats els attachments dels DNI.
Ara mateix l'ET no té una manera "estàndard" de guardar aquests attachments i moltes vegades ho posen com a adjunt de la polissa.
Això pot suposar un problema perquè hi ha partners amb és d'una polissa i clar... No totes les polisses tindran el DNI adjunt.
Aquesta PR crea una categoria pels document d'identitat i si aquest s'adjunta al titular, sortirà a la pestanya de documents relacionats de la polissa que ensenya el camp funció `related_attachments`
https://somenergia.openproject.com/projects/som-energia/work_packages/286/activity
Cadascú ho feia com volia
S'intenta estandaritzar una manera
=> 🦺 DNI Attachments 

giscedata_facturacio_comer_som/giscedata_facturacio_report.py, giscedata_facturacio_comer_som/report/components/contract_data_td/contract_data_td.mako
Amb l'arribada de la modificació de multi_CAU, hem de mostrar els diferents CAU's associats al contracte a la factura
https://somenergia.openproject.com/projects/som-energia/work_packages/309/activity
Només es mostrava 1
Es mostren les que estiguin relacionats
Fer rebase abans de fer traduccions i aplicar per evitar col·lisions amb:
https://github.com/Som-Energia/openerp_som_addons/pull/685
https://github.com/Som-Energia/openerp_som_addons/pull/678
https://github.com/Som-Energia/openerp_som_addons/pull/691
giscedta_facturacio_comer_som
=> Mostrar els mútiples CAU's en la factura en pdf

som_polissa/giscedata_polissa_view.xml, som_polissa/migrations/5.0.24.5.0/post-0002_remove_autoconsum_id_from_view.py
La polissa ja no te el camp de autoconsum_id a la vista base de la polissa i es treu del modul personalitzat
https://trello.com/c/6H6ATHED/5999-multicaus-gisce
https://github.com/gisce/erp/pull/19697
- som_polissa
som_polissa, post-0002_remove_autoconsum_id_from_view, **v24.5.0**
=> Treure autoconsum_id de la vista de polissa

som_facturacio_switching/giscedata_facturacio_importacio_linia.py
Permetre carregar F1s amb tipus d'autoconsum inactius
https://somenergia.openproject.com/work_packages/377/activity
No entrava el F1 per que petava per valors de camp selection
Es modifica el tipus d'autoconsum inactiu per 00
=> Correcció de tipus d'autoconsum inactiu en carregar un F1

som_gurb/models/report_backend_som_gurb_documents.py, som_gurb/models/som_gurb.py, som_gurb/views/som_gurb_view.xml
L'acord de repartiment sortia malament perquè posava la propietària de la teulada com a productora. Amb aquest nou camp solucionem aquest error
Relacionada amb https://somenergia.openproject.com/wp/84
Sortia la propietària de la coberta
Surt l'empresa productora
Update de som_gurb
=> ✨ (gurb): Afegeix productora a la fitxa gurb

som_polissa/__init__.py, som_polissa/__terp__.py, som_polissa/giscedata_autoconsum.py, som_polissa/giscedata_autoconsum_view.xml, som_polissa/migrations/5.0.24.9.0/post-0001_new_fields_on_generadors.py
Afegir nous camps al generador d'autoconsum
https://somenergia.openproject.com/projects/som-energia/work_packages/403/activity
N/D
Es creen nous camps al generador:
- Potencia sortida
- Energia acumulable
- som_polissa
- som_polissa - post-0001_new_fields_on_generadors.py
=> Afegir nous camps al generador d'autoconsum

som_account_invoice_pending/models/som_consulta_pobresa.py, som_account_invoice_pending/models/update_pending_states.py, som_account_invoice_pending/tests/test_som_consulta_pobresa.py
Evitar marcar falsament factures com a pobresa quan no ho són
https://freescout.somenergia.coop/conversation/122000?folder_id=87
Es marcava sempre que hi havia una consulta recent com a pobresa
Només es marca com a pobresa en cas que el resultat de la consulta sigui positiu
=> fix checking consulta resolution

som_informe/report/components/InvoiceF1NG/InvoiceF1NG.py, som_informe/report/components/InvoiceF1R/InvoiceF1R.py, som_informe/report/components/component_utils.py
Arreglar part del informe on s'anava a buscar una linia de la factura, però en alguns casos en els quals una factura tenia un periode entre dos anys hi ha dos linies per el mateix periode (una per any), i en el informe per tant es veien dades incompletes (total facturat).
https://hs.somenergia.coop/conversation/45710?folder_id=103
=> Fix som_informe more than 1 line when different years

som_account_invoice_pending/models/som_consulta_pobresa.py, som_account_invoice_pending/tests/test_som_consulta_pobresa.py
Arreglar el funcionament dels estats pendents, en el moment de tancar les consultes de pobresa energètica.
https://freescout.somenergia.coop/conversation/6290097?folder_id=283
Es movien factures que no s'havien de moure.
- No moure l'estat pendent de les factures quan la consulta pobresa es negativa.
- Quan la consulta és positiva, moure les factures que estan en un estat posterior a "Consulta pobresa" i anterior als estats calaixos, a l'estat "Pobresa energètica"
=> 🐛 No moure l'estat pendent de les factures quan la consulta pobresa es negativa

som_facturacio_flux_solar/__init__.py, som_facturacio_flux_solar/giscedata_facturacio.py
Comptar en el mode 0 de Flux Solar només les línies dessitjades de la factura.
https://somenergia.openproject.com/projects/flux-solar/work_packages/438/activity
Es compensa la totalitat de la factura (com a màxim)
Es tenen en compte només les línies de:
- energia (totes les possibles)
- potència (totes les potències possibles)
- lloguer de comptador
- bo social
- Impostos (novetat)
=> Mode 0 de Flux Solar custom per a Som Energia

som_facturacio_flux_solar/giscedata_facturacio.py
Corregir el comportament de l'ERP a l'hora d'arrodonir el "total_energia"
SAC: `240685`
N/A
S'arrodoneix el total d'energia al segon decimal.
=> Corregir arrodoniment en el total d'energia

som_facturacio_flux_solar/giscedata_bateria_virtual_origen.xml, som_facturacio_flux_solar/migrations/5.0.25.1.0/post-0001_update_origin_view.py
Mostrar data inici generació descomptes als origens de Flux Solar
- Incidència 9350 No es generen Sols tot i estar la bateria bé Àmbit Comercialització
El camp existia però no era visible
Es mostra el camp
=> Mostrar data inici generació descomptes als origens de Flux Solar

som_atc/models/giscedata_switching_helpers.py
No es cridaven canvis fets pels D1 perquè el nom de la funció s'ha canviat
https://freescout.somenergia.coop/conversation/7906036?folder_id=87
Es cridava _crear_autoconsum
Es crida _crear_autoconsum_from_d1
=> 🐛 (atr) Arreglar canvi de nom d'una funció "punxada"

som_polissa/giscedata_polissa_view.xml, som_polissa/migrations/5.0.24.9.0/post-0002_reload_polissa_view_for_no_estimable.py
🧹 (polissa): Posar com a readonly el check de no estimable
https://somenergia.openproject.com/wp/554
Sortia que es podia editar
Readonly
=> 🧹 (polissa): Posar com a readonly el check de no estimable

som_autoreclama/som_autoreclama_state_updater.py, som_infoenergia/giscedata_polissa.py
A partir de la intervenció, les cadenes son unicode i el codi existent falla
https://freescout.somenergia.coop/conversation/7905822?folder_id=87
Falla i fa rollback
No falla i envia el que ha d'enviar
- ERP crons
=> FIX arreglar enviament de correus quan les dades venen en unicode

giscedata_facturacio_comer_som/__init__.py, giscedata_facturacio_comer_som/__terp__.py, giscedata_facturacio_comer_som/giscedata_facturacio_comer_data.xml, giscedata_facturacio_comer_som/giscedata_facturacio_factura.py, giscedata_facturacio_comer_som/giscedata_facturacio_factura.xml, giscedata_facturacio_comer_som/invoice_pdf_storer.py, giscedata_facturacio_comer_som/migrations/5.0.24.11.0/manual_migration.py, giscedata_facturacio_comer_som/migrations/5.0.24.11.0/migration_query.sql, giscedata_facturacio_comer_som/migrations/5.0.24.11.0/post-0001_create_enviat_mail_id_field_in_factura.py, giscedata_facturacio_comer_som/report/giscedata_facturacio_comer_som.py, giscedata_facturacio_comer_som/requirements.txt, giscedata_facturacio_comer_som/sql/query_fact_to_pdf_store.sql, giscedata_facturacio_comer_som/tests/__init__.py, giscedata_facturacio_comer_som/tests/tests_FacturacioFacturaReport_some.py, giscedata_facturacio_comer_som/tests/tests_invoice_pdf_storer.py, scripts/store_unsent_pdf_invoices.py
Permetre emmagatzemar i recuperar les factures en pdf sense forçar la regeneració agafant les emmagatzemades amb anterioritat com adjunts als correus
https://somenergia.openproject.com/projects/som-energia/work_packages/488/activity
Les factures es regeneraven cada cop, companyes han de recuperar-les de HS o de adjunts del correu
Es recupera dels correus prèviament enviats o s'emmagatzemen
https://github.com/Som-Energia/openerp_som_addons/pull/747
giscedata_facturacio_comer_som
=> Emmagatzemar les factures en pdf  i recuperar les ja guardades

som_crawlers/models/som_crawlers_task_step.py
El portal de Constancia-Aren ha canviat i ara al baixar els fitxers, els baixa en carpetes. Per poder-los carregar correctament al ERP primer els hem de treure.
https://somenergia.openproject.com/projects/som-energia/work_packages/471/activity
No funcionava la càrrega de fitxes XML perquè estaven dins d'un zip amb carpetes
Carrega al ERP un zip de fitxers .xml sense carpetes intermitges
=> Desempaquetar els fitxers baixats de la distri Constancia-Aren

som_polissa_soci/sql/llistat_socis.sql
Arregla la consulta per el CSV que fa servir comunicacio per obtenir socis i adreçes, agafant nomes la primera adreça i tenint en compte si el soci s'ha donat de baixa per evitar alguns bruts extres que sortien.
https://freescout.somenergia.coop/conversation/7937995?folder_id=87
=> Fix llistat socis sql (get first address, check baixa soci)

som_facturacio_flux_solar/giscedata_facturacio.py
Evitar de totes les maneres que quedin factures de flux solar amb cèntims per facturar que tinguin saldo de sobra disponible al flux.
SAC Gisce [240685]
=> Darrera comprovació a Flux Solar

som_leads_polissa/wizard/wizard_importador_leads_comercials.py, som_leads_polissa/wizard/wizard_importador_leads_comercials_view.xml
Els leads si tenien totes les dades possibles s'activaven i creaven la pòlissa
És un comportament no desitjat
S'activava automàticament 
No l'activem automàticament
Reiniciar ERP
=> 🐛 (leads): Millor no activar els leads per defecte a l'assistent

som_indexada/giscedata_hourly_energy_price.py
Habilitar al càlcul del preu mensual pels subsistemes CAN i BAL
Incidència comunicada a través d'Slack
No es calculava en cas de no tenir els fitxers en cache
S'indica l'ESIOS Token a fer servir per a la descàrrega.
=> Indicar ESIOS Token en el cálcul per Balears i Canàries

giscedata_facturacio_comer_som/giscedata_facturacio_report.py, giscedata_facturacio_comer_som/report/components/invoice_details_td_bo_social_2023/invoice_details_td_bo_social_2023.mako
Amb el canvi d'any arribe linies de repercusió del bo social dividides per dates, cal arreglar la visualització del bo social partit a la factura en pdf
NOTA: es modifica el mako amb compte de no tocar les línies per no tenir que refer les traduccions
Incidència facturació #2025 #happynewyear
Es mostra una única línia sumat els conceptes però mostra malament el preu
Es mostren 2 línies separades
=> Arreglar la visualització del bo social partit a la factura en pdf

som_polissa_soci/somenergia_soci.py
Pel comptador de socis de la web, si es vol fer amb aquestes condicions un simple domini va molt lent, per això l'OOQUERY
=> Add a exact and fast soci count

som_facturacio_flux_solar/giscedata_facturacio.py
Incrementa a 2 cèntims el llidar de flux solar
240685
Es limitava el llindar per a recalcular el total a descomptar de Flux Solar a 1 cèntim.
Es limita a 2 cèntims per que per temes d'arrodoniment de Python pot desquadrar d'un cèntim al càlcul de l'IVA i per un altre cèntim al càlcul de l'IESE.
=> Incrementa a 2 cèntims el llidar de flux solar

som_facturacio_comer/giscedata_facturacio_correu_backend.py
Obtenir un flag a la plantilla de mail de factura per poder mostrar un bloc de text durant un periode de temps en pòlisses amb distri E-DISTRIBUCIÓN referent a CAMPANYA DE SUBSTITUCIÓ DE COMPTADORS E-DISTRIBUCIÓN
https://somenergia.openproject.com/wp/633
No podiem condicionar el text a mostrar
Tenim un un flag '**flag_msg_counters_edistri**' per condicionar el text a mostrar requerit
=> Obtenir un flag a la plantilla de mail de factura per poder mostrar un bloc de text en pòlisses amb distri E-DISTRIBUCIÓN

som_account_invoice_pending/tests/test_giscedata_polissa.py
✅ Split writes because write state force datetime to now
RedTestBuster
=> ✅ Split writes because write state force datetime to now

giscedata_facturacio_comer_som/giscedata_facturacio_factura.py
https://freescout.somenergia.coop/conversation/7976387?folder_id=87
S'estava copiant tota la info del mail i ens molestava en les abonadores, que quedaven linkades al mail de la factura original i per tant al imprimir el PDF agafava també l'original.
=> Fix invoice copy_data to dont copy mail info

giscedata_facturacio_comer_som/giscedata_facturacio_comer_data.xml, giscedata_facturacio_comer_som/tests/tests_FacturacioFacturaReport_some.py
Avoid disabling the entire store system in an update
=> Move invoice store pdf config to noupdate data

giscedata_facturacio_som/giscedata_facturacio.py, giscedata_facturacio_som/tests/tests_giscedata_facturacio_som.py
Arreglar la funció search quan l'operador no és ilike
https://freescout.somenergia.coop/conversation/7981701?folder_id=87
https://somenergia.openproject.com/projects/som-energia/work_packages/618/activity
Si no apareix un "%" en el camp número de factura o origen de factura, substitueix l'operador que sigui per un "=". Això provocava que quan es feia una cerca per aquests camps amb un operador com per exemple "!=", el comportament dels resultats era contrari al buscat amb l'optimització.
Només substitueix l'operador per un "=" quan l'operador és un "ilike".
=> Arreglar la funció search quan l'operador no és ilike

som_autoreclama/tests/test_som_autoreclama_states.py
Arreglar els tests que fallen del mòdul
Bugbuster
Fallen
No fallen
=> ✅🐛 Arreglar testos de som_autoreclama que fallen per versió nova d'ERP

som_switching/tests/tests_wizard_validate_d101.py, som_switching/wizard/wizard_validate_d101.py
Arreglar els testos de som_switching
=> fix som_switching_tests

som_polissa/giscedata_cups.py, som_polissa/tests/__init__.py, som_polissa/tests/giscedata_cups_tests.py
✨🌐  Add new auto subseccion translations and description methods
https://freescout.somenergia.coop/conversation/7993509?folder_id=283
S'havien de traduïr aquests camps en cada report/email
Es poden cridar els mètodes de CUPS per obtenir la descripció d'aquests dos camps en l'idioma que es vulgui:
```python
cups_obj.get_autoconsum_description(cursor, uid, '00', 'ca_ES')
cups_obj.get_auto_tipus_subseccio_description(cursor, uid, '00', 'es_ES')
```
O importar directament la taula en format diccionari:
```python
from som_polissa.giscedata_cups import TABLA_113_dict
from som_polissa.giscedata_cups import TABLA_133_dict
```
=> ✨🌐  Add new auto subseccion translations and description methods

som_municipal_taxes/__terp__.py, som_municipal_taxes/models/som_municipal_taxes_config.py, som_municipal_taxes/wizard/wizard_creacio_remesa_pagament_taxes.py
♻️  Adaptar als canvis del MunicipalTaxesInvoicingReport
https://freescout.somenergia.coop/conversation/7993508?folder_id=87
Amb l'antic Wizard no hi havia el paràmetre group_type, sempre es feia trimestral.
Amb aquesta PR https://github.com/gisce/erp/pull/20310 s'afegeix l'opció de fer els càlculs mensuals o trimestrals. Nosaltres seguim generant-los trimestralment.
També s'ha adaptar el resultat que ara és un Dataframe.
=> ♻️  Adaptar als canvis del MunicipalTaxesInvoicingReport

som_municipal_taxes/__terp__.py, som_municipal_taxes/data/som_municipal_taxes_data.xml, som_municipal_taxes/demo/som_municipal_taxes_demo.xml, som_municipal_taxes/migrations/5.0.24.9.0/post-00003_new_journal_som_municipal_taxes.py, som_municipal_taxes/tests/test_wizard_creacio_remesa_pagament_taxes.py, som_municipal_taxes/wizard/wizard_creacio_remesa_pagament_taxes.py, som_municipal_taxes/wizard/wizard_creacio_remesa_pagament_taxes.xml, som_municipal_taxes/wizard/wizard_presentacio_redsaras.xml
Per poder pagar remeses de l'impost municipal des del ERP, ha d'haver-hi una factura pel mig.
https://somenergia.openproject.com/projects/som-energia/work_packages/551/activity
No es pot pagar la remesa perquè les línies no corresponen a factures
Les línies de la remesa són factures
=> [CiF] Remesa Ajuntaments 1,5% per factura

som_auvidi/giscedata_polissa.py, som_auvidi/wizard/wizard_load_servei_gen_records_from_file.py
No assignar pòlisses cancelades/baixa al servei de generacio al importar participants
https://somenergia.openproject.com/projects/som-energia/work_packages/517/activity
- Es buscava qualssevol pòlissa amb el mateix CUPS
- S'ignoren les pòlisses `cancel·lades` o en estat de `baixa`
=> No assignar pòlisses cancelades/baixa al servei de generacio al importar participants

som_facturacio_switching/giscedata_facturacio_switching_error_data.xml, som_facturacio_switching/migrations/5.0.25.3.0/post-0001_reaload_switching_errors.py
Cal modificar el tipus del error d'importació 3043 d'avís a crític per tal de que pari i no permeti continuar, però només per som
https://somenergia.openproject.com/projects/som-energia/work_packages/618/activity
era warning i permetia continuar facturant
es crític i para el pipeline de facturació del contracte
som_facturacio_switching
=> Canvia el tipus del error d'importació 3043 de avís a crític

.github/workflows/reusable_workflow.yml
Disabled failed CI when update coveralls fail
Ens falla de tant en tant la pujada a coveralls i ens fa petar el CI
https://github.com/Som-Energia/openerp_som_addons/actions/runs/14702131835/attempts/1
Si falla el servidor de coveralls, peta tot el pipeline.
Si falla el servidor de coveralls, no peta tot el pipeline.
=> Disabled failed CI when update coveralls fail

som_gurb/models/giscedata_facturacio.py
El producte Enterprise no existia al gurb
X
El producte Enterprise no es validava i no feia linia extra
S'evalua el producte Enterprise i es fa linia extra
=> 🔧 (gurb) Afegir enterprise_product_id al service

somre_ov_module/sql/get_forecast_measures.sql
Sols mostrar les previsions horàries a l'OV de Representa
💡 Donar-li una pensada si caldria afegir-ho com a paràmetre indicant si es volen: _totes, horàries o quathoràries_ al [entry_point measures ](https://github.com/Som-Energia/openerp_som_addons/blob/main/somre_ov_module/models/somre_ov_production_data.py#L21) i conseqüentment al mètode del backend i la query.
https://freescout.somenergia.coop/conversation/8004516?folder_id=87
Mostrava totes, horàries i quarthoràries
Sols mostra les horàries
=> 🚧 (ov_representa) Only hourly forecast measurements are shown in ov_rep

giscedata_facturacio_comer_som/report/components/invoice_details_td_energy_tolls/invoice_details_td_energy_tolls.mako
corregir notació científica en els peatges d'energia si números molt petits
https://freescout.somenergia.coop/conversation/7972661?folder_id=259
es mostrava en notació científica de l'estil 2.8e-6
es mostra correctament
=> 🐛 corregir notació científica en els peatges d'energia si números molt petits

giscedata_facturacio_comer_som/giscedata_facturacio_report.py, giscedata_facturacio_comer_som/i18n/es_ES.po, giscedata_facturacio_comer_som/i18n/giscedata_facturacio_comer_som.pot, giscedata_facturacio_comer_som/migrations/5.0.25.5.0/post-0001_load_translations.py, giscedata_facturacio_comer_som/report/components/energy_consumption_detail_td/energy_consumption_detail_td.css, giscedata_facturacio_comer_som/report/components/energy_consumption_detail_td/energy_consumption_detail_td.mako, giscedata_facturacio_comer_som/report/components/energy_consumption_detail_td_base/energy_consumption_detail_td_base.mako, giscedata_facturacio_comer_som/report/components/energy_consumption_detail_td_collective/energy_consumption_detail_td_collective.mako, giscedata_facturacio_comer_som/report/components/energy_consumption_detail_td_surplus/energy_consumption_detail_td_surplus.mako
Mostrar la informació dels autoconsums col·lectius a la factura en pdf arrel de l'ntroducció de la millora dels multicaus en avançament a ATR3.0
https://somenergia.openproject.com/projects/som-energia/work_packages/309/activity
no es mostrava la informació
Es mostra la informació
Fer rebase abans de fer traduccions i aplicar per evitar col·lisions amb:
https://github.com/Som-Energia/openerp_som_addons/pull/685
https://github.com/Som-Energia/openerp_som_addons/pull/678
FET 02/09/2024
giscedata_facturacio_comer_som
=> Nou sub component per mostrar l'informació dels autoconsums col·lectius al pdf de la factura

som_switching/giscedata_switching_helpers.py
Cobrir casuística no contemplada per als M105
https://freescout.somenergia.coop/conversation/8009539?folder_id=185
S'assumia que els M1s de canvi de titular per subrogació sempre eren M102
Ara contemplem també els M105
=> 🐛 Fix 'ct_baixa_mailchimp'

som_facturacio_switching/giscedata_facturacio_importacio_linia.py
Mostrar per defecte 00 - Sin Autoconsumo al llistat de fitxers F1 importats quan el node TipoSubseccion no esta al F1 (o sigui sense autoconsum)
https://somenergia.openproject.com/projects/som-energia/work_packages/729/activity
mostrava en blanc
es mostra 00
=> 🐛 Mostrar per defecte 00 - Sin Autoconsumo al llistat de fitxers F1 si no TipoSubseccion al F1

som_facturacio_flux_solar/giscedata_facturacio.py
Evitar que quedin linies extres de bateria virtual amb quantitats pendents d'aplicar.
https://somenergia.openproject.com/projects/som-energia/work_packages/844/activity
No es tenien en compte les linies d'indeminitzacio, per lu que en alguns casos, es creava una linia extra d'una quantitat que no era la que s'acabava aplicant a la factura realment.
Si que es te en compte.
=> Tenir en compte les linies d'indemnització per calcular el descompte de bateria virtual

som_gurb/__terp__.py, som_gurb/models/giscedata_switching.py, som_switching/giscedata_switching_activation_data.xml, som_switching/migrations/5.0.25.6.0/post-0001_m105_SR_new_activation.py, som_switching/models/giscedata_switching_helpers.py, som_switching/tests/tests_activacions_m1.py
Necessitem que quan arriben casos M105 SR (canvi de l'acord de repartiment), el cas ATR es tanque automàticament i envie un nou correu segons el que s'especifica a la targeta.
https://somenergia.openproject.com/wp/814
PR plantilla nou correu:
https://github.com/Som-Energia/somenergia-oomakotest/pull/188
A dia de hui apareix aquest error al casos ATR M105 (S)[R] Mod. Acord repartiment/fitxer coeficients:
> Resultado Activación:
> ERROR: No se trata de un cambio de titular (S / A) con tipo de cambio "sin subrogación" (T) o "con subrogación" (S), caso Procés M1 pel CUPS: XXXX
En cas de ser M105 SR, es tanca al cas i s'envia un mail nou.
🚧 _Casuística de GURB_
=> ✨ Automatitzar ATR M105 (S)[R] Mod. Acord repartiment/fitxer coeficients 

som_switching/giscedata_switching_notification_data.xml
✨ Afegir nos casos de configuració de notificacions de switching
https://somenergia.openproject.com/projects/cim-erp/work_packages/865/activity
No estaven separats per motius, o s'activaven tots els M2 05 o cap.
Es poden activar segons motiu
=> [GContractes] Nous formats correus M2

scripts/create_migration_script.py, som_switching/migrations/5.0.24.5.0/post-0004_ADD_M1_02_notification_config_update_views_and_fields.py
Millorar script de creació de scripts de migració
No
- Afegia la variabla pooler quan no la necessitava i t'obligava a acceptar els canvis del pre-commit
- Barrejava data.xml i security.csv fent que si es carregava primer el csv, petava l'script.
- Només afegeix pooler quan el fa servir
-  Ara carrega primer els xml i després els csv.
=> Millorar script de creació de scripts de migració

som_switching/giscedata_switching_notification_data.xml, som_switching/migrations/5.0.25.9.0/post-0001_fix_m2_sw_notifications.py
Corregir les plantilles de notificacio de casos ATR perque tinguin el pas correcte. El primer element del camp 'conditions' correspon al pas del procés. 
Com que estava posat el `01`, fallava perque no existia el model `giscedata.switching.m2.01`
SAC GISCE -> `246968`
=> Corregir Plantillas de notificaciones de M2 05

giscedata_facturacio_comer_som/giscedata_facturacio_factura.py
Evitar una lectura al mongo que no serveix per res i està donant problemes en l'enviament de factures, fent que falli i s'enviin dos cops
https://freescout.somenergia.coop/conversation/8020502?folder_id=87
=> Fix unnecessary mongo read

giscedata_facturacio_comer_som/giscedata_facturacio_report.py
Mostrar les dades d'autoconsum col·lectiu quan hi ha un F1 tipus R pel mig
https://freescout.somenergia.coop/conversation/8034909?folder_id=87
no es mostra o es motren les dades d'un altre F1 del mateix contracte
es mostren les dades correctes
=> 🐛 Mostrar les dades d'autoconsum col·lectiu quan hi ha un F1 tipus R pel mig

som_facturacio_comer/giscedata_facturacio_factura_view.xml, som_facturacio_comer/migrations/5.0.25.9.0/pre-0001_remove_unnecessary_tree_views.py
Eliminar vistes duplicades per haver-se afegit a ERP
https://somenergia.openproject.com/projects/som-energia/work_packages/941
Mostrar camp a llistats de factures
Degut a PR https://github.com/gisce/erp/pull/24693 ja no son necessaris i de fet son redundants ja que es mostren per duplicat els camps de generacio_kwh
=> Eliminar vistes duplicades per haver-se afegit a ERP

som_leads_polissa/giscedata_crm_lead.py, som_leads_polissa/tests/tests_som_lead_www.py, som_partner_account/partner.py, som_partner_account/tests/test_membership.py
La primera incidència ja estava resolta, aquest PR només arregla una mica els tests i simplifica els writes.
La segona és simplement canviar el comportament per sempre renovar el número de sòcia, i adaptar els leads perque tot segueixi funcionant com sempre :)
https://freescout.somenergia.coop/conversation/8037651?folder_id=103
https://freescout.somenergia.coop/conversation/8035038?folder_id=103
=> 🐛⚡ Lead fixes: member number, tests and write performance

som_leads_polissa/www/som_lead_www.py
Sembla ser que GISCE llegeix desde crear_cas_atr les observacions de la polissa i busca el camp proces amb aquest nom concret.
Amb aquest PR ens assegurem que el codi de GISCE funcionarà (fa una copia del camp al guardar-lo)
https://freescout.somenergia.coop/conversation/8035520?folder_id=69
=> 🐛 Fix proces name in polissa observations

som_facturacio_comer/giscedata_polissa.py, som_facturacio_flux_solar/giscedata_polissa.py
Tindre tot el codi referent a les personalitzacions de flux solar en el modul `som_facturacio_flux_solar` per evitar que la gent de gisce es torni boja intentant saber què té el flux solar diferent en els mòduls de som.
Origen del codi que es mou: https://github.com/Som-Energia/openerp_som_addons/pull/413
=> Moure codi de flux solar al modul correcte

.github/workflows/reusable_workflow.yml
Descarregar repo OMIE perquè ja no està a pypi.org
Checks
GISCE tenia el repositori https://github.com/gisce/omie en obert i publicava els paquests a Pypi.org
GISCE ha tancat el repositori i deixa de publicar versions al pypi.org i ha canviat els requirements.txt dels mòduls que el necessiten, per a que vaig a buscar el repositori privat en comptes de a pypi.org.
=> Descarregar repo OMIE perquè ja no està a pypi.org

som_gurb/migrations/5.0.24.5.0/post-0003_fix_gurb_wizard_copy_paste_migrate_data.py, som_gurb/wizard/wizard_atr_gurb_model_view.xml
Tornar a crear botó que s'havia sobreescrit. Canviar nom incorrecte que sobreescrivia.
https://freescout.somenergia.coop/conversation/8050356?folder_id=87
No apareixia botó d'un assistent
Ara torna a aparèixer
=> Copy/Paste ha sobreescrit el botó que portava a un wizard

.github/workflows/reusable_workflow.yml
No fem servir ja Coveralls.io, fem servir el Codecov
Tests setmanals
Pujàvem als dos serveis (Coveralls i Codecov) i vam fer aquesta PR https://github.com/Som-Energia/openerp_som_addons/pull/866 perquè a vegades fallava al Coveralls, però sembla que aquest flag no funciona quan s'executa amb multithreat, per tant millor ho traiem.
Puja el coverage només al Codecov, que respecta històric de referència de coverage per mòdul.
=> No pujar coverage a Coveralls.io

som_leads_polissa/giscedata_crm_lead.py, som_leads_polissa/tests/tests_som_lead_www.py
Afegir error descriptiu quan un lead falla pq el número de sòcia està mal escrit
- XATS i incidències varies
Error "list intex out of range"
Error que diu el que està passant
=> 🐛 (lead) Afegir error descriptiu quan un lead falla pq el número de sòcia està mal escrit

som_polissa_condicions_generals/models/report_backend_ccpp.py
Arreglar paths, ja que a la PR https://github.com/Som-Energia/openerp_som_addons/pull/1006 s'han modificat els paths del mòdul som_polissa
Tests del diumenge
giscedata_cups estava a l'arrel del mòdul
giscedata_cups esta dins la carpeta modules del mòdul
=> 🐛 Arreglar path de giscedata_cups.TABLA_113
